### ISSUE TITLE
Data Source Statistics SQL error

### ISSUE THREAD

**Issue by eschoeller** [Cacti/cacti#1033]
I'm getting this error in my logs when I enable Data Source Statistics collection

<pre>
2017/10/16 00:24:42 - DBCALL ERROR: A DB Exec Failed!, Error:1064, SQL:'INSERT INTO data_source_stats_hourly_cache (local_data_id, rrd_name, time, `value`) VALUES (30775, 'infeedPhaseCurrent1', '2017-10-16 00:24:30', 311), (30775, 'infeedPhaseCurrent2', '2017-10-16 00:24:30', 461), (30775, 'infeedPhaseCurrent3', '2017-10-16 00:24:30', 483), (30776, 'infeedPhaseVoltage3', '2017-10-16 00:24:30', 2393), (30776, 'infeedPhaseVoltage2', '2017-10-16 00:24:30', 2401), (30776, 'infeedPhaseVoltage1', '2017-10-16 00:24:30', 2412), (30777, 'infeedPhaseVoltage2', '2017-10-16 00:24:30', 2399), (30777, 'infeedPhaseVoltage1', '2017-10-16 00:24:30', 2411), (30777, 'infeedPhaseVoltage3', '2017-10-16 00:24:30', 2392), (30778, 'infeedFactor2', '2017-10-16 00:24:30', 92), (30778, 'infeedFactor1', '2017-10-16 00:24:30', 94), (30778, 'infeedFactor3', '2017-10-16 00:24:30', 94), (30779, 'infeedFactor3', '2017-10-16 00:24:30', 95), (30779, 'infeedFactor2', '2017-10-16 00:24:30', 97), (30779, 'infeedFactor1', '2017-10-16 00:24:30', 94), (30780, 'humidity', '2017-10-16 00:24:30', 41), (30780, 'temperature', '2017-10-16 00:24:30', 230), (30835, 'total_it_watts_ups', '2017-10-16 00:24:38', 47045.5523656), (30835, 'average_latency', '2017-10-16 00:24:38', 39), (30835, 'data_hit_rate', '2017-10-16 00:24:38', 100), (30836, 'total_it_watts_pdu', '2017-10-16 00:24:38', 121734.282716667), (30836, 'average_latency', '2017-10-16 00:24:38', 99), (30836, 'data_hit_rate', '2017-10-16 00:24:38', 100), (30958, 'apparentPower', '2017-10-16 00:24:34', 1017), (30959, 'energy', '2017-10-16 00:24:34', 29000), (30963, 'vaUsed', '2017-10-16 00:24:34', 101), (30964, 'vaUsed', '2017-10-16 00:24:34', 94), (30965, 'powerFactor', '2017-10-16 00:24:34', 84), (30966, 'powerFactor', '2017-10-16 00:24:34', 88), (30967, 'infeedLoad2', '2017-10-16 00:24:34', 315), (30967, 'infeedLoad1', '2017-10-16 00:24:34', 345), (30967, 'infeedLoad3', '2017-10-16 00:24:34', 239), (30968, 'infeedLoad3', '2017-10-16 00:24:34', 189), (30968, 'infeedLoad1', '2017-10-16 00:24:34', 190), (30968, 'infeedLoad2', '2017-10-16 00:24:34', 341), (31043, 'udpInErrors', '2017-10-16 00:24:36', NULL), (31043, 'udpNoPorts', '2017-10-16 00:24:36', NULL), (31044, 'tempProbeReading', '2017-10-16 00:24:36', 24), (31045, 'voltageProbeReading', '2017-10-16 00:24:36', 210000), (31047, 'voltageProbeReading', '2017-10-16 00:24:36', 208000), (31048, 'coolingDeviceReadin', '2017-10-16 00:24:36', 3600), (31049, 'coolingDeviceReadin', '2017-10-16 00:24:36', 3600), (31050, 'coolingDeviceReadin', '2017-10-16 00:24:36', 3600), (31051, 'coolingDeviceReadin', '2017-10-16 00:24:36', 3600), (31052, 'coolingDeviceReadin', '2017-10-16 00:24:36', 3600), (31054, 'amperageReading', '2017-10-16 00:24:36', 4), (31055, 'amperageReading', '2017-10-16 00:24:36', 2), (31057, 'cpu_nice', '2017-10-16 00:24:36', NULL), (31058, 'cpu_system', '2017-10-16 00:24:36', 35.266666666667), (31059, 'cpu_user', '2017-10-16 00:24:36', 28.95), (31060, 'load_1min', '2017-10-16 00:24:36', 0.07), (31062, 'load_15min', '2017-10-16 00:24:36', 0.00), (31063, 'load_5min', '2017-10-16 00:24:36', 0.03), (31065, 'mem_cache', '2017-10-16 00:24:36', 5821908), (31193, 'inst_volts_an', '2017-10-16 00:24:39', 287.947), (31193, 'inst_volts_bn', '2017-10-16 00:24:39', 286.890), (31193, 'inst_volts_cn', '2017-10-16 00:24:39', 286.636), (31193, 'inst_volts_ab', '2017-10-16 00:24:39', 497.814), (31193, 'inst_volts_bc', '2017-10-16 00:24:39', 496.632), (31193, 'inst_volts_ca', '2017-10-16 00:24:39', 497.578), (31193, 'inst_freq', '2017-10-16 00:24:39', 60.01), (31193, 'inst_current_a', '2017-10-16 00:24:39', 7.441), (31193, 'inst_current_b', '2017-10-16 00:24:39', 6.265), (31193, 'inst_current_c', '2017-10-16 00:24:39', 5.245), (31193, 'inst_current_n', '2017-10-16 00:24:39', 1.895), (31193, 'inst_watts', '2017-10-16 00:24:39', 3974), (31193, 'inst_vars', '2017-10-16 00:24:39', -3707), (31193, 'inst_va', '2017-10-16 00:24:39', 5447), (31193, 'inst_power_factor', '2017-10-16 00:24:39', 0.729), (31202, 'wathrec', '2017-10-16 00:24:39', 85053580), (31202, 'wathdel', '2017-10-16 00:24:39', 0), (31202, 'wathnet', '2017-10-16 00:24:39', 85053580), (31202, 'wathtot', '2017-10-16 00:24:39', 85053600), (31202, 'varhpos', '2017-10-16 00:24:39', 19300), (31202, 'varhneg', '2017-10-16 00:24:39', -84045780), (31202, 'varhnet', '2017-10-16 00:24:39', -), (31213, 'inst_volts_an', '2017-10-16 00:24:39', 287.990), (31213, 'inst_volts_bn', '2017-10-16 00:24:39', 286.970), (31213, 'inst_volts_cn', '2017-10-16 00:24:39', 286.631), (31213, 'inst_volts_ab', '2017-10-16 00:24:39', 497.922), (31213, 'inst_volts_bc', '2017-10-16 00:24:39', 496.699), (31213, 'inst_volts_ca', '2017-10-16 00:24:39', 497.616), (31213, 'inst_freq', '2017-10-16 00:24:39', 60.01), (31213, 'inst_current_a', '2017-10-16 00:24:39', 10.651), (31213, 'inst_current_b', '2017-10-16 00:24:39', 8.443), (31213, 'inst_current_c', '2017-10-16 00:24:39', 7.164), (31213, 'inst_current_n', '2017-10-16 00:24:39', 5.650), (31213, 'inst_watts', '2017-10-16 00:24:39', 6329), (31213, 'inst_vars', '2017-10-16 00:24:39', -1476.953), (31213, 'inst_va', '2017-10-16 00:24:39', 7500), (31213, 'inst_power_factor', '2017-10-16 00:24:39', 0.843), (31222, 'wathrec', '2017-10-16 00:24:39', 122936110), (31222, 'wathdel', '2017-10-16 00:24:39', -3240), (31222, 'wathnet', '2017-10-16 00:24:39', 122932880), (31222, 'wathtot', '2017-10-16 00:24:39', 122939360), (31222, 'varhpos', '2017-10-16 00:24:39', 451320), (31222, 'varhneg', '2017-10-16 00:24:39', -73881270) ON DUPLICATE KEY UPDATE `value`=VALUES(`value`)'
</pre>
<pre>
2017/10/16 00:24:42 - CMDPHP ERROR: A DB Exec Failed!, Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '), (31213, 'inst_volts_an', '2017-10-16 00:24:39', 287.990), (31213, 'inst_volts' at line 1
</pre>
<pre>
2017/10/16 00:24:42 - CMDPHP SQL Backtrace: (/poller.php: 539 process_poller_output)(/lib/poller.php: 508 dsstats_poller_output)(/lib/dsstats.php: 681 db_execute)(/lib/database.php: 135 db_execute_prepared)(/lib/database.php: 208 cacti_debug_backtrace)
</pre>

This is the part that trips it up:
<pre>
mysql> INSERT INTO data_source_stats_hourly_last (local_data_id, rrd_name, `value`, calculated) VALUES (31202, 'varhnet', '2017-10-16 00:24:39', -) ON DUPLICATE KEY UPDATE `value`=VALUES(`value`), `calculated`=VALUES(`calculated`);
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`), `calculated`=VALUES(`calculat' at line 1
</pre>

I am not sure why this particular data source is returning '-' values but it's not working with the INSERT very well. The '-' should probably be NULL.

**Comment by cigamit** [comment]
Yup, searching the code in just a few minutes.

**Comment by cigamit** [comment]
I've committed a patch.  Let me know if it works.  The only think I can think of is that this is a holdover from the earlier versions of dsstats.

**Comment by cigamit** [comment]
No feedback.  I'm sure it's working though.

**Comment by eschoeller** [comment]
Sorry I just had a chance to upgrade. I'm still seeing these issues:
``` 2017/11/12 23:16:46 - DBCALL ERROR: A DB Exec Failed!, Error:1054, SQL:'INSERT INTO data_source_stats_hourly_last (local_data_id, rrd_name, `value`, calculated) VALUES (51154, 'infeedLoad2', 389, 389), (51154, 'infeedLoad1', 375, 375), (51155, 'infeedLoad2', 415, 415), (51155, 'infeedLoad1', 367, 367), (51155, 'infeedLoad3', 382, 382), (51156, 'infeedPower3', 455, 455), (51156, 'infeedPower2', 424, 424), (51156, 'infeedPower1', 391, 391), (51157, 'infeedPower1', 403, 403), (51157, 'infeedPower2', 449, 449), (51157, 'infeedPower3', 430, 430), (51158, 'infeedVoltage3', 2093, 2093), (51158, 'infeedVoltage2', 2092, 2092), (51158, 'infeedVoltage1', 2087, 2087), (51159, 'infeedVoltage2', 2094, 2094), (51159, 'infeedVoltage1', 2092, 2092), (51159, 'infeedVoltage3', 2090, 2090), (51160, 'infeedApparent1', 451, 451), (51160, 'infeedApparent3', 493, 493), (51160, 'infeedApparent2', 457, 457), (51161, 'infeedApparent1', 467, 467), (51161, 'infeedApparent2', 482, 482), (51161, 'infeedApparent3', 461, 461), (51164, 'infeedCrest3', 18, 18), (51164, 'infeedCrest1', 19, 19), (51164, 'infeedCrest2', 16, 16), (51165, 'infeedCrest1', 17, 17), (51165, 'infeedCrest2', 16, 16), (51165, 'infeedCrest3', 18, 18), (51168, 'infeedPhaseCurrent3', 237, 237), (51168, 'infeedPhaseCurrent1', 218, 218), (51168, 'infeedPhaseCurrent2', 218, 218), (51169, 'infeedPhaseCurrent1', 223, 223), (51169, 'infeedPhaseCurrent2', 231, 231), (51169, 'infeedPhaseCurrent3', 220, 220), (51170, 'infeedPhaseVoltage3', 2093, 2093), (51170, 'infeedPhaseVoltage2', 2092, 2092), (51170, 'infeedPhaseVoltage1', 2087, 2087), (51171, 'infeedPhaseVoltage3', 2090, 2090), (51171, 'infeedPhaseVoltage1', 2092, 2092), (51171, 'infeedPhaseVoltage2', 2095, 2095), (51172, 'infeedFactor2', 93, 93), (51172, 'infeedFactor1', 86, 86), (51172, 'infeedFactor3', 92, 92), (51173, 'infeedFactor2', 93, 93), (51173, 'infeedFactor1', 86, 86), (51173, 'infeedFactor3', 93, 93), (53245, 'ups1_efficiency', NaN, NaN), (53245, 'ups2_efficiency', NaN, NaN), (54341, 'btuhr', 540336.312500, 540336.312500), (54342, 'kw', 158.372559, 158.372559), (58968, 'PhasePowerFactor1', 100, 100), (58968, 'PhasePowerFactor2', 100, 100), (58968, 'PhasePowerFactor3', 98, 98), (58968, 'PhasePowerFactor4', 97, 97), (58968, 'PhasePowerFactor5', 100, 100), (58968, 'PhasePowerFactor6', 100, 100), (58968, 'PhasePowerFactor7', 98, 98), (58968, 'PhasePowerFactor8', 100, 100), (58968, 'PhasePowerFactor9', 100, 100), (58970, 'BankCurrent1', 120, 120), (58970, 'BankCurrent2', 96, 96), (58970, 'BankCurrent3', 168, 168), (58970, 'BankCurrent4', 114, 114), (58970, 'BankCurrent5', 109, 109), (58970, 'BankCurrent6', 68, 68), (58970, 'BankCurrent7', 111, 111), (58970, 'BankCurrent8', 111, 111), (58970, 'BankCurrent9', 74, 74), (58972, 'ModulePower1', 809, 809), (58972, 'ModulePower2', 619, 619), (58972, 'ModulePower3', 626, 626), (58975, 'ModuleApparent1', 817, 817), (58975, 'ModuleApparent2', 625, 625), (58975, 'ModuleApparent3', 631, 631), (59108, 'PhaseCurrent1', 53, 53), (59108, 'PhaseCurrent2', 21, 21), (59108, 'PhaseCurrent3', 39, 39), (59109, 'PhasePower1', 58, 58), (59109, 'PhasePower2', 25, 25), (59109, 'PhasePower3', 19, 19) ON DUPLICATE KEY UPDATE `value`=VALUES(`value`), `calculated`=VALUES(`calculated`)'
2017/11/12 23:16:46 - CMDPHP ERROR: A DB Exec Failed!, Error: Unknown column 'NaN' in 'field list'
2017/11/12 23:16:46 - CMDPHP SQL Backtrace: (/poller.php: 539 process_poller_output)(/lib/poller.php: 508 dsstats_poller_output)(/lib/dsstats.php: 710 db_execute)(/lib/database.php: 135 db_execute_prepared)(/lib/database.php: 208 cacti_debug_backtrace) ```

**Comment by cigamit** [comment]
Missed that case.  'Nan' for guages....

**Comment by cigamit** [comment]
Resolved.
