### ISSUE TITLE
Cannot create threshold from graph

### ISSUE THREAD

**Issue by interduo** [Cacti/cacti#118]
graph.php?local_graph_id=5886&rra_id=0

1. The icons nearby graph are not in vertical align. (Classic Theme)

2. Choose function Create Threshold (clicking by nearby graph icon)
It will show You New dialog 'Create Threshold from Template' but the button 'Continue' doesn't work.

**Comment by ronytomen** [comment]
Shouldn't this be in the Thold plugin issue tracker?

**Comment by interduo** [comment]
Firstly I was creating this issue in cacti / thold but after consideration I moved it here.

**Comment by ronytomen** [comment]
The theme issue, agreed, probably not a Thold plugin issue.  The second item, totally a plugin issue.

**Comment by cigamit** [comment]
Two things:
1) On issue 1., you need to attach an image.
2) On issue 2., please open bugs under thold.

**Comment by interduo** [comment]
![not_alligned](https://cloud.githubusercontent.com/assets/17087236/21562152/742d0aa4-ce76-11e6-8409-c58724b3876f.png)

**Comment by cigamit** [comment]
Both are resolved.

**Comment by interduo** [comment]
No - it is not resolved:

2017-01-03 17:25:24 - CMDPHP SQL Backtrace: (/plugins/thold/thold.php: 61 thold_add)(/plugins/thold/thold.php: 166 thold_add_graphs_action_execute)(/plugins/thold/thold_webapi.php: 59 db_fetch_assoc)(/lib/database.php: 310 db_fetch_assoc_prepared)(/lib/database.php: 348 cacti_debug_backtrace)
2017-01-03 17:25:24 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/thold/thold.php: 61 thold_add)(/plugins/thold/thold.php: 166 thold_add_graphs_action_execute)(/plugins/thold/thold_webapi.php: 52 CactiErrorHandler)(/lib/functions.php: 4199 cacti_debug_backtrace)
2017-01-03 17:25:24 - ERROR PHP NOTICE in Plugin 'thold': Undefined index: data_template_id in file: /var/www/html/cacti/plugins/thold/thold_webapi.php on line: 52
2017-01-03 17:25:24 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/thold/thold.php: 61 thold_add)(/plugins/thold/thold.php: 166 thold_add_graphs_action_execute)(/plugins/thold/thold_webapi.php: 48 CactiErrorHandler)(/lib/functions.php: 4199 cacti_debug_backtrace)
2017-01-03 17:25:24 - ERROR PHP NOTICE in Plugin 'thold': Undefined index: local_data_id in file: /var/www/html/cacti/plugins/thold/thold_webapi.php on line: 48
2017-01-03 17:25:24 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/thold/thold.php: 61 thold_add)(/plugins/thold/thold.php: 166 thold_add_graphs_action_execute)(/plugins/thold/thold_webapi.php: 47 CactiErrorHandler)(/lib/functions.php: 4199 cacti_debug_backtrace)
2017-01-03 17:25:24 - ERROR PHP NOTICE in Plugin 'thold': Undefined index: data_template_id in file: /var/www/html/cacti/plugins/thold/thold_webapi.php on line: 47
2017-01-03 17:25:19 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/thold/thold.php: 61 thold_add)(/plugins/thold/thold.php: 169 thold_add_graphs_action_prepare)(/plugins/thold/thold_webapi.php: 323 CactiErrorHandler)(/lib/functions.php: 4199 cacti_debug_backtrace)
2017-01-03 17:25:19 - ERROR PHP NOTICE in Plugin 'thold': Undefined index: HTTP_REFERER in file: /var/www/html/cacti/plugins/thold/thold_webapi.php on line: 323
2017-01-03 17:25:16 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/thold/thold.php: 61 thold_add)(/plugins/thold/thold.php: 169 thold_add_graphs_action_prepare)(/plugins/thold/thold_webapi.php: 323 CactiErrorHandler)(/lib/functions.php: 4199 cacti_debug_backtrace)
2017-01-03 17:25:16 - ERROR PHP NOTICE in Plugin 'thold': Undefined index: HTTP_REFERER in file: /var/www/html/cacti/plugins/thold/thold_webapi.php on line: 323
2017-01-03 17:25:05 - CMDPHP SQL Backtrace: (/plugins/thold/thold.php: 61 thold_add)(/plugins/thold/thold.php: 166 thold_add_graphs_action_execute)(/plugins/thold/thold_webapi.php: 59 db_fetch_assoc)(/lib/database.php: 310 db_fetch_assoc_prepared)(/lib/database.php: 348 cacti_debug_backtrace)
2017-01-03 17:25:05 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/thold/thold.php: 61 thold_add)(/plugins/thold/thold.php: 166 thold_add_graphs_action_execute)(/plugins/thold/thold_webapi.php: 52 CactiErrorHandler)(/lib/functions.php: 4199 cacti_debug_backtrace)
2017-01-03 17:25:05 - ERROR PHP NOTICE in Plugin 'thold': Undefined index: data_template_id in file: /var/www/html/cacti/plugins/thold/thold_webapi.php on line: 52
2017-01-03 17:25:05 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/thold/thold.php: 61 thold_add)(/plugins/thold/thold.php: 166 thold_add_graphs_action_execute)(/plugins/thold/thold_webapi.php: 48 CactiErrorHandler)(/lib/functions.php: 4199 cacti_debug_backtrace)
2017-01-03 17:25:05 - ERROR PHP NOTICE in Plugin 'thold': Undefined index: local_data_id in file: /var/www/html/cacti/plugins/thold/thold_webapi.php on line: 48
2017-01-03 17:25:05 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/thold/thold.php: 61 thold_add)(/plugins/thold/thold.php: 166 thold_add_graphs_action_execute)(/plugins/thold/thold_webapi.php: 47 CactiErrorHandler)(/lib/functions.php: 4199 cacti_debug_backtrace)
2017-01-03 17:25:05 - ERROR PHP NOTICE in Plugin 'thold': Undefined index: data_template_id in file: /var/www/html/cacti/plugins/thold/thold_webapi.php on line: 47
