### ISSUE TITLE
Traffic graphs on new device do not work

### ISSUE THREAD

**Issue by ronytomen** [Cacti/cacti#135]
![screen shot 2017-01-04 at 11 04 57 pm](https://cloud.githubusercontent.com/assets/5140624/21668708/65acd288-d2d2-11e6-8752-3f67fadcff67.png)

Unable to view graphs of newly created device because of rrdtool issue.

RRDTool Says:
ERROR: invalid y-grid format

**Comment by ronytomen** [comment]
![screen shot 2017-01-04 at 11 08 59 pm](https://cloud.githubusercontent.com/assets/5140624/21668752/ce6447ca-d2d2-11e6-866f-a0cfd5c0801c.png)
Invalid value in the graph template.

**Comment by cigamit** [comment]
Please try again with the latest build.  This is resolved.  However, note, that you must import at least one Device Template during install.

**Comment by 0xygen8** [comment]
nope, still an issue in the latest build

**Comment by ron-slc** [comment]
I confirm.  This still occurs on a new-installation of cacti-develop, as downloaded from GitHub 15 minutes ago.

RRDTool Says:
ERROR: invalid y-grid format

RRDtool Version 1.5.5
OS: Ubuntu 16.04 / Xenial
