### ISSUE TITLE
Enhancement: Allow uptime to be a variable for use with graphs

### ISSUE THREAD

**Issue by camerabob** [Cacti/cacti#1551]
Using any template, it would be a benefit to see the system uptime along with total data passed to/from an interface (such as Traffic - bits in/out). This would make sense when troubleshooting knowing if the value you see is in line with the length of time the device has been up. Not having to go back to reference the device management page would definitely be a bonus.

Thanks for your time

Bob

**Comment by cigamit** [comment]
Yea, I've thought about this many times.  It's actually a boring graph except when you are trying to do event correlation or count the number times a node has rebooted during a finite period of time.  Won't work with the daily RRA level, but does provide some good information more in the near term.

**Comment by netniV** [comment]
Would it not be as simple as taking it from the hosts 'snmp_uptime_instance' field?

**Comment by netniV** [comment]
True, if the snmp daemon is restarted, it normally resets the uptime.

**Comment by xmacan** [comment]
I didn't find this issue before and I write small plugin for it
https://github.com/xmacan/plugin_uptime

**Comment by TheWitness** [comment]
Maybe we change spine/cmd.php to prefer the system uptime over the agent uptime.  Could add a lot of polling time though if the system uptime is not available.

**Comment by TheWitness** [comment]
This is fixed now.  New variable is |host_uptime|.

**Comment by camerabob** [comment]
Thank you b

Excuse any misspellings. I'm still getting used to this iGadget!

**Comment by TheWitness** [comment]
Thanks for staying active on the forums @camerabob.
