### ISSUE TITLE
[cacti 1.2.0] Unable to add new Graph Template Item

### ISSUE THREAD

**Issue by dsclassen** [Cacti/cacti#1594]
Attempting to add a new Graph Template Item by pressing the "+" in the top right corner results in a partially blank web page.

<img width="1203" alt="graph_template_err1" src="https://user-images.githubusercontent.com/8882563/39439024-076e196c-4c5b-11e8-8fc6-7e1a426b0096.png">
<img width="1200" alt="graph_template_err2" src="https://user-images.githubusercontent.com/8882563/39439025-0784e6e2-4c5b-11e8-9583-6679d0c0a246.png">

**Comment by netniV** [comment]
Can you see if you have any javascript console errors?   I think this is one area that we currently know is slightly broken and is being resolved.

**Comment by dsclassen** [comment]
<img width="1201" alt="graph_template_err3" src="https://user-images.githubusercontent.com/8882563/39440318-59e88840-4c5f-11e8-8513-1b5e1ce982e2.png">

**Comment by netniV** [comment]
I did see this:
```
commit a04a6be54b65579a13d811df5eb0d99c578f3a34
Author: cigamit <jimmy@sqmail.org>
Date:   Sat Apr 28 20:39:05 2018 -0500

    Resolving Issue #1581
    
    This first commit handles some of the API and adding from the Console >
    Graphs page.  Another commit coming on this issue.
```

**Comment by anarkia1976** [comment]
I have tested and no problem so far, i think is resolved in the latest develop branch.

**Comment by dsclassen** [comment]
I'm on 8f4d2cfc and still seeing the query error and a blank screen when attempting to add a new graph template item.

**Comment by netniV** [comment]
Any console or log errors?

**Comment by dsclassen** [comment]
The same as before: 

<img width="595" alt="jquery_error" src="https://user-images.githubusercontent.com/8882563/39601090-b6fb9c20-4ed5-11e8-8f83-abbe8a021dd4.png">

**Comment by dsclassen** [comment]
Give me some hints and I'll see what I can do to help.

**Comment by netniV** [comment]
There are two ways to get it to break at that point.  Open the develop console of your browser, and add a breakpoint or add `debugger;` to the layout.js just above the line in error above.  When you reload the javascript in your browser and open the development console, it should automatically break at that point.  Hovering over the 'value' variable should show the state of that variable.

**Comment by dsclassen** [comment]
<img width="1716" alt="debugger1" src="https://user-images.githubusercontent.com/8882563/39605402-26e67cf8-4ee5-11e8-812a-58239b58fbaf.png">

**Comment by dsclassen** [comment]
Still broken. Perhaps typeof is returning 'null' instead of 'undefined' ?

<img width="1710" alt="layout js err1" src="https://user-images.githubusercontent.com/8882563/39606023-16e0c540-4ee8-11e8-912f-cda17ddcf44f.png">
<img width="1165" alt="layout js err2" src="https://user-images.githubusercontent.com/8882563/39606024-16f5549c-4ee8-11e8-9e10-91df134f2770.png">

**Comment by dsclassen** [comment]
This works though!!

```diff --git a/include/layout.js b/include/layout.js
index e896c714..f599560b 100644
--- a/include/layout.js
+++ b/include/layout.js
@@ -2898,7 +2898,10 @@ $.widget('custom.dropcolor', {
                var regExp = /\(([^)]+)\)/;
                var hex   = regExp.exec(value);
 
-               this.wrapper.find('#bgc').css('background-color', '#'+hex[1]);
+               if ( hex != null) {
+                       this.wrapper.find('#bgc').css('background-color', '#'+hex[1]);
+               }
+
                this.input = $('<input class="ui-autocomplete-input ui-state-default ui-selectmenut-text" style="background:transparent;border:0px;margin-left:-22px;padding-right:3px;padding-left:22px;" value="'+value+'">')
                .appendTo(this.wrapper)
                .on('click', function() {```

**Comment by dsclassen** [comment]
OK. I made a pull request to fix this.
