### ISSUE TITLE
Edit data query -  Undefined variable

### ISSUE THREAD

**Issue by mdrons** [Cacti/cacti#1617]
Trying to add a suggested name to a data source and getting the following error messages.

attached is the cacti.log file, showing the same issue.
[dataquery.log](https://github.com/Cacti/cacti/files/1984406/dataquery.log)

Attached are the images from the browser.
![20180508_104149](https://user-images.githubusercontent.com/30851206/39764326-6998f474-52ad-11e8-9399-93a9c51c63dd.jpg)
![20180508_104137](https://user-images.githubusercontent.com/30851206/39764327-69ae3528-52ad-11e8-88b9-0f831b5ac7a1.jpg)

These are from the apache log file:
[Tue May 08 10:38:08.418961 2018] [reqtimeout:info] [pid 32716] [client 192.168.250.147:64633] AH01382: Request header read timeout
[Tue May 08 10:38:08.419716 2018] [reqtimeout:info] [pid 30720] [client 192.168.250.147:64632] AH01382: Request header read timeout
[Tue May 08 10:38:11.802617 2018] [deflate:debug] [pid 32439] mod_deflate.c(853): [client 192.168.250.147:64556] AH01384: Zlib: Compressed 28675 to 6675 : URL /cacti/data_queries.php, referer: http://10.16.0.10/cacti/graphs_new.php
[Tue May 08 10:38:12.116354 2018] [deflate:debug] [pid 30730] mod_deflate.c(853): [client 192.168.250.147:64568] AH01384: Zlib: Compressed 137230 to 16990 : URL /cacti/graphs_new.php, referer: http://10.16.0.10/cacti/graphs_new.php
[Tue May 08 10:38:14.605150 2018] [authz_core:debug] [pid 322] mod_authz_core.c(809): [client 192.168.250.147:64675] AH01626: authorization result of Require all granted: granted, referer: http://10.16.0.10/cacti/data_queries.php?action=item_edit&id=26&snmp_query_id=1
[Tue May 08 10:38:14.605189 2018] [authz_core:debug] [pid 322] mod_authz_core.c(809): [client 192.168.250.147:64675] AH01626: authorization result of <RequireAny>: granted, referer: http://10.16.0.10/cacti/data_queries.php?action=item_edit&id=26&snmp_query_id=1
[Tue May 08 10:38:14.621699 2018] [php7:notice] [pid 322] [client 192.168.250.147:64675] PHP Notice:  Undefined variable: header in /var/www/html/cacti/data_queries.php on line 255, referer: http://10.16.0.10/cacti/data_queries.php?action=item_edit&id=26&snmp_query_id=1
[Tue May 08 10:38:14.691567 2018] [authz_core:debug] [pid 322] mod_authz_core.c(809): [client 192.168.250.147:64675] AH01626: authorization result of Require all granted: granted, referer: http://10.16.0.10/cacti/data_queries.php?action=item_edit&id=26&snmp_query_id=1
[Tue May 08 10:38:14.691584 2018] [authz_core:debug] [pid 322] mod_authz_core.c(809): [client 192.168.250.147:64675] AH01626: authorization result of <RequireAny>: granted, referer: http://10.16.0.10/cacti/data_queries.php?action=item_edit&id=26&snmp_query_id=1
[Tue May 08 10:38:14.817875 2018] [deflate:debug] [pid 322] mod_deflate.c(853): [client 192.168.250.147:64675] AH01384: Zlib: Compressed 17747 to 3830 : URL /cacti/data_queries.php, referer: http://10.16.0.10/cacti/data_queries.php?action=item_edit&id=26&snmp_query_id=1

**Comment by netniV** [comment]
I've created a PR that should fix this issue in 1.2

**Comment by mdrons** [comment]
I still get the same error in the web browser, but the error in the log file is not there anymore.

**Comment by netniV** [comment]
What version of Cacti are you running on?

**Comment by mdrons** [comment]
version 1.2.0

 git log
commit 3c9e95398f973884a3b6df2649732ef03c7e6ec8 (HEAD -> develop, origin/develop, origin/HEAD)
Author: cigamit <jimmy@sqmail.org>
Date:   Tue May 8 17:50:21 2018 -0500

    Two more QA issues in installer

**Comment by cigamit** [comment]
Confirming that this is resolved now.
