### ISSUE TITLE
[1.2.0] Upgrade from 0.8.8h fails on poller_reindex statement

### ISSUE THREAD

**Issue by AndyLDEX** [Cacti/cacti#1902]
Hi,

   during upgrade I recieve the following errors:

1.0.5:

```
ALTER TABLE `poller_reindex` ADD PRIMARY KEY(host_id,data_query_id)	[Fail]
ALTER TABLE `poller_reindex` ADD PRIMARY KEY(host_id,data_query_id)	[Fail]
```

Checking the exact error from MySQL I see:

```

root@localhost [cacti]> ALTER TABLE poller_reindex DROP PRIMARY KEY, ADD PRIMARY KEY (host_id, data_query_id);
ERROR 1062 (23000): Duplicate entry '19-13' for key 'PRIMARY'
```

And here is the table detail:

```
| poller_reindex | CREATE TABLE `poller_reindex` (
  `host_id` mediumint(8) unsigned NOT NULL DEFAULT '0',
  `data_query_id` mediumint(8) unsigned NOT NULL DEFAULT '0',
  `action` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `present` tinyint(4) NOT NULL DEFAULT '1',
  `op` char(1) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `assert_value` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `arg1` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  PRIMARY KEY (`host_id`,`data_query_id`,`arg1`),
  KEY `present` (`present`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci 
```

This is reproduceable on one system, another 0.8.8h system I tested the upgrade on worked perfectly,

thanks, Andy.

**Comment by netniV** [comment]
This is a strange one because our thought was to add a de-dupe check but it appears that 1_0_5 already performs checks for duplicates in the current 1.2 branch.  Did you definitely get this error with the 1.2 upgrade?

Try running the following query for me:
```sql
SELECT host_id, data_query_id, count(*) AS totals 
                        FROM poller_reindex
                        GROUP BY host_id, data_query_id
```

**Comment by netniV** [comment]
Just updated the SQL slightly as I missed off the `> 1` check.

**Comment by netniV** [comment]
Also, it may be easier if you could export your database, compress it and email it to netniv@cacti.net, then let me know here so I can check it.

**Comment by AndyLDEX** [comment]
```
+---------+---------------+--------+
| host_id | data_query_id | totals |
+---------+---------------+--------+
|      19 |            13 |     24 |
+---------+---------------+--------+
1 row in set (0.00 sec)
```

**Comment by netniV** [comment]
I have a fix coming, once merged you'll be able to see if that gets sorted.  In the mean time, can you do the following query:

```sql
SELECT * FROM poller_reindex where host_id = 19 and data_query_id = 13
```

**Comment by AndyLDEX** [comment]
I've passed you the results to your email, also earlier the database dump,

thanks, Andy.

**Comment by netniV** [comment]
OK, thanks, that will be useful to test the fix as it seems quite specific to you. 👍

**Comment by cigamit** [comment]
My bad guys.  This was my fault.  Has to do with the Verify all indexes re-index method.  Just update to the latest development branch and rerun the upgrade_database.php with the forcever=1.1.38 and this issue should be resolved.

**Comment by AndyLDEX** [comment]
No, sorry still getting the same error. Im a bit sick today, maybe I did something wrong. Will retest now...

**Comment by netniV** [comment]
Hi Andy,

There are some more changes coming today.  Your upgrade is showing a number of 1.2 fails and we suspect it may be down to index lengths so we are investigating it.  With our own databases, we get zero fails so must be something specific to your data.

Thanks,

Mark.

**Comment by netniV** [comment]
![image](https://user-images.githubusercontent.com/9052188/45304633-685f9980-b510-11e8-97c5-70d3a8328a3b.png)

**Comment by cigamit** [comment]
Just merged!

**Comment by netniV** [comment]
Hi @AndyLDEX, just in case you're only receiving direct notifications, please download the latest development source and retry the upgrade.  As I've already done this successfully, I will close this issue now.
