### ISSUE TITLE
[1.2.0 beta 1 develop] - cannot get the number of CPU

### ISSUE THREAD

**Issue by pautiina** [Cacti/cacti#2032]
The lastest develop branch cannot get the number of CPU.
My OS: FreeBSD 11.2 stable
PHP 7.0.30 
```
2018/10/08 22:35:01 - SPINE: Poller[Main Poller] DEBUG: The Value of Active Threads is 8 for Device ID 521
--
2018/10/08 22:35:01 - SPINE: Poller[Main Poller] Device[nas0] TH[1] DEBUG: HOST COMPLETE: About to Exit Device Polling Thread Function
2018/10/08 22:35:01 - SPINE: Poller[Main Poller] Device[nas0] TH[1] Total Time: 0.0091 Seconds
2018/10/08 22:35:01 - SPINE: Poller[Main Poller] Device[nas0] TH[1] ASSERT: '5' .eq. 'U' failed. Recaching host 'nas0', data query #9
2018/10/08 22:35:01 - SPINE: Poller[Main Poller] Device[nas0] TH[1] Recache DataQuery[9] SERVER: /var/www/cacti/scripts/ss_host_cpu.php 'ss_host_cpu' 'nas0' '521' '2:161:800:1:50:public::::::' 'num_indexes', output: U
2018/10/08 22:35:01 - PHPSVR WARNING: Function does not exist INC: 'ss_host_cpu.php' FUNC: ''ss_host_cpu'' PARMS: ''nas0' '521' '2:161:800:1:50:public::::::' 'num_indexes''
2018/10/08 22:35:01 - SPINE: Poller[Main Poller] Device[nas0] TH[1] Recache DataQuery[8] OID: .1.3.6.1.2.1.1.3.0, output: 67380
2018/10/08 22:35:01 - SPINE: Poller[Main Poller] Device[nas0] TH[1] Recache DataQuery[1] OID: .1.3.6.1.2.1.1.3.0, output: 67380
2018/10/08 22:35:01 - SPINE: Poller[Main Poller] Device[nas0] TH[1] RECACHE: Processing 3 items in the auto reindex cache for 'nas0'
2018/10/08 22:35:01 - SPINE: Poller[Main Poller] Updating Full System Information Table
2018/10/08 22:35:01 - SPINE: Poller[Main Poller] Device[nas0] DEBUG: Entering SNMP Ping
2018/10/08 22:35:01 - SPINE: Poller[Main Poller] Device[nas0] DEBUG: ICMP Device Alive, Try Count:1, Time:0.1712 ms
2018/10/08 22:35:01 - SPINE: Poller[Main Poller] Device[nas0] DEBUG: Entering ICMP Ping
2018/10/08 22:35:01 - SPINE: Poller[Main Poller] DEBUG: In Poller, About to Start Polling of Device for Device ID 521

```

**Comment by netniV** [comment]
Is the NAS definitely offerring up that value? What happens if you run the script manually at the command line?

**Comment by pautiina** [comment]
I run this: `php -q /var/www/cacti/scripts/ss_host_cpu.php 'ss_host_cpu' 'nas.isp.kh.ua' '521' '2:161:800:1:50:public::::::' 'num_indexes'`
but it gave me an empty result. The rest of the graphs were created normally.

**Comment by cigamit** [comment]
Likely older than 1.2, but resolved now.

**Comment by pautiina** [comment]
I still can't create CPU graphs for this device.
![image](https://user-images.githubusercontent.com/11805503/46651270-288be080-cba8-11e8-8a10-cb308027e835.png)
```
2018/10/09 10:08:01 - SPINE: Poller[1] DEBUG: In Poller, About to Start Polling of Device for Device ID 522
2018/10/09 10:08:01 - SPINE: Poller[1] Device[522] DEBUG: Entering ICMP Ping
2018/10/09 10:08:01 - SPINE: Poller[1] Device[522] DEBUG: ICMP Device Alive, Try Count:1, Time:0.1600 ms
2018/10/09 10:08:01 - SPINE: Poller[1] Device[522] DEBUG: Entering SNMP Ping
2018/10/09 10:08:01 - SPINE: Poller[1] Updating Full System Information Table
2018/10/09 10:08:01 - SPINE: Poller[1] Device[522] HT[1] RECACHE: Processing 3 items in the auto reindex cache for 'nas0'
2018/10/09 10:08:01 - SPINE: Poller[1] Device[522] HT[1] DQ[1] RECACHE OID: .1.3.6.1.2.1.1.3.0, (assert: 177305 < output: 183305)
2018/10/09 10:08:01 - SPINE: Poller[1] Device[522] HT[1] DQ[8] RECACHE OID: .1.3.6.1.2.1.1.3.0, (assert: 177305 < output: 183305)
2018/10/09 10:08:01 - SPINE: Poller[1] Device[522] HT[1] DQ[9] RECACHE OID: .1.3.6.1.2.1.1.3.0, (assert: 177305 < output: 183305)
2018/10/09 10:08:01 - SPINE: Poller[1] Device[522] HT[1] NOTE: There are '41' Polling Items for this Device
2018/10/09 10:08:01 - SPINE: Poller[1] Device[522] HT[1] DS[10062] SS[1] SERVER: /var/www/cacti/scripts/ss_host_disk.php ss_host_disk 'nas0' '522' '2:161:800:1:50:public::::::' 'get' 'total' '36', output: 207483056128
2018/10/09 10:08:01 - SPINE: Poller[1] Device[522] HT[1] DS[10062] SS[1] SERVER: /var/www/cacti/scripts/ss_host_disk.php ss_host_disk 'nas0' '522' '2:161:800:1:50:public::::::' 'get' 'used' '36', output: 160288768
2018/10/09 10:08:01 - SPINE: Poller[1] Device[522] HT[1] DS[10061] SS[3] SERVER: /var/www/cacti/scripts/ss_host_disk.php ss_host_disk 'nas0' '522' '2:161:800:1:50:public::::::' 'get' 'total' '35', output: 103993864192
2018/10/09 10:08:01 - SPINE: Poller[1] Device[522] HT[1] DS[10060] SS[0] SERVER: /var/www/cacti/scripts/ss_host_disk.php ss_host_disk 'nas0' '522' '2:161:800:1:50:public::::::' 'get' 'total' '34', output: 415996366848
2018/10/09 10:08:01 - SPINE: Poller[1] Device[522] HT[1] DS[10061] SS[4] SERVER: /var/www/cacti/scripts/ss_host_disk.php ss_host_disk 'nas0' '522' '2:161:800:1:50:public::::::' 'get' 'used' '35', output: 282624000
2018/10/09 10:08:01 - SPINE: Poller[1] Device[522] HT[1] DS[10059] SS[1] SERVER: /var/www/cacti/scripts/ss_host_disk.php ss_host_disk 'nas0' '522' '2:161:800:1:50:public::::::' 'get' 'total' '33', output: 195515146240
2018/10/09 10:08:01 - SPINE: Poller[1] Device[522] HT[1] DS[10060] SS[2] SERVER: /var/www/cacti/scripts/ss_host_disk.php ss_host_disk 'nas0' '522' '2:161:800:1:50:public::::::' 'get' 'used' '34', output: 47964160
2018/10/09 10:08:01 - SPINE: Poller[1] Device[522] HT[1] DS[10059] SS[4] SERVER: /var/www/cacti/scripts/ss_host_disk.php ss_host_disk 'nas0' '522' '2:161:800:1:50:public::::::' 'get' 'used' '33', output: 7906041856
2018/10/09 10:08:01 - SPINE: Poller[1] Device[522] HT[1] DS[10058] SS[2] SERVER: /var/www/cacti/scripts/ss_host_disk.php ss_host_disk 'nas0' '522' '2:161:800:1:50:public::::::' 'get' 'used' '31', output: 304242688
2018/10/09 10:08:01 - SPINE: Poller[1] Device[522] HT[1] DS[10058] SS[3] SERVER: /var/www/cacti/scripts/ss_host_disk.php ss_host_disk 'nas0' '522' '2:161:800:1:50:public::::::' 'get' 'total' '31', output: 12472053760
2018/10/09 10:08:01 - SPINE: Poller[1] Device[522] HT[1] DS[10057] SS[2] SERVER: /var/www/cacti/scripts/ss_host_disk.php ss_host_disk 'nas0' '522' '2:161:800:1:50:public::::::' 'get' 'used' '10', output: 0
2018/10/09 10:08:01 - SPINE: Poller[1] Device[522] HT[1] DS[10057] SS[4] SERVER: /var/www/cacti/scripts/ss_host_disk.php ss_host_disk 'nas0' '522' '2:161:800:1:50:public::::::' 'get' 'total' '10', output: 34359607296
2018/10/09 10:08:01 - SPINE: Poller[1] Device[522] HT[1] DS[10056] SS[4] SERVER: /var/www/cacti/scripts/ss_host_disk.php ss_host_disk 'nas0' '522' '2:161:800:1:50:public::::::' 'get' 'used' '9', output: 11350016
2018/10/09 10:08:01 - SPINE: Poller[1] Device[522] HT[1] DS[10056] SS[0] SERVER: /var/www/cacti/scripts/ss_host_disk.php ss_host_disk 'nas0' '522' '2:161:800:1:50:public::::::' 'get' 'total' '9', output: 12255232
2018/10/09 10:08:01 - SPINE: Poller[1] Device[522] HT[1] DS[10055] SS[1] SERVER: /var/www/cacti/scripts/ss_host_disk.php ss_host_disk 'nas0' '522' '2:161:800:1:50:public::::::' 'get' 'used' '8', output: 12283904
2018/10/09 10:08:01 - SPINE: Poller[1] Device[522] HT[1] DS[10055] SS[0] SERVER: /var/www/cacti/scripts/ss_host_disk.php ss_host_disk 'nas0' '522' '2:161:800:1:50:public::::::' 'get' 'total' '8', output: 17031168
2018/10/09 10:08:01 - SPINE: Poller[1] Device[522] HT[1] DS[10054] SS[0] SERVER: /var/www/cacti/scripts/ss_host_disk.php ss_host_disk 'nas0' '522' '2:161:800:1:50:public::::::' 'get' 'used' '7', output: 447500288
2018/10/09 10:08:01 - SPINE: Poller[1] Device[522] HT[1] DS[10054] SS[1] SERVER: /var/www/cacti/scripts/ss_host_disk.php ss_host_disk 'nas0' '522' '2:161:800:1:50:public::::::' 'get' 'total' '7', output: 447500288
2018/10/09 10:08:01 - SPINE: Poller[1] Device[522] HT[1] DS[10053] SS[0] SERVER: /var/www/cacti/scripts/ss_host_disk.php ss_host_disk 'nas0' '522' '2:161:800:1:50:public::::::' 'get' 'total' '6', output: 1724071936
2018/10/09 10:08:01 - SPINE: Poller[1] Device[522] HT[1] DS[10052] SS[4] SERVER: /var/www/cacti/scripts/ss_host_disk.php ss_host_disk 'nas0' '522' '2:161:800:1:50:public::::::' 'get' 'total' '3', output: 1005568000
2018/10/09 10:08:01 - SPINE: Poller[1] Device[522] HT[1] DS[10053] SS[0] SERVER: /var/www/cacti/scripts/ss_host_disk.php ss_host_disk 'nas0' '522' '2:161:800:1:50:public::::::' 'get' 'used' '6', output: 688648192
2018/10/09 10:08:01 - SPINE: Poller[1] Device[522] HT[1] DS[10051] SS[4] SERVER: /var/www/cacti/scripts/ss_host_disk.php ss_host_disk 'nas0' '522' '2:161:800:1:50:public::::::' 'get' 'total' '2', output: 630734848
2018/10/09 10:08:01 - SPINE: Poller[1] Device[522] HT[1] DS[10052] SS[2] SERVER: /var/www/cacti/scripts/ss_host_disk.php ss_host_disk 'nas0' '522' '2:161:800:1:50:public::::::' 'get' 'used' '3', output: 1000759296
2018/10/09 10:08:01 - SPINE: Poller[1] Device[522] HT[1] DS[10050] SS[0] SERVER: /var/www/cacti/scripts/ss_host_disk.php ss_host_disk 'nas0' '522' '2:161:800:1:50:public::::::' 'get' 'total' '1', output: 17132003328
2018/10/09 10:08:01 - SPINE: Poller[1] Device[522] HT[1] DS[10051] SS[0] SERVER: /var/www/cacti/scripts/ss_host_disk.php ss_host_disk 'nas0' '522' '2:161:800:1:50:public::::::' 'get' 'used' '2', output: 629772288
2018/10/09 10:08:01 - SPINE: Poller[1] Device[522] DEBUG: The NIFTY POPEN returned the following File Descriptor 37
2018/10/09 10:08:01 - SPINE: Poller[1] Device[522] HT[1] DS[10049] SCRIPT: perl /var/www/cacti/scripts/ping.pl 'nas0', output: 0.166
2018/10/09 10:08:01 - SPINE: Poller[1] Device[522] HT[1] DS[10050] SS[2] SERVER: /var/www/cacti/scripts/ss_host_disk.php ss_host_disk 'nas0' '522' '2:161:800:1:50:public::::::' 'get' 'used' '1', output: 2694950912
2018/10/09 10:08:01 - SPINE: Poller[1] Device[522] HT[1] DS[10067] SNMP: v2: nas0, dsname: traffic_in, oid: .1.3.6.1.2.1.31.1.1.1.6.6, value: 0
2018/10/09 10:08:01 - SPINE: Poller[1] Device[522] HT[1] DS[10067] SNMP: v2: nas0, dsname: traffic_out, oid: .1.3.6.1.2.1.31.1.1.1.10.6, value: 42
2018/10/09 10:08:01 - SPINE: Poller[1] Device[522] HT[1] DS[10066] SNMP: v2: nas0, dsname: traffic_out, oid: .1.3.6.1.2.1.31.1.1.1.10.4, value: 0
2018/10/09 10:08:01 - SPINE: Poller[1] Device[522] HT[1] DS[10066] SNMP: v2: nas0, dsname: traffic_in, oid: .1.3.6.1.2.1.31.1.1.1.6.4, value: 0
2018/10/09 10:08:01 - SPINE: Poller[1] Device[522] HT[1] DS[10065] SNMP: v2: nas0, dsname: traffic_out, oid: .1.3.6.1.2.1.31.1.1.1.10.3, value: 0
2018/10/09 10:08:01 - SPINE: Poller[1] Device[522] HT[1] DS[10065] SNMP: v2: nas0, dsname: traffic_in, oid: .1.3.6.1.2.1.31.1.1.1.6.3, value: 0
2018/10/09 10:08:01 - SPINE: Poller[1] Device[522] HT[1] DS[10064] SNMP: v2: nas0, dsname: traffic_out, oid: .1.3.6.1.2.1.31.1.1.1.10.2, value: 0
2018/10/09 10:08:01 - SPINE: Poller[1] Device[522] HT[1] DS[10064] SNMP: v2: nas0, dsname: traffic_in, oid: .1.3.6.1.2.1.31.1.1.1.6.2, value: 904404
2018/10/09 10:08:01 - SPINE: Poller[1] Device[522] HT[1] DS[10063] SNMP: v2: nas0, dsname: traffic_out, oid: .1.3.6.1.2.1.31.1.1.1.10.1, value: 2447800104
2018/10/09 10:08:01 - SPINE: Poller[1] Device[522] HT[1] DS[10063] SNMP: v2: nas0, dsname: traffic_in, oid: .1.3.6.1.2.1.31.1.1.1.6.1, value: 1085662611
2018/10/09 10:08:01 - SPINE: Poller[1] Device[522] HT[1] DS[10068] SNMP: v2: nas0, dsname: traffic_in, oid: .1.3.6.1.2.1.31.1.1.1.6.7, value: 606384370
2018/10/09 10:08:01 - SPINE: Poller[1] Device[522] HT[1] DS[10068] SNMP: v2: nas0, dsname: traffic_out, oid: .1.3.6.1.2.1.31.1.1.1.10.7, value: 2210403880
2018/10/09 10:08:01 - SPINE: Poller[1] Device[522] HT[1] DS[10069] SNMP: v2: nas0, dsname: traffic_in, oid: .1.3.6.1.2.1.31.1.1.1.6.8, value: 469783883
2018/10/09 10:08:01 - SPINE: Poller[1] Device[522] HT[1] DS[10069] SNMP: v2: nas0, dsname: traffic_out, oid: .1.3.6.1.2.1.31.1.1.1.10.8, value: 222520566
2018/10/09 10:08:01 - SPINE: Poller[1] Device[522] HT[1] Total Time: 0.082 Seconds
2018/10/09 10:08:01 - SPINE: Poller[1] Device[522] HT[1] DEBUG: HOST COMPLETE: About to Exit Device Polling Thread Function
2018/10/09 10:08:01 - SPINE: Poller[1] DEBUG: The Value of Active Threads is 7 for Device ID 522

```
![image](https://user-images.githubusercontent.com/11805503/46652320-65a5a200-cbab-11e8-9548-c55fef9becbc.png)

**Comment by netniV** [comment]
The index counts haven't changed so it's not picking up that there has been a change.  Use the verifyall option and it may rectify itself, then you can switch back.
