### ISSUE TITLE
Granting a user only permission to preview view, still brings him to the three after login

### ISSUE THREAD

**Issue by groentebroer** [Cacti/cacti#211]
Created a new user, only granted graph access in the "preview" view.

After login the user is still taken to the tree view.

![image](https://cloud.githubusercontent.com/assets/1811817/21978736/2adc9694-dbdc-11e6-99a3-89875c2f3a21.png)

**Comment by cigamit** [comment]
Resolved, thanks!  You may have to logoff and back on again once you have updated.

**Comment by groentebroer** [comment]
Confirmed, it works!

Related (also want to file a new issue if needed).
Dispite the fact that a user does not have any Console permission the console tab is still shown.
Clicking it displays the "error" page to login or to return...
