### ISSUE TITLE
1.2.1 I.E. and Chrome issues

### ISSUE THREAD

**Issue by jdcoats** [Cacti/cacti#2334]
After upgrade to 1.2.1 Cacti does not work with IE, and tabs/buttons within the mactrack interface do not work with chrome either. It appears everything is fine with Firefox. Is there some known compatibility work already in progress?

**Comment by netniV** [comment]
There is no known issues with any browser. I would suggest trying to clear caches and hit control-f5 or control-refresh.

**Comment by jdcoats** [comment]
I have tried, all of the suggestions and the result is the same with I.E. on multiple machines.

Dan Coats
IT/Network VoIP Engineer
Tallahassee Memorial Healthcare
Office 850-431-7014
Cell 850-567-2201
dan.coats@tmh.org<mailto:dan.coats@tmh.org>

*CONFIDENTIALITY NOTICE* The information contained in this email message is intended only for the personal and confidential use of the designated recipient(s) named above. This message may be an attorney/client or physician/patient communication, and as such, is privileged and confidential. If the reader of this message is not the intended recipient, you are hereby notified that you have received this document in error, and that any review, dissemination, distribution, or copying of this message is strictly prohibited. If you have received this email communication in error, please notify me immediately by telephone.

**Comment by jdcoats** [comment]
![screen shot 01-22-19 at 04 56 pm](https://user-images.githubusercontent.com/42470924/51567998-ab3e6000-1e66-11e9-8a97-b6d459c069ba.PNG)


screenshot of what I.E. does on multiple machines.

**Comment by jdcoats** [comment]
Confirmed on numerous other ie11 computers. Edge browser works but has the same limitations with some buttons DOM  jscript issues that chrome has. So far it looks like this version only works with Firefox

**Comment by netniV** [comment]
Take a look at the browser console log, are there any errors?

**Comment by cigamit** [comment]
Update to the latest layout.js and this should be resolved.  Confirmed on IE10.

**Comment by jdcoats** [comment]
![screen shot 01-23-19 at 08 57 am](https://user-images.githubusercontent.com/42470924/51611453-42e69180-1eed-11e9-8665-dcc6a3d1bf1b.PNG)

**Comment by jdcoats** [comment]
confirmed that latest layout.js resolves the issue with I.E. display itself. However the issue with mactrack plugin still exists where I need to append a ? to the end of the url to get the buttons working. Should I open this separate on mactrack or want to attempt to address it in cacti since it only started in 1.2.1?
![screen shot 01-23-19 at 09 08 am](https://user-images.githubusercontent.com/42470924/51611987-8b527f00-1eee-11e9-9fca-ef3c64ea4cbc.PNG)

**Comment by netniV** [comment]
Can you download the latest layout.js from here.  It should be compatible with your 1.2.1 instalaltion.

**Comment by cigamit** [comment]
This issue should be resolved now.
