### ISSUE TITLE
1.2.1 upgrade: аfter the update, there is no choice of interface language

### ISSUE THREAD

**Issue by pautiina** [Cacti/cacti#2338]
![image](https://user-images.githubusercontent.com/11805503/51638802-0c9a2800-1f68-11e9-8af7-271937a7aafb.png)
![image](https://user-images.githubusercontent.com/11805503/51638846-2c315080-1f68-11e9-9ab4-31741822c600.png)

**Comment by pautiina** [comment]
related #2336

**Comment by cigamit** [comment]
@pautiina, Update to the latest layout.js.  This issue should be resolved there.  Provide feedback.

**Comment by pautiina** [comment]
![image](https://user-images.githubusercontent.com/11805503/51793782-92b7a800-21ce-11e9-8e3d-d682ea49adaf.png)
Not resolved
Log fot updated files:
```
[root@noc /var/www/cacti]# git pull
remote: Enumerating objects: 320, done.
remote: Counting objects: 100% (320/320), done.
remote: Compressing objects: 100% (15/15), done.
remote: Total 364 (delta 306), reused 316 (delta 305), pack-reused 44
Receiving objects: 100% (364/364), 89.28 KiB | 510.00 KiB/s, done.
Resolving deltas: 100% (326/326), completed with 251 local objects.
From https://github.com/Cacti/cacti
   cce4b961..190bddf5  develop    -> origin/develop
   fe92e877..308292e2  master     -> origin/master
Updating cce4b961..190bddf5
Fast-forward
 CHANGELOG                                 |  15 ++++++--
 README.md                                 |   2 +-
 about.php                                 |   2 +-
 aggregate_graphs.php                      |   2 +-
 aggregate_items.php                       |   2 +-
 aggregate_templates.php                   |   2 +-
 auth_changepassword.php                   |   2 +-
 auth_login.php                            |   2 +-
 auth_profile.php                          |   2 +-
 automation_devices.php                    |   2 +-
 automation_graph_rules.php                |   2 +-
 automation_networks.php                   |   2 +-
 automation_snmp.php                       |   2 +-
 automation_templates.php                  |   2 +-
 automation_tree_rules.php                 |   2 +-
 boost_rrdupdate.php                       |   2 +-
 cacti.sql                                 |   2 +-
 cdef.php                                  |   2 +-
 cli/add_data_query.php                    |   2 +-
 cli/add_datasource.php                    |   2 +-
 cli/add_device.php                        |   2 +-
 cli/add_graph_template.php                |   2 +-
 cli/add_graphs.php                        |   2 +-
 cli/add_perms.php                         |   2 +-
 cli/add_tree.php                          |   2 +-
 cli/analyze_database.php                  |   2 +-
 cli/audit_database.php                    |   2 +-
 cli/convert_tables.php                    |   2 +-
 cli/copy_user.php                         |   2 +-
 cli/host_update_template.php              |   2 +-
 cli/import_package.php                    |   2 +-
 cli/import_template.php                   |   2 +-
 cli/install_cacti.php                     |   2 +-
 cli/md5sum.php                            |   2 +-
 cli/poller_data_sources_reapply_names.php |   2 +-
 cli/poller_graphs_reapply_names.php       |   2 +-
 cli/poller_output_empty.php               |   2 +-
 cli/poller_reindex_hosts.php              |   2 +-
 cli/poller_replicate.php                  |   6 +++-
 cli/rebuild_poller_cache.php              |   2 +-
 cli/remove_device.php                     |   2 +-
 cli/remove_graphs.php                     |   2 +-
 cli/reorder_data_query.php                |   2 +-
 cli/repair_database.php                   |   2 +-
 cli/repair_graphs.php                     |   2 +-
 cli/repair_templates.php                  |   2 +-
 cli/splice_rra.php                        |   2 +-
 cli/sqltable_to_php.php                   |   2 +-
 cli/structure_rra_paths.php               |   2 +-
 cli/upgrade_database.php                  |   2 +-
 clog.php                                  |   2 +-
 clog_user.php                             |   2 +-
 cmd.php                                   |   2 +-
 cmd_realtime.php                          |   2 +-
 color.php                                 |   2 +-
 color_templates.php                       |   2 +-
 color_templates_items.php                 |   2 +-
 data_input.php                            |   2 +-
 data_queries.php                          |   2 +-
 data_source_profiles.php                  |   2 +-
 data_sources.php                          |   2 +-
 data_templates.php                        |   2 +-
 docs/README.md                            |   2 +-
 docs/index.php                            |   2 +-
 formats/cacti_group.format                |   2 +-
 formats/cacti_group_dark.format           |   2 +-
 formats/cacti_monitor.format              |   2 +-
 formats/lotus_notes.format                |   2 +-
 gprint_presets.php                        |   2 +-
 graph.php                                 |   2 +-
 graph_image.php                           |   2 +-
 graph_json.php                            |   2 +-
 graph_realtime.php                        |   2 +-
 graph_templates.php                       |   2 +-
 graph_templates_inputs.php                |   2 +-
 graph_templates_items.php                 |  32 ++++++++++++-----
 graph_view.php                            |   2 +-
 graph_xport.php                           |   2 +-
 graphs.php                                |   2 +-
 graphs_items.php                          |  20 +++++++++--
 graphs_new.php                            |   2 +-
 host.php                                  |   2 +-
 host_templates.php                        |   2 +-
 include/auth.php                          |   2 +-
 include/bottom_footer.php                 |   2 +-
 include/cacti_version                     |   2 +-
 include/cli_check.php                     |   2 +-
 include/config.php.dist                   |   2 +-
 include/global.php                        |   2 +-
 include/global_arrays.php                 |   3 +-
 include/global_constants.php              |   2 +-
 include/global_form.php                   |   2 +-
 include/global_languages.php              |   2 +-
 include/global_session.php                |   2 +-
 include/global_settings.php               |   2 +-
 include/js/jquery.zoom.js                 |   2 +-
 include/layout.js                         |  29 +++++++--------
 include/plugins.php                       |   2 +-
 include/top_general_header.php            |   2 +-
 include/top_graph_header.php              |   2 +-
 include/top_header.php                    |   2 +-
 include/vendor/phpsnmp/mib_parser.php     |   2 +-
 index.php                                 |   2 +-
 install/background.php                    |   2 +-
 install/cli_check.php                     |   4 +--
 install/cli_test.php                      |   2 +-
 install/functions.php                     |   2 +-
 install/index.php                         |   2 +-
 install/install.php                       |   2 +-
 install/step_json.php                     |   2 +-
 install/upgrades/0_8_1.php                |   2 +-
 install/upgrades/0_8_2.php                |   2 +-
 install/upgrades/0_8_2a.php               |   2 +-
 install/upgrades/0_8_3.php                |   2 +-
 install/upgrades/0_8_4.php                |   2 +-
 install/upgrades/0_8_5.php                |   2 +-
 install/upgrades/0_8_6.php                |   2 +-
 install/upgrades/0_8_6a.php               |   2 +-
 install/upgrades/0_8_6d.php               |   2 +-
 install/upgrades/0_8_6e.php               |   2 +-
 install/upgrades/0_8_6g.php               |   2 +-
 install/upgrades/0_8_6h.php               |   2 +-
 install/upgrades/0_8_6i.php               |   2 +-
 install/upgrades/0_8_7.php                |   2 +-
 install/upgrades/0_8_7a.php               |   2 +-
 install/upgrades/0_8_7b.php               |   2 +-
 install/upgrades/0_8_7c.php               |   2 +-
 install/upgrades/0_8_7h.php               |   2 +-
 install/upgrades/0_8_8.php                |   2 +-
 install/upgrades/1_0_0.php                |   2 +-
 install/upgrades/1_0_4.php                |   2 +-
 install/upgrades/1_0_5.php                |   2 +-
 install/upgrades/1_1_11.php               |   2 +-
 install/upgrades/1_1_14.php               |   2 +-
 install/upgrades/1_1_17.php               |   2 +-
 install/upgrades/1_1_2.php                |   2 +-
 install/upgrades/1_1_20.php               |   2 +-
 install/upgrades/1_1_26.php               |   2 +-
 install/upgrades/1_1_28.php               |   2 +-
 install/upgrades/1_1_31.php               |   2 +-
 install/upgrades/1_1_34.php               |   2 +-
 install/upgrades/1_1_35.php               |   2 +-
 install/upgrades/1_1_36.php               |   2 +-
 install/upgrades/1_1_37.php               |   2 +-
 install/upgrades/1_1_4.php                |   2 +-
 install/upgrades/1_1_6.php                |   2 +-
 install/upgrades/1_1_7.php                |   2 +-
 install/upgrades/1_1_8.php                |   2 +-
 install/upgrades/1_2_0.php                |   2 +-
 install/upgrades/1_2_1.php                |   2 +-
 install/upgrades/1_2_2.php                |  27 ++++++++++++++
 lib/aggregate.php                         |   2 +-
 lib/api_aggregate.php                     |   2 +-
 lib/api_automation.php                    |   2 +-
 lib/api_automation_tools.php              |   2 +-
 lib/api_data_source.php                   |   2 +-
 lib/api_device.php                        |   2 +-
 lib/api_graph.php                         |   2 +-
 lib/api_poller.php                        |   2 +-
 lib/api_tree.php                          |   2 +-
 lib/auth.php                              |   6 ++--
 lib/boost.php                             |   2 +-
 lib/cdef.php                              |   2 +-
 lib/clog_webapi.php                       |   2 +-
 lib/data_query.php                        |   2 +-
 lib/database.php                          |  48 +++++++++++++++++++++----
 lib/dsdebug.php                           |   2 +-
 lib/dsstats.php                           |   2 +-
 lib/export.php                            |   3 +-
 lib/functions.php                         |   5 +--
 lib/graph_variables.php                   |   2 +-
 lib/html.php                              |  26 +++++++-------
 lib/html_filter.php                       |   2 +-
 lib/html_form.php                         |   2 +-
 lib/html_form_template.php                |   2 +-
 lib/html_graph.php                        |   2 +-
 lib/html_reports.php                      |   2 +-
 lib/html_tree.php                         |   2 +-
 lib/html_utility.php                      |  21 +++++------
 lib/html_validate.php                     |   2 +-
 lib/import.php                            |   2 +-
 lib/ldap.php                              |   2 +-
 lib/mib_cache.php                         |   2 +-
 lib/ping.php                              |   2 +-
 lib/plugins.php                           |   6 +++-
 lib/poller.php                            |   2 +-
 lib/reports.php                           |   2 +-
 lib/rrd.php                               |   2 +-
 lib/snmp.php                              |   2 +-
 lib/snmpagent.php                         |   2 +-
 lib/sort.php                              |   2 +-
 lib/spikekill.php                         |   2 +-
 lib/template.php                          |   2 +-
 lib/time.php                              |   2 +-
 lib/timespan_settings.php                 |   2 +-
 lib/utility.php                           |   7 +++-
 lib/variables.php                         |   2 +-
 lib/vdef.php                              |   2 +-
 lib/xml.php                               |   2 +-
 link.php                                  |   2 +-
 links.php                                 |   2 +-
 locales/build_gettext.sh                  |   2 +-
 locales/po/zh-CN.po                       | 230 +++++++++++++++++++++++++++++++++++++++++++++++++++++-----------------------------------------------------------------
 logout.php                                |   2 +-
 managers.php                              |   2 +-
 permission_denied.php                     |   2 +-
 plugins.php                               |   2 +-
 poller.php                                |   2 +-
 poller_automation.php                     |   2 +-
 poller_boost.php                          |   2 +-
 poller_commands.php                       |   2 +-
 poller_dsstats.php                        |   2 +-
 poller_maintenance.php                    |   2 +-
 poller_realtime.php                       |   2 +-
 poller_recovery.php                       |   2 +-
 poller_reports.php                        |   2 +-
 poller_spikekill.php                      |   2 +-
 pollers.php                               |   6 +++-
 remote_agent.php                          |   2 +-
 reports_admin.php                         |   2 +-
 reports_user.php                          |   2 +-
 rrdcleaner.php                            |   2 +-
 script_server.php                         |   2 +-
 settings.php                              |   2 +-
 sites.php                                 |   2 +-
 snmpagent_mibcache.php                    |   2 +-
 snmpagent_mibcachechild.php               |   2 +-
 snmpagent_persist.php                     |   2 +-
 spikekill.php                             |   2 +-
 templates_export.php                      |   2 +-
 templates_import.php                      |   2 +-
 tests/tools/check_cli_version.sh          |   2 +-
 tests/tools/check_install_code.php        |   2 +-
 tree.php                                  |   2 +-
 user_admin.php                            |  20 ++++++-----
 user_domains.php                          |   2 +-
 user_group_admin.php                      |   2 +-
 utilities.php                             |   2 +-
 vdef.php                                  |   2 +-
 239 files changed, 531 insertions(+), 423 deletions(-)
 create mode 100644 install/upgrades/1_2_2.php
[root@noc /var/www/cacti]# php cli/upgrade_database.php
Upgrading from v1.2.1
Upgrading from v1.2.1 (DB 1.2.1) to v1.2.2
+

```

**Comment by cigamit** [comment]
Sorry, we forgot that some people upgrade from git.  If you do a fresh pull of develop, this will be all cleared up.
