### ISSUE TITLE
Drag and Drop of Tree Items in Management -> Trees is Erratic

### ISSUE THREAD

**Issue by reubenfarrelly** [Cacti/cacti#245]
After having created some new hosts and a Management Tree for them, I am attempting to drag and drop them from the Available Devices (center) column into the Tree Items column (left column).

I have this tree set to Manual Ordering as I would like to arrange the devices in order of most to least important - and the only way to do this is to manually order the Tree Items.

However the Drag and Drop function of these is very erratic.  It is fairly easy to drag and drop Available Devices across to the Tree Items column, but it is a constant game of click and hope to rearrange the order of them within the Tree Items list.  For example I have just attempted to drag a host to the middle of the list, and it has gone there, but some other hosts have now moved around and changed their own order and been placed at some random place lower down the list.

This seems to be the case with both Firefox and Chrome on Windows.  This is experienced with Cacti-1.0.0.

**Comment by cigamit** [comment]
This one is going to be a little tricky.  I've tried to fix it once already using css.  Now I have to review the jstree code to find a better solution.

**Comment by cigamit** [comment]
I've updated jstree to the latest stable.  It had a change to help with the calculation of the drop zone.  Please verify that it makes things a little easier to handle.  Remember F5 or CTRL+R (Chrome) to reload the updated JavaScript.

**Comment by reubenfarrelly** [comment]
It seems a little better but something is still not quite right.  There is something odd with regards to the ordering not being preserved when a new item is dragged up within the list.  I can't quite put my finger on it though.......

**Comment by cigamit** [comment]
Check the order on your tree or branch.  If it's 'alpha' or 'natural' it does not matter where they are dropped, the tree or branch is always reordered in that manner.

**Comment by reubenfarrelly** [comment]
No - I've been set to Manual Ordering the whole time (since I want to order by importance to me and not alphabetically).

Here's a picture of what just happened.  In this case I dragged just the one item - the device vmware-1.reub.net up to beneath the Palo Alto firewall (red line).  It moved to the right spot.  But look at all the items in the yellow box underneath - they've all rearranged themselves in a weird unexpected way without me even touching, clicking or dragging them at all.  That's the issue :-)

<img width="719" alt="cactitreeordering" src="https://cloud.githubusercontent.com/assets/8552189/22537515/522454a4-e95f-11e6-9d78-993c565a410f.png">

**Comment by cigamit** [comment]
Okay, there is a sequence issue.  If you can send the output of the following:

select * from graph_tree_items where tree_id=X order by parent, sequence;

That would be great.  Also, did you attempt to drag multiple items simultaneously.  I noted an issue there lately.

**Comment by reubenfarrelly** [comment]
Only attempted to drag one item above.

Here's the MariaDB output:

```
MariaDB [cacti]> describe graph_tree_items;
+--------------------+-----------------------+------+-----+---------+----------------+
| Field              | Type                  | Null | Key | Default | Extra          |
+--------------------+-----------------------+------+-----+---------+----------------+
| id                 | bigint(20) unsigned   | NO   | PRI | NULL    | auto_increment |
| parent             | bigint(20) unsigned   | YES  | MUL | NULL    |                |
| position           | int(10) unsigned      | YES  |     | NULL    |                |
| graph_tree_id      | smallint(5) unsigned  | NO   | MUL | 0       |                |
| local_graph_id     | mediumint(8) unsigned | NO   | MUL | 0       |                |
| title              | varchar(255)          | YES  |     | NULL    |                |
| host_id            | mediumint(8) unsigned | NO   | MUL | 0       |                |
| host_grouping_type | tinyint(3) unsigned   | NO   |     | 1       |                |
| sort_children_type | tinyint(3) unsigned   | NO   |     | 1       |                |
+--------------------+-----------------------+------+-----+---------+----------------+
9 rows in set (0.00 sec)

MariaDB [cacti]> select * from graph_tree_items where graph_tree_id=2 order by parent, position;
+----+--------+----------+---------------+----------------+-------+---------+--------------------+--------------------+
| id | parent | position | graph_tree_id | local_graph_id | title | host_id | host_grouping_type | sort_children_type |
+----+--------+----------+---------------+----------------+-------+---------+--------------------+--------------------+
| 10 |      0 |        1 |             2 |              0 |       |       7 |                  1 |                  1 |
|  8 |      0 |        2 |             2 |              0 |       |       8 |                  1 |                  1 |
|  7 |      0 |        3 |             2 |              0 |       |       6 |                  1 |                  1 |
| 18 |      0 |        4 |             2 |              0 |       |       2 |                  1 |                  1 |
| 19 |      0 |        5 |             2 |              0 |       |       3 |                  1 |                  1 |
|  9 |      0 |        6 |             2 |              0 |       |       5 |                  1 |                  1 |
| 11 |      0 |        7 |             2 |              0 |       |      19 |                  1 |                  1 |
|  2 |      0 |        8 |             2 |              0 |       |       1 |                  1 |                  1 |
|  4 |      0 |        9 |             2 |              0 |       |      13 |                  1 |                  1 |
|  5 |      0 |       10 |             2 |              0 |       |      14 |                  1 |                  1 |
|  6 |      0 |       11 |             2 |              0 |       |      21 |                  1 |                  1 |
| 12 |      0 |       12 |             2 |              0 |       |      18 |                  1 |                  1 |
| 13 |      0 |       13 |             2 |              0 |       |      17 |                  1 |                  1 |
| 20 |      0 |       14 |             2 |              0 |       |      15 |                  1 |                  1 |
| 21 |      0 |       15 |             2 |              0 |       |      16 |                  1 |                  1 |
| 22 |      0 |       16 |             2 |              0 |       |      20 |                  1 |                  1 |
| 23 |      0 |       17 |             2 |              0 |       |       4 |                  1 |                  1 |
+----+--------+----------+---------------+----------------+-------+---------+--------------------+--------------------+
17 rows in set (0.00 sec)

MariaDB [cacti]> 
```

**Comment by cigamit** [comment]
Okay, that looks correct.  This must have something to do with either the sorting routine, or some other internal bug.

**Comment by cigamit** [comment]
Should be resolved now.  Can you confirm once 1.1.11 is released?

**Comment by reubenfarrelly** [comment]
OK tested again with current -git - and it's much "better" but still not quite right.  I can still see some odd behaviour going on when I drag and drop within the list above - devices sometimes are dragged to one location in the tree but appear in a different place in the list, but the frequency of this is inconsistent (it doesn't happen every time).  It's nowhere near as erratic as it was when I opened the bug though.

**Comment by cigamit** [comment]
Yea, the drop location has to be improved in jsTree.  I've had the same issue at times.  My efforts to resolve in CSS have not worked well.  Since it's much better, I'm going to close for the moment.  We can revisit it once the next release of jsTree is released.
