### ISSUE TITLE
Data Source reapply names does not update name from data query or template.

### ISSUE THREAD

**Issue by jdcoats** [Cacti/cacti#2499]
I have changed graph template suggested name and data query suggested name and reapply suggested name works. However when I change data source name in the template and data query, sync template to device and reapply names does not work. Is this already a known issue? Am I doing something wrong? I don't want to have to recreate or change each individually :)

**Comment by jdcoats** [comment]
This typically isn't a big deal unless you are trying to update a bunch of weather maps and to select the interface link they all say Hostname - Traffic (dumb default ds name) :)
![connectivity](https://user-images.githubusercontent.com/42470924/54077649-4d849c80-4289-11e9-9ca9-e4bf1461a60d.png)

**Comment by jdcoats** [comment]
I can reapply DS name changes to other snmp interface related data queries for example Interface status updated fine with the exact same variables |host_description|-|query_ifName|-|query_ifAlias|. so It appears that just the interface traffic doesn't work?

**Comment by jdcoats** [comment]
I checked the other default native cacti snmp interface DS's and cant reapply names but the Interface Status that I added does work.

**Comment by cigamit** [comment]
It this just for Data Sources or for both Data Sources and Graphs?

**Comment by jdcoats** [comment]
Just data sources. Graphs update fine

**Comment by cigamit** [comment]
Resolved.

**Comment by jdcoats** [comment]
Awesome! I updated 500 DS individually today. I’ll test with the rest in the morning :)

**Comment by jdcoats** [comment]
just jumped in and applied latest changes and the result is still the same. Ill test more tomorrow but the initial result is the same

**Comment by jdcoats** [comment]
```

2019/03/11 22:25:48 - CMDPHP PHP ERROR WARNING Backtrace: (/cli/poller_data_sources_reapply_names.php[137]:CactiErrorHandler())
--
2019/03/11 22:25:48 - ERROR PHP WARNING: Invalid argument supplied for foreach() in file: /var/www/localhost/htdocs/cacti/cli/poller_data_sources_reapply_names.php on line: 137
2019/03/11 22:25:48 - CMDPHP SQL Backtrace: (/cli/poller_data_sources_reapply_names.php[130]:db_fetch_assoc(), /lib/database.php[450]:db_fetch_assoc_prepared(), /lib/database.php[464]:db_execute_prepared())
2019/03/11 22:25:48 - CMDPHP ERROR: A DB Row Failed!, Error: Unknown column 'debug' in 'where clause'


```

**Comment by jdcoats** [comment]
hmm cant find a commit the references these changes

**Comment by netniV** [comment]
download the latest version of that file and it should be corrected.  However, if you use the debug option, it should also give you the SQL being used that produced no results.

**Comment by jdcoats** [comment]
It still does not change the name to the current name in the data query like the graphs do. It just uses Description - Traffic which is not any of the suggested names in the template or the data query. 
```
 # php poller_data_sources_reapply_names.php --host-id=775 --debug
WARNING: Do not interrupt this script.  Interrupting during rename can cause issues
DEBUG: There are '530' Data Sources to rename
......
......
DEBUG: Data Source Name 'BIXLER-CORE-7009-01-N7K2 - Traffic' starting
DEBUG: Data Source Rename Done for Data Source 'BIXLER-CORE-7009-01-N7K2 - Traffic'
DEBUG: Data Source Name 'BIXLER-CORE-7009-01-N7K2 - Traffic' starting
DEBUG: Data Source Rename Done for Data Source 'BIXLER-CORE-7009-01-N7K2 - Traffic'
DEBUG: Data Source Name 'BIXLER-CORE-7009-01-N7K2 - Traffic' starting
DEBUG: Data Source Rename Done for Data Source 'BIXLER-CORE-7009-01-N7K2 - Traffic'
DEBUG: Data Source Name 'BIXLER-CORE-7009-01-N7K2 - Traffic' starting
DEBUG: Data Source Rename Done for Data Source 'BIXLER-CORE-7009-01-N7K2 - Traffic'
DEBUG: Data Source Name 'BIXLER-CORE-7009-01-N7K2 - Traffic' starting
DEBUG: Data Source Rename Done for Data Source 'BIXLER-CORE-7009-01-N7K2 - Traffic'
DEBUG: Data Source Name 'BIXLER-CORE-7009-01-N7K2 - Traffic' starting
DEBUG: Data Source Rename Done for Data Source 'BIXLER-CORE-7009-01-N7K2 - Traffic'
DEBUG: Data Source Name 'BIXLER-CORE-7009-01-N7K2 - Traffic' starting
DEBUG: Data Source Rename Done for Data Source 'BIXLER-CORE-7009-01-N7K2 - Traffic'
.....
.....
```

**Comment by jdcoats** [comment]
I can confirm that It does work for the interface status data query. I just added Status- to |host_description|-|query_ifName|-|query_ifAlias| It just does not work for the interface traffic data queries.
```
DEBUG: Data Source Name 'Status-BIXLER-CORE-7009-01-N7K2-Ethernet3/1-IDF H-BN-65' starting
DEBUG: Data Source Rename Done for Data Source 'Status-BIXLER-CORE-7009-01-N7K2-Ethernet3/1-IDF H-BN-65'
DEBUG: Data Source Name 'Status-BIXLER-CORE-7009-01-N7K2-Ethernet3/2-IDF H-GA-38' starting
DEBUG: Data Source Rename Done for Data Source 'Status-BIXLER-CORE-7009-01-N7K2-Ethernet3/2-IDF H-GA-38'
DEBUG: Data Source Name 'Status-BIXLER-CORE-7009-01-N7K2-Ethernet3/3-IDF H-GN-50' starting
DEBUG: Data Source Rename Done for Data Source 'Status-BIXLER-CORE-7009-01-N7K2-Ethernet3/3-IDF H-GN-50'
```

**Comment by cigamit** [comment]
I have confirmed that this is resolved now.

**Comment by jdcoats** [comment]
Sorry for not responding, yes it works great now. Thanks!
