### ISSUE TITLE
Poller Output Table not Empty WARNING messages in cacti.log

### ISSUE THREAD

**Issue by reubenfarrelly** [Cacti/cacti#257]
Something appears to have broken in the past hour or two with my Cacti 1.0.0 and it's not obvious what the cause is.  What I am seeing is this in the logs:

2017-02-02 14:55:02 - POLLER: Poller[1] WARNING: Poller Output Table not Empty.  Issues Found: 300, Data Sources: traffic_in(DS[30]), traffic_out(DS[30]), traffic_in(DS[69]), traffic_out(DS[69]), traffic_in(DS[70]), traffic_out(DS[70]), traffic_in(DS[71]), traffic_out(DS[71]), traffic_in(DS[72]), traffic_out(DS[72]), traffic_in(DS[73]), traffic_out(DS[73]), traffic_in(DS[74]), traffic_out(DS[74]), traffic_in(DS[75]), traffic_out(DS[75]), traffic_in(DS[76]), traffic_out(DS[76]), traffic_in(DS[77]), traffic_out(DS[77]), Additional Issues Remain.  Only showing first 20
2017-02-02 14:55:04 - POLLER: Poller[1] Device[2] DS[269] WARNING: Result from SNMP not valid.  Partial Result: U
2017-02-02 14:55:04 - POLLER: Poller[1] Device[2] DS[269] WARNING: Result from SNMP not valid.  Partial Result: U
2017-02-02 14:55:32 - SYSTEM STATS: Time:30.3660 Method:cmd.php Processes:2 Threads:N/A Hosts:22 HostsPerProcess:11 DataSources:425 RRDsProcessed:105
2017-02-02 14:55:35 - SYSTEM DSSTATS STATS: Type:HOURLY, Time:0.0230 
2017-02-02 15:00:03 - POLLER: Poller[1] WARNING: Poller Output Table not Empty.  Issues Found: 280, Data Sources: traffic_in(DS[30]), traffic_out(DS[30]), traffic_in(DS[69]), traffic_out(DS[69]), traffic_in(DS[70]), traffic_out(DS[70]), traffic_in(DS[71]), traffic_out(DS[71]), traffic_in(DS[72]), traffic_out(DS[72]), traffic_in(DS[73]), traffic_out(DS[73]), traffic_in(DS[74]), traffic_out(DS[74]), traffic_in(DS[75]), traffic_out(DS[75]), traffic_in(DS[76]), traffic_out(DS[76]), traffic_in(DS[77]), traffic_out(DS[77]), Additional Issues Remain.  Only showing first 20
2017-02-02 15:00:04 - POLLER: Poller[1] Device[2] DS[269] WARNING: Result from SNMP not valid.  Partial Result: U
2017-02-02 15:00:04 - POLLER: Poller[1] Device[2] DS[269] WARNING: Result from SNMP not valid.  Partial Result: U
2017-02-02 15:00:12 - CMDPHP Device[3] ERROR: HOST EVENT: Device is DOWN Message: SNMP not performed due to setting or ping result., UDP ping error: timeout
2017-02-02 15:00:33 - SYSTEM STATS: Time:30.3418 Method:cmd.php Processes:2 Threads:N/A Hosts:22 HostsPerProcess:11 DataSources:425 RRDsProcessed:105
2017-02-02 15:00:35 - SYSTEM DSSTATS STATS: Type:HOURLY, Time:0.0120 
2017-02-02 15:05:02 - POLLER: Poller[1] WARNING: Poller Output Table not Empty.  Issues Found: 280, Data Sources: traffic_in(DS[30]), traffic_out(DS[30]), traffic_in(DS[69]), traffic_out(DS[69]), traffic_in(DS[70]), traffic_out(DS[70]), traffic_in(DS[71]), traffic_out(DS[71]), traffic_in(DS[72]), traffic_out(DS[72]), traffic_in(DS[73]), traffic_out(DS[73]), traffic_in(DS[74]), traffic_out(DS[74]), traffic_in(DS[75]), traffic_out(DS[75]), traffic_in(DS[76]), traffic_out(DS[76]), traffic_in(DS[77]), traffic_out(DS[77]), Additional Issues Remain.  Only showing first 20
2017-02-02 15:05:04 - POLLER: Poller[1] Device[2] DS[269] WARNING: Result from SNMP not valid.  Partial Result: U
2017-02-02 15:05:04 - POLLER: Poller[1] Device[2] DS[269] WARNING: Result from SNMP not valid.  Partial Result: U
2017-02-02 15:05:28 - SYSTEM STATS: Time:25.3211 Method:cmd.php Processes:2 Threads:N/A Hosts:22 HostsPerProcess:11 DataSources:425 RRDsProcessed:106
2017-02-02 15:05:30 - SYSTEM DSSTATS STATS: Type:HOURLY, Time:0.0153 
2017-02-02 15:10:02 - POLLER: Poller[1] WARNING: Poller Output Table not Empty.  Issues Found: 300, Data Sources: traffic_in(DS[30]), traffic_out(DS[30]), traffic_in(DS[69]), traffic_out(DS[69]), traffic_in(DS[70]), traffic_out(DS[70]), traffic_in(DS[71]), traffic_out(DS[71]), traffic_in(DS[72]), traffic_out(DS[72]), traffic_in(DS[73]), traffic_out(DS[73]), traffic_in(DS[74]), traffic_out(DS[74]), traffic_in(DS[75]), traffic_out(DS[75]), traffic_in(DS[76]), traffic_out(DS[76]), traffic_in(DS[77]), traffic_out(DS[77]), Additional Issues Remain.  Only showing first 20
2017-02-02 15:10:04 - POLLER: Poller[1] Device[2] DS[269] WARNING: Result from SNMP not valid.  Partial Result: U
2017-02-02 15:10:04 - POLLER: Poller[1] Device[2] DS[269] WARNING: Result from SNMP not valid.  Partial Result: U
2017-02-02 15:10:26 - SYSTEM STATS: Time:24.3681 Method:cmd.php Processes:2 Threads:N/A Hosts:22 HostsPerProcess:11 DataSources:425 RRDsProcessed:106
2017-02-02 15:10:29 - SYSTEM DSSTATS STATS: Type:HOURLY, Time:0.0074 
2017-02-02 15:15:02 - POLLER: Poller[1] WARNING: Poller Output Table not Empty.  Issues Found: 300, Data Sources: traffic_in(DS[30]), traffic_out(DS[30]), traffic_in(DS[69]), traffic_out(DS[69]), traffic_in(DS[70]), traffic_out(DS[70]), traffic_in(DS[71]), traffic_out(DS[71]), traffic_in(DS[72]), traffic_out(DS[72]), traffic_in(DS[73]), traffic_out(DS[73]), traffic_in(DS[74]), traffic_out(DS[74]), traffic_in(DS[75]), traffic_out(DS[75]), traffic_in(DS[76]), traffic_out(DS[76]), traffic_in(DS[77]), traffic_out(DS[77]), Additional Issues Remain.  Only showing first 20
2017-02-02 15:15:04 - POLLER: Poller[1] Device[2] DS[269] WARNING: Result from SNMP not valid.  Partial Result: U
2017-02-02 15:15:04 - POLLER: Poller[1] Device[2] DS[269] WARNING: Result from SNMP not valid.  Partial Result: U
2017-02-02 15:15:09 - CMDPHP Device[3] NOTICE: HOST EVENT: Device Returned FROM DOWN State: 
2017-02-02 15:15:30 - SYSTEM STATS: Time:28.3288 Method:cmd.php Processes:2 Threads:N/A Hosts:22 HostsPerProcess:11 DataSources:425 RRDsProcessed:106
2017-02-02 15:15:33 - SYSTEM DSSTATS STATS: Type:HOURLY, Time:0.0067 
2017-02-02 15:20:03 - POLLER: Poller[1] WARNING: Poller Output Table not Empty.  Issues Found: 300, Data Sources: traffic_in(DS[30]), traffic_out(DS[30]), traffic_in(DS[69]), traffic_out(DS[69]), traffic_in(DS[70]), traffic_out(DS[70]), traffic_in(DS[71]), traffic_out(DS[71]), traffic_in(DS[72]), traffic_out(DS[72]), traffic_in(DS[73]), traffic_out(DS[73]), traffic_in(DS[74]), traffic_out(DS[74]), traffic_in(DS[75]), traffic_out(DS[75]), traffic_in(DS[76]), traffic_out(DS[76]), traffic_in(DS[77]), traffic_out(DS[77]), Additional Issues Remain.  Only showing first 20
2017-02-02 15:20:05 - POLLER: Poller[1] Device[2] DS[269] WARNING: Result from SNMP not valid.  Partial Result: U
2017-02-02 15:20:05 - POLLER: Poller[1] Device[2] DS[269] WARNING: Result from SNMP not valid.  Partial Result: U
2017-02-02 15:20:34 - SYSTEM STATS: Time:31.3370 Method:cmd.php Processes:2 Threads:N/A Hosts:22 HostsPerProcess:11 DataSources:425 RRDsProcessed:105
2017-02-02 15:20:37 - SYSTEM DSSTATS STATS: Type:HOURLY, Time:0.0089 
2017-02-02 15:25:02 - POLLER: Poller[1] WARNING: Poller Output Table not Empty.  Issues Found: 280, Data Sources: traffic_in(DS[30]), traffic_out(DS[30]), traffic_in(DS[69]), traffic_out(DS[69]), traffic_in(DS[70]), traffic_out(DS[70]), traffic_in(DS[71]), traffic_out(DS[71]), traffic_in(DS[72]), traffic_out(DS[72]), traffic_in(DS[73]), traffic_out(DS[73]), traffic_in(DS[74]), traffic_out(DS[74]), traffic_in(DS[75]), traffic_out(DS[75]), traffic_in(DS[76]), traffic_out(DS[76]), traffic_in(DS[77]), traffic_out(DS[77]), Additional Issues Remain.  Only showing first 20
2017-02-02 15:25:04 - POLLER: Poller[1] Device[2] DS[269] WARNING: Result from SNMP not valid.  Partial Result: U
2017-02-02 15:25:04 - POLLER: Poller[1] Device[2] DS[269] WARNING: Result from SNMP not valid.  Partial Result: U
2017-02-02 15:25:12 - CMDPHP Device[3] ERROR: HOST EVENT: Device is DOWN Message: SNMP not performed due to setting or ping result., UDP ping error: timeout
2017-02-02 15:25:33 - SYSTEM STATS: Time:30.3485 Method:cmd.php Processes:2 Threads:N/A Hosts:22 HostsPerProcess:11 DataSources:425 RRDsProcessed:105
2017-02-02 15:25:36 - SYSTEM DSSTATS STATS: Type:HOURLY, Time:0.0067 
2017-02-02 15:30:02 - POLLER: Poller[1] WARNING: Poller Output Table not Empty.  Issues Found: 280, Data Sources: traffic_in(DS[30]), traffic_out(DS[30]), traffic_in(DS[69]), traffic_out(DS[69]), traffic_in(DS[70]), traffic_out(DS[70]), traffic_in(DS[71]), traffic_out(DS[71]), traffic_in(DS[72]), traffic_out(DS[72]), traffic_in(DS[73]), traffic_out(DS[73]), traffic_in(DS[74]), traffic_out(DS[74]), traffic_in(DS[75]), traffic_out(DS[75]), traffic_in(DS[76]), traffic_out(DS[76]), traffic_in(DS[77]), traffic_out(DS[77]), Additional Issues Remain.  Only showing first 20
2017-02-02 15:30:04 - POLLER: Poller[1] Device[2] DS[269] WARNING: Result from SNMP not valid.  Partial Result: U
2017-02-02 15:30:04 - POLLER: Poller[1] Device[2] DS[269] WARNING: Result from SNMP not valid.  Partial Result: U
2017-02-02 15:30:27 - SYSTEM STATS: Time:25.3225 Method:cmd.php Processes:2 Threads:N/A Hosts:22 HostsPerProcess:11 DataSources:425 RRDsProcessed:106
2017-02-02 15:30:30 - SYSTEM DSSTATS STATS: Type:HOURLY, Time:0.0128

router-2.reub.net was never offline - but that might not be the cause.  The device which is now returning an invalid result from SNMP was working OK earlier - this could be unrelated as well.

The poller_output table in mysql is indeed populating with data:

MariaDB [cacti]> select * from poller_output;
+---------------+-------------+---------------------+---------------+
| local_data_id | rrd_name    | time                | output        |
+---------------+-------------+---------------------+---------------+
|            30 | traffic_in  | 2017-02-02 15:25:14 | 40401439      |
|            30 | traffic_out | 2017-02-02 15:25:14 | 20911774      |
|            69 | traffic_in  | 2017-02-02 15:25:12 | 14700351604   |
...
|           268 | traffic_in  | 2017-02-02 15:25:12 | 2301460242    |
|           268 | traffic_out | 2017-02-02 15:25:12 | 224343390     |
|           269 | traffic_in  | 2017-02-02 15:25:04 | U             |
|           269 | traffic_out | 2017-02-02 15:25:04 | U             |
+---------------+-------------+---------------------+---------------+
280 rows in set (0.01 sec)

MariaDB [cacti]>  

I guess the question is, what caused the system to get into this state given it was working fine for the previous 24 hours, and why is the poller_output table not being emptied on every run?

It would be helpful if Cacti could log a little more detail as to why this is occurring and ideally if possible, self-heal so that whatever has caused this problem does not bring down the entire installation.

I am also not seeing any updates to quite a few RRD files.

What debugging would I need to enable (which file?) to help determine what has gone wrong?

**Comment by pautiina** [comment]
I have this error too, and I clear mysql table poller_output and poller_output_boost. After thiis I have error in log:
`2017-02-02 10:48:50 - CMDPHP SQL Backtrace: (/graph_json.php: 148 rrdtool_function_graph)(/lib/rrd.php: 1122 boost_graph_cache_check)(/lib/boost.php: 321 boost_process_poller_output)(/lib/boost.php: 601 db_fetch_cell)(/lib/database.php: 199 db_fetch_cell_prepared)(/lib/database.php: 243 cacti_debug_backtrace)`

**Comment by reubenfarrelly** [comment]
Here's the debug output leading up to the error being logged:

2017-02-02 20:35:03 - DBCALL DEVEL: SQL Cell: "SELECT cacti FROM version LIMIT 1"
2017-02-02 20:35:03 - DBCALL DEVEL: SQL Cell: "SHOW TABLES LIKE 'sessions'"
2017-02-02 20:35:03 - DBCALL DEVEL: SQL Cell: "SHOW TABLES LIKE 'settings_user'"
2017-02-02 20:35:03 - DBCALL DEVEL: SQL Row: "SELECT value    FROM settings_user    WHERE name = ?    AND user_id = ?"
2017-02-02 20:35:03 - DBCALL DEVEL: SQL Cell: "SHOW TABLES LIKE 'user_domains'"
2017-02-02 20:35:03 - DBCALL DEVEL: SQL Assoc: "SELECT * FROM user_domains WHERE enabled="on" ORDER BY domain_name"
2017-02-02 20:35:03 - DBCALL DEVEL: SQL Cell: "SELECT domain_id FROM user_domains WHERE defdomain=1 AND enabled="on""
2017-02-02 20:35:03 - DBCALL DEVEL: SQL Assoc: "SELECT pc.id, ph.name, ph.file, ph.function  FROM plugin_hooks AS ph  LEFT JOIN plugin_config AS pc  ON pc.directory = ph.name  WHERE ph.status = 1 AND hook = ?  ORDER BY id ASC"
2017-02-02 20:35:03 - DBCALL DEVEL: SQL Assoc: "SELECT * FROM plugin_realms ORDER BY plugin, display"
2017-02-02 20:35:03 - DBCALL DEVEL: SQL Assoc: "SELECT DISTINCT gt.id, gt.name  FROM graph_templates AS gt  INNER JOIN graph_templates_item AS gti  ON gt.id=gti.graph_template_id  INNER JOIN data_template_rrd AS dtr  ON gti.task_item_id=dtr.id  WHERE gti.local_graph_id=0 AND data_source_type_id IN (3,2) ORDER BY name"
2017-02-02 20:35:03 - DBCALL DEVEL: SQL Assoc: "SELECT directory AS id, name  FROM plugin_config  WHERE status=1"
2017-02-02 20:35:03 - DBCALL DEVEL: SQL Assoc: "SELECT pc.id, ph.name, ph.file, ph.function  FROM plugin_hooks AS ph  LEFT JOIN plugin_config AS pc  ON pc.directory = ph.name  WHERE ph.status = 1 AND hook = ?  ORDER BY id ASC"
2017-02-02 20:35:03 - DBCALL DEVEL: SQL Assoc: "SELECT pc.id, ph.name, ph.file, ph.function  FROM plugin_hooks AS ph  LEFT JOIN plugin_config AS pc  ON pc.directory = ph.name  WHERE ph.status = 1 AND hook = ?  ORDER BY id ASC"
2017-02-02 20:35:03 - DBCALL DEVEL: SQL Assoc: "SELECT pc.id, ph.name, ph.file, ph.function  FROM plugin_hooks AS ph  LEFT JOIN plugin_config AS pc  ON pc.directory = ph.name  WHERE ph.status = 1 AND hook = ?  ORDER BY id ASC"
2017-02-02 20:35:03 - DBCALL DEVEL: SQL Assoc: "SELECT pc.id, ph.name, ph.file, ph.function  FROM plugin_hooks AS ph  LEFT JOIN plugin_config AS pc  ON pc.directory = ph.name  WHERE ph.status = 1 AND hook = ?  ORDER BY id ASC"
2017-02-02 20:35:03 - DBCALL DEVEL: SQL Cell: "SELECT hostname FROM poller where id = ?"
2017-02-02 20:35:03 - DBCALL DEVEL: SQL Cell: "SELECT disabled FROM poller WHERE id = ?"
2017-02-02 20:35:03 - DBCALL DEVEL: SQL Assoc: "SELECT pc.id, ph.name, ph.file, ph.function  FROM plugin_hooks AS ph  LEFT JOIN plugin_config AS pc  ON pc.directory = ph.name  WHERE ph.status = 1 AND hook = ?  ORDER BY id ASC"
2017-02-02 20:35:03 - DBCALL DEVEL: SQL Cell: "SELECT COUNT(*) FROM poller WHERE disabled="""
2017-02-02 20:35:03 - DBCALL DEVEL: SQL Cell: "SELECT SQL_NO_CACHE COUNT(*) FROM poller_item WHERE rrd_next_step<=0 AND poller_id = 1"
2017-02-02 20:35:03 - DBCALL DEVEL: SQL Assoc: "SELECT SQL_NO_CACHE host_id, COUNT(*) AS data_sources  FROM poller_item  WHERE rrd_next_step<=0 AND poller_id = 1  GROUP BY host_id  ORDER BY host_id"
2017-02-02 20:35:03 - DBCALL DEVEL: SQL Exec: "REPLACE INTO settings  (name, value)  VALUES (?, ?)"
2017-02-02 20:35:03 - DBCALL DEVEL: SQL Assoc: "SELECT SQL_NO_CACHE id     FROM host     WHERE poller_id = ?    AND disabled=""     ORDER BY id"
2017-02-02 20:35:03 - DBCALL DEVEL: SQL Assoc: "SELECT action, count(*) AS totals FROM poller_item WHERE poller_id = ? GROUP BY action"
2017-02-02 20:35:03 - DBCALL DEVEL: SQL Exec: "INSERT INTO poller (id, snmp, script, server, last_status, status)  VALUES (?, ?, ?, ?, NOW(), 1)  ON DUPLICATE KEY UPDATE snmp=VALUES(snmp), script=VALUES(script),   server=VALUES(server), last_status=VALUES(last_status), status=VALUES(status)"
2017-02-02 20:35:03 - DBCALL DEVEL: SQL Exec: "REPLACE INTO settings (name, value) VALUES ('path_webroot','/var/www/cacti.reub.net/htdocs')"
2017-02-02 20:35:03 - DBCALL DEVEL: SQL Cell: "SELECT SQL_NO_CACHE COUNT(*)   FROM poller_time   WHERE poller_id = ?  AND end_time="0000-00-00 00:00:00""
2017-02-02 20:35:03 - DBCALL DEVEL: SQL Exec: "DELETE FROM poller_time WHERE poller_id = ?"
2017-02-02 20:35:03 - DBCALL DEVEL: SQL Assoc: "SELECT SQL_NO_CACHE local_data_id, rrd_name    FROM poller_output AS po   LEFT JOIN data_local AS dl   ON po.local_data_id=dl.id   LEFT JOIN host AS h   ON dl.host_id=h.id   WHERE h.poller_id = ? OR h.id IS NULL LIMIT 20"
2017-02-02 20:35:03 - DBCALL DEVEL: SQL Cell: "SELECT SQL_NO_CACHE COUNT(*)    FROM poller_output AS po   LEFT JOIN data_local AS dl   ON po.local_data_id=dl.id   LEFT JOIN host AS h   ON dl.host_id=h.id   WHERE h.poller_id = ? OR h.id IS NULL"
2017-02-02 20:35:03 - POLLER: Poller[1] WARNING: Poller Output Table not Empty.  Issues Found: 298, Data Sources: traffic_in(DS[30]), traffic_out(DS[30]), traffic_in(DS[69]), traffic_out(DS[69]), traffic_in(DS[70]), traffic_out(DS[70]), traffic_in(DS[71]), traffic_out(DS[71]), traffic_in(DS[72]), traffic_out(DS[72]), traffic_in(DS[73]), traffic_out(DS[73]), traffic_in(DS[74]), traffic_out(DS[74]), traffic_in(DS[75]), traffic_out(DS[75]), traffic_in(DS[76]), traffic_out(DS[76]), traffic_in(DS[77]), traffic_out(DS[77]), Additional Issues Remain.  Only showing first 20
2017-02-02 20:35:03 - DBCALL DEVEL: SQL Exec: "DELETE po    FROM poller_output AS po    LEFT JOIN data_local AS dl   ON po.local_data_id=dl.id   LEFT JOIN host AS h   ON dl.host_id=h.id   WHERE h.poller_id = ? OR h.id IS NULL"
2017-02-02 20:35:03 - DBCALL DEVEL: SQL Assoc: "SELECT pc.id, ph.name, ph.file, ph.function  FROM plugin_hooks AS ph  LEFT JOIN plugin_config AS pc  ON pc.directory = ph.name  WHERE ph.status = 1 AND hook = ?  ORDER BY id ASC"
2017-02-02 20:35:03 - DBCALL DEVEL: SQL Exec: "REPLACE INTO settings (name, value) VALUES ('date', NOW())"
2017-02-02 20:35:03 - DBCALL DEVEL: SQL Cell: "SELECT SQL_NO_CACHE count(*)     FROM poller_time     WHERE poller_id = ?     AND end_time >'0000-00-00 00:00:00'"
2017-02-02 20:35:03 - DBCALL DEVEL: SQL Assoc: "SELECT po.output, po.time,  UNIX_TIMESTAMP(po.time) as unix_time, po.local_data_id, dl.data_template_id,  pi.rrd_path, pi.rrd_name, pi.rrd_num  FROM poller_output AS po  INNER JOIN poller_item AS pi  ON po.local_data_id=pi.local_data_id  AND po.rrd_name=pi.rrd_name  INNER JOIN data_local AS dl  ON dl.id=po.local_data_id  ORDER BY po.local_data_id  LIMIT 40000"
2017-02-02 20:35:03 - DBCALL DEVEL: SQL Assoc: "SELECT SQL_NO_CACHE    CONCAT(data_template_id, "_", data_name) AS keyname, data_source_names AS data_source_name    FROM poller_data_template_field_mappings"
2017-02-02 20:35:04 - DBCALL DEVEL: SQL Cell: "SELECT SQL_NO_CACHE count(*)     FROM poller_time     WHERE poller_id = ?     AND end_time >'0000-00-00 00:00:00'"
2017-02-02 20:35:04 - DBCALL DEVEL: SQL Assoc: "SELECT po.output, po.time,  UNIX_TIMESTAMP(po.time) as unix_time, po.local_data_id, dl.data_template_id,  pi.rrd_path, pi.rrd_name, pi.rrd_num  FROM poller_output AS po  INNER JOIN poller_item AS pi  ON po.local_data_id=pi.local_data_id  AND po.rrd_name=pi.rrd_name  INNER JOIN data_local AS dl  ON dl.id=po.local_data_id  ORDER BY po.local_data_id  LIMIT 40000"
2017-02-02 20:35:04 - DBCALL DEVEL: SQL Cell: "SELECT cacti FROM version LIMIT 1"
2017-02-02 20:35:04 - DBCALL DEVEL: SQL Cell: "SHOW TABLES LIKE 'sessions'"
2017-02-02 20:35:04 - DBCALL DEVEL: SQL Cell: "SHOW TABLES LIKE 'settings_user'"
2017-02-02 20:35:04 - DBCALL DEVEL: SQL Row: "SELECT value    FROM settings_user    WHERE name = ?    AND user_id = ?"
2017-02-02 20:35:04 - DBCALL DEVEL: SQL Cell: "SHOW TABLES LIKE 'user_domains'"

**Comment by cigamit** [comment]
There was a fix this morning.  Please test again.

**Comment by pautiina** [comment]
I test again, but problem not solved.
```
2017-02-02 14:30:00 - POLLER: Poller[1] WARNING: Poller Output Table not Empty.  Issues Found: 2407, Data Sources: traffic_in(DS[790]), traffic_out(DS[790]), traffic_in(DS[791]), traffic_out(DS[791]), traffic_in(DS[792]), traffic_out(DS[792]), traffic_in(DS[793]), traffic_out(DS[793]), ping(DS[1194]), ping(DS[1201]), ping(DS[1213]), ping(DS[3186]), hrSystemUptime(DS[3217]), hdd_total(DS[3218]), hdd_used(DS[3218]), hdd_total(DS[3219]), hdd_used(DS[3219]), hdd_total(DS[3220]), hdd_used(DS[3220]), hdd_total(DS[3221]), Additional Issues Remain.  Only showing first 20
2017-02-02 14:31:00 - POLLER: Poller[1] WARNING: Poller Output Table not Empty.  Issues Found: 2233, Data Sources: traffic_in(DS[790]), traffic_out(DS[790]), traffic_in(DS[791]), traffic_out(DS[791]), traffic_in(DS[792]), traffic_out(DS[792]), traffic_in(DS[793]), traffic_out(DS[793]), traffic_in(DS[999]), traffic_out(DS[999]), traffic_in(DS[1000]), traffic_out(DS[1000]), traffic_in(DS[1001]), traffic_out(DS[1001]), traffic_in(DS[1002]), traffic_out(DS[1002]), traffic_in(DS[1003]), traffic_out(DS[1003]), traffic_in(DS[1004]), traffic_out(DS[1004]), Additional Issues Remain.  Only showing first 20

```

**Comment by reubenfarrelly** [comment]
Not fixed for me either:

2017-02-02 23:40:03 - POLLER: Poller[1] WARNING: Poller Output Table not Empty.  Issues Found: 298, Data Sources: traffic_in(DS[30]), traffic_out(DS[30]), traffic_in(DS[69]), traffic_out(DS[69]), traffic_in(DS[70]), traffic_out(DS[70]), traffic_in(DS[71]), traffic_out(DS[71]), traffic_in(DS[72]), traffic_out(DS[72]), traffic_in(DS[73]), traffic_out(DS[73]), traffic_in(DS[74]), traffic_out(DS[74]), traffic_in(DS[75]), traffic_out(DS[75]), traffic_in(DS[76]), traffic_out(DS[76]), traffic_in(DS[77]), traffic_out(DS[77]), Additional Issues Remain.  Only showing first 20
2017-02-02 23:40:04 - POLLER: Poller[1] Device[2] DS[273] WARNING: Result from SNMP not valid.  Partial Result: U
2017-02-02 23:40:04 - POLLER: Poller[1] Device[2] DS[273] WARNING: Result from SNMP not valid.  Partial Result: U
2017-02-02 23:40:28 - SYSTEM STATS: Time:25.3335 Method:cmd.php Processes:2 Threads:N/A Hosts:22 HostsPerProcess:11 DataSources:425 RRDsProcessed:107

**Comment by pautiina** [comment]
After some times this message has been away, but into rrd file no valid data, onlu 'U'. 
![load](https://cloud.githubusercontent.com/assets/11805503/22555143/600082c6-e96b-11e6-8e27-a370078c36ee.png)

**Comment by cigamit** [comment]
This issue is resolved.  Apologize for that.  This is a development branch after all.  Thanks for everyone's patience.

**Comment by reubenfarrelly** [comment]
Still not working for me even with the latest git (26007e4304c4c08e007c9f725424b6449ea0cc08)  :

2017-02-03 14:00:03 - POLLER: Poller[1] WARNING: Poller Output Table not Empty.  Issues Found: 298, Data Sources: traffic_in(DS[30]), traffic_out(DS[30]), traffic_in(DS[69]), traffic_out(DS[69]), traffic_in(DS[70]), traffic_out(DS[70]), traffic_in(DS[71]), traffic_out(DS[71]), traffic_in(DS[72]), traffic_out(DS[72]), traffic_in(DS[73]), traffic_out(DS[73]), traffic_in(DS[74]), traffic_out(DS[74]), traffic_in(DS[75]), traffic_out(DS[75]), traffic_in(DS[76]), traffic_out(DS[76]), traffic_in(DS[77]), traffic_out(DS[77]), Additional Issues Remain.  Only showing first 20

Should I clear the output table manually?

**Comment by pautiina** [comment]
@cigamit Thanks. Now working and not have error in Cacti log.

**Comment by reubenfarrelly** [comment]
Hmmm.    Reading this:

http://www.cacti.net/downloads/docs/html/cli_poller_output_empty.html

Then following the suggestion in there gives me this output:

apache@thunderstorm ~/cacti.reub.net/htdocs/cli $ php -q poller_output_empty.phpPHP Fatal error:  Uncaught Error: Call to undefined function boost_poller_on_demand() in /var/www/cacti.reub.net/htdocs/lib/poller.php:494
Stack trace:
#0 /var/www/cacti.reub.net/htdocs/cli/poller_output_empty.php(82): process_poller_output(Resource id #35, false)
#1 {main}
  thrown in /var/www/cacti.reub.net/htdocs/lib/poller.php on line 494
apache@thunderstorm ~/cacti.reub.net/htdocs/cli $ 

Does that help show what is happening?

**Comment by cigamit** [comment]
Reuben, thanks for that note, the poller_output_empty.php script was missing the include of lib/boost.php.  That issue is resolved.  If you are still getting this error, I suggest that you take a fresh dump of your production environment, import it into the development insance and re-upgrade it.  Your issues may have been caused by your special case around the 'Add' button on Graphs and Data Sources and the bugs you found there.  Now that those bugs have been resolved, you should see if you can reproduce this poller output issue.  If so, please carefully document the steps you followed, and run the poller.php in debug mode from the command line to see if there is any notable error.
