### ISSUE TITLE
In PHP strict standards mode, rrdtool_function_graph() generates ByRef message for HRULE items

### ISSUE THREAD

**Issue by eschoeller** [Cacti/cacti#2724]
I've seen this in some graphs, not in others. But across a random sampling the error(s) were present in 50% of them. 

Upon viewing the RRDtool command for a given graph several of these messages will appear:

```Strict Standards:  Only variables should be passed by reference in /cacti/cacti-1.2.4-prod/lib/rrd.php on line 2127```

![image](https://user-images.githubusercontent.com/12864741/59155015-5b8aba80-8a3c-11e9-8678-56f04823b5e2.png)

The graph is still displayed correctly with no other issues. Seems like this is just a warning.

**Comment by eschoeller** [comment]
Looks like this issue occurs on graphs with HRULEs. So, it's probably related to my other issue that was already resolved. #2662 Sorry!

**Comment by netniV** [comment]
Actually, you will still have this.  The call to strip_alpha() expects the parameter to be variable whose value can be returned.  However, the call at the line you have referenced is:

```php
$substitute = strip_alpha(rrd_substitute_host_query_data($graph_variables['value'][$graph_item_id], $graph, $graph_item));
```

This is trying to pass the return value of `rrd_substitute_host_query_data()` to the `strip_alpha()` which is invalid as it's not a variable that can be updated.

**Comment by colbaip** [comment]
en lib/function.php ,  en la funcion  strip_alpha agrege  agregue (int) para asegurar  que velva un numero

function strip_alpha(&$string) {
	/* strip all non numeric data */
	$string = trim(preg_replace('/[^0-9,.+-]/', '', $string));

	/* check the easy cases first */
	/* it has no delimiters, and no space, therefore, must be numeric */
	if (is_numeric($string) || is_float($string)) {
--		return $string;
++		return (int)$string;
	} else {
		return false;
	}

**Comment by netniV** [comment]
That would not work as you are assuming integer values when they could be float/decimal.
