### ISSUE TITLE
Unable to add items into a report

### ISSUE THREAD

**Issue by camerabob** [Cacti/cacti#2760]
**Describe the bug**

 Receive the logged error:
"2019/06/24 14:00:07 - CMDPHP PHP ERROR Backtrace:  (CactiShutdownHandler())
--
2019/06/24 14:00:07 - ERROR PHP ERROR: Call to undefined function  get_timespan() in file: /usr/share/cacti/lib/html_reports.php on line:  797"

**To Reproduce**
1. Go to '...' Reporting, create a report, enter the report and attempt to create an item in that new report.
4. See error shown above

**Expected behavior**
A new line item is created.

**Screenshots**
![image](https://user-images.githubusercontent.com/25908052/60041369-35465b00-9689-11e9-9e73-899515c05c10.png)

![image](https://user-images.githubusercontent.com/25908052/60041387-41cab380-9689-11e9-8f16-db31818be7dd.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 7 Enterprise
 - Browser [e.g. chrome, safari] Firefox

**Smartphone (please complete the following information):**
 - Browser [e.g. stock browser, safari] Firefox
 - Version [e.g. 22] 67.0.4

**Additional context**

Cacti 1.2.4, CentOS 7

**Comment by camerabob** [comment]
Brand new install, first time setting up.

**Comment by cigamit** [comment]
Resolved, thanks!

**Comment by camerabob** [comment]
Perfect. Thank you!

**Comment by camerabob** [comment]
Excuse any misspellings. I'm still getting used to this iGadget!
