### ISSUE TITLE
SNMP - Bits/Sec + Total Bandwith - Cacti Version 1.0.3

### ISSUE THREAD

**Issue by SoNix21** [Cacti/cacti#298]
Anyone can confirm this problem...
 My Graph stopped working since Cacti 1.0.3... (Every others graph works ).
And check at the bottom : RRDtools says : (Nothing)..

And there is no error in my Cacti Log.

![bits_totalbandwith](https://cloud.githubusercontent.com/assets/25518106/22896352/c023273c-f1ed-11e6-9360-43a70beeba5a.jpg)

**Comment by cigamit** [comment]
Can you please copy the string on the left hand side and past it into a shell window and then see what the error is?  I'm thinking that rrdtool is crashing on you.  Also, please report your rrdtool version from 'rrdtool --version'.

**Comment by SoNix21** [comment]
OKay... I tried to do, the complete Command : 

`C:/rrdtool/rrdtool.exe graph - --imgformat=PNG --start="-86400" --end="-300" --pango-markup  --title="LXXXX - XX - XX-5500 [IRF] - Traffic - ***VERS XXSW-XX-4800-1 GIG 1/0/28***" --vertical-label="bytes per second" --slope-mode --base=1000 --height=120 --width=500 --tabwidth "30" --rigid --alt-autoscale-max --lower-limit="0" --color BACK#F3F3F3 --color CANVAS#FDFDFD --color SHADEA#CBCBCB --color SHADEB#999999 --color FONT#000000 --color AXIS#2C4D43 --color ARROW#2C4D43 --color FRAME#2C4D43 --border 1 --font TITLE:11:"Ariel" --font AXIS:8:"Ariel" --font LEGEND:8:"Courier" --font UNIT:8:"Ariel" --font WATERMARK:6:"Ariel" --slope-mode --watermark "Copyright (C) 2004-2017 The Cacti Group" DEF:a="C\:/Cacti/Apache24/htdocs/Cacti/rra/178/649.rrd":"traffic_in":AVERAGE DEF:b="C\:/Cacti/Apache24/htdocs/Cacti/rra/178/649.rrd":"traffic_out":AVERAGE AREA:a#00CF00FF:"Inbound "  GPRINT:a:LAST:"Current\:%8.2lf%s"  GPRINT:a:AVERAGE:"Average\:%8.2lf%s"  GPRINT:a:MAX:"Maximum\:%8.2lf%s\n"  COMMENT:\"Total In\:  -300 B\n\"  LINE1:b#002A97FF:"Outbound"  GPRINT:b:LAST:"Current\:%8.2lf%s"  GPRINT:b:AVERAGE:"Average\:%8.2lf%s"  GPRINT:b:MAX:"Maximum\:%8.2lf%s\n"  COMMENT:\"Total Out\: -300 B\n\"`

I get an "**ERROR: unknown option '3'**"

Here is my RRDTool Version :

`C:\rrdtool>rrdtool.exe -version
RRDtool 1.4.5  Copyright 1997-2009 by Tobias Oetiker <tobi@oetiker.ch>
               Compiled Dec 15 2011 15:06:41

Usage: rrdtool [options] command command_options
Valid commands: create, update, updatev, graph, graphv,  dump, restore,
                last, lastupdate, first, info, fetch, tune,
                resize, xport, flushcached

RRDtool is distributed under the Terms of the GNU General
Public License Version 2. (www.gnu.org/copyleft/gpl.html)

For more information read the RRD manpages`

**Comment by cigamit** [comment]
Change the comments from the following:

COMMENT:\"Total Out\: -300 B\n\"

to the following:

COMMENT:"Total Out\: -300 B\n"

And comment.  I think this will fix it.  If you can confirm that, I can make the fix.

**Comment by SoNix21** [comment]
I think the forum removed a `\` or something.. because you write the same thing.. ;)

**Comment by cigamit** [comment]
If you update the the latest lib/rrd.php, I think that this problem should be solved.  We introduced a new escaping function.  In my environment, when you look at the debug output, there will be single characters used instead of double for the bandwidth comments as well.

**Comment by SoNix21** [comment]
I did the update, but the problem is still there.. :( 

I still get no "OK" from rrdtool : 
`C:/rrdtool/rrdtool.exe graph - \
--imgformat=PNG \
--start="-86400" \
--end="-300" \
--pango-markup  \
--title="LXXXXX - XX - XX-5500 [IRF] - Traffic - ***VERS XXSW-XXX-4800-1 GIG 1/0/28***" \
--vertical-label="bytes per second" \
--slope-mode \
--base=1000 \
--height=120 \
--width=500 \
--tabwidth "30" \
--rigid \
--alt-autoscale-max \
--lower-limit="0" \
--color BACK#F3F3F3 \
--color CANVAS#FDFDFD \
--color SHADEA#CBCBCB \
--color SHADEB#999999 \
--color FONT#000000 \
--color AXIS#2C4D43 \
--color ARROW#2C4D43 \
--color FRAME#2C4D43 \
--border 1 --font TITLE:11:"Ariel" \
--font AXIS:8:"Ariel" \
--font LEGEND:8:"Courier" \
--font UNIT:8:"Ariel" \
--font WATERMARK:6:"Ariel" \
--slope-mode \
--watermark "Copyright (C) 2004-2017 The Cacti Group" \
DEF:a="C\:/Cacti/Apache24/htdocs/Cacti/rra/178/649.rrd":"traffic_in":AVERAGE \
DEF:b="C\:/Cacti/Apache24/htdocs/Cacti/rra/178/649.rrd":"traffic_out":AVERAGE \
AREA:a#00CF00FF:"Inbound "  \
GPRINT:a:LAST:"Current\:%8.2lf%s"  \
GPRINT:a:AVERAGE:"Average\:%8.2lf%s"  \
GPRINT:a:MAX:"Maximum\:%8.2lf%s\n"  \
COMMENT:\"Total In\:  0 B\n\"  \
LINE1:b#002A97FF:"Outbound"  \
GPRINT:b:LAST:"Current\:%8.2lf%s"  \
GPRINT:b:AVERAGE:"Average\:%8.2lf%s"  \
GPRINT:b:MAX:"Maximum\:%8.2lf%s\n"  \
COMMENT:\"Total Out\: 0 B\n\" `

**Comment by cigamit** [comment]
Please test with the latest commit.  Thanks.

**Comment by SoNix21** [comment]
Yep! Problem Fixed!!! I close the ticket.
