### ISSUE TITLE
Graph Zooming to edge of timespan

### ISSUE THREAD

**Issue by eschoeller** [Cacti/cacti#3028]
I'm not sure if this one is fix-able, but it's been on my radar for quite some time. 
When using the highlight graph zooming feature, it's very difficult to get the zoom region to land directly on the edges (start and end) of the graph. If your cursor exceeds the graph image ever so slightly the zoom range is lost. 
It would be fantastic if the zoom range would be maintained to the very end (or beginning) of the timespan instead. 
![Peek 2019-10-13 11-57](https://user-images.githubusercontent.com/12864741/66719758-1511e780-edb1-11e9-9d41-43c2a488d526.gif)

**Comment by cigamit** [comment]
Looks limited to Chrome and Edge.  Can not reproduce on Firefox.

**Comment by cigamit** [comment]
Resolved now.

**Comment by eschoeller** [comment]
I updated jquery.zoom.js. I can see that firefox has the desired functionality, good to see this is possible because it's SO much easier to use. My version of chrome still doesn't handle this properly though, and has the same issue as before. 
```
Chromium	77.0.3865.90 (Official Build) Built on Ubuntu , running on Ubuntu 18.04 (64-bit)
Revision	58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS	Linux
JavaScript	V8 7.7.299.11
Flash	(Disabled)
User Agent	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/77.0.3865.90 Chrome/77.0.3865.90 Safari/537.36
Command Line	/usr/lib/chromium-browser/chromium-browser --enable-pinch --flag-switches-begin --flag-switches-end
```
I will say that _this_ version of chrome works correctly:
```
Chromium	77.0.3865.90 (Official Build) Built on Ubuntu , running on Ubuntu 18.04 (64-bit)
Revision	58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS	Linux
JavaScript	V8 7.7.299.11
Flash	(Disabled)
User Agent	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/77.0.3865.90 Chrome/77.0.3865.90 Safari/537.36
Command Line	/usr/lib/chromium-browser/chromium-browser --enable-pinch --flag-switches-begin --flag-switches-end
```

**Comment by cigamit** [comment]
You have to force the reload of the file.  You can't just do an F5 in Chrome.  The way I do it is that I point my browser to http://myhost/cacti/include/js/jquery.zoom.js and press enter, and once it shows the javascript, then press F5, after that, you can back button back and the updated JS file will be loaded.  It's a pain in the arse, I know.

**Comment by netniV** [comment]
If you have the developer tools open, it will normally force a refresh and with Chrome's tools, I think you can even force it to clear cache on every call.

**Comment by eschoeller** [comment]
I'm still seeing a lot of irregularity with zooming and adhering to the set timespan definition. I haven't been able to reproduce the errors precisely and "sum it all up". I'm starting to suspect there's a browser session issue of some sort. I've also been switching between modern and dark themes to see if the theme has anything to do with it. Eventually I hope to open another issue about it all.

**Comment by cigamit** [comment]
Update jquery.zoom.js and I think this will be solved.

**Comment by eschoeller** [comment]
zooming to the end of a graph still causes some problems. I'm on a Mac so I'll have to figure out how to capture an active screen grab of the behavior.

**Comment by cigamit** [comment]
Weird.  I can not re-produce on any normal Windows based browser now.

**Comment by netniV** [comment]
> I'm on a Mac so I'll have to figure out how to capture an active screen grab of the behavior.

Cmd+shift+5
