### ISSUE TITLE
ALTER TABLE host_snmp_cache MODIFY COLUMN snmp_index VARCHAR(255) NOT NULL default ""	[Fail]

### ISSUE THREAD

**Issue by clonek24** [Cacti/cacti#3189]
Hello
my upgrade process from 1.2.6 to 1.2.8 has failed due to 
`

ALTER TABLE host_snmp_cache MODIFY COLUMN snmp_index VARCHAR(255) NOT NULL default "" | [Fail]
-- | --

`
`
logs
`2020/01/15 07:25:36 - INSTALL: always: Installation was started at 2020-01-15 06:25:02, completed at 2020-01-15 06:25:36
2020/01/15 07:25:36 - INSTALL: info: Progress: 100
2020/01/15 07:25:36 - INSTALL: always: WARNING: One or more upgrades failed to install correctly
2020/01/15 07:25:36 - INSTALL: info: Progress: 85
2020/01/15 07:25:36 - INSTALL: info: Progress: 80
2020/01/15 07:25:36 - INSTALL: always: Finished UPGRADE Process for v1.2.8
2020/01/15 07:25:34 - INSTALL: always: Upgrading from v1.2.7 (DB 1.2.7) to v1.2.8
2020/01/15 07:25:34 - INSTALL: always: Upgrading from v1.2.6 (DB 1.2.8 (DB: 1.2.6)) to v1.2.7
2020/01/15 07:25:34 - INSTALL: always: NOTE: Using temporary file for db cache: /tmp/cduVyz0PG
2020/01/15 07:25:34 - INSTALL: always: Switched from to /tmp/cduVyz0PG
2020/01/15 07:25:34 - INSTALL: info: Progress: 60`
`
How to fix the issue?

**Comment by TheWitness** [comment]
Just run the command

```console
ALTER TABLE host_snmp_cache ROW_FORMAT=Dynamic;
```

This fix will be in 1.2.9 for others.

**Comment by clonek24** [comment]
not working
`mysql> ALTER TABLE host_snmp_cache ROW_FORMAT=Dynamic;
Query OK, 0 rows affected, 2 warnings (1.65 sec)
Records: 0  Duplicates: 0  Warnings: 2
`

**Comment by netniV** [comment]
How do you mean not working? That said it worked as the query returned OK

**Comment by cigamit** [comment]
You just have to re-run your upgrade now and you will be all set.

**Comment by cigamit** [comment]
This is fixed permanently in 1.2.29.

**Comment by clonek24** [comment]
AS you can see in log - 2 warnings; no affected rows. 
I restarted upgrade process and still the same issue

**Comment by clonek24** [comment]
as you can see on the log: 0 rows affected, 2 warnings. Restart of upgrade does not help

**Comment by netniV** [comment]
Can you describe the table in question using the MySQL describe command, just so we can verify that the changes applied.  Also, since you had warnings, check your SQL logs for what they were.

**Comment by TheWitness** [comment]
I have this happen the other day, when @clonek24 does a show warnings, it'll show that the highest innodb_file_format supported is Antelope.  @clonek24 first has to set:

```sql
innodb_file_format=Barracuda
```

Restart MariaDB/MySQL and then perform the alter a second time.

**Comment by cigamit** [comment]
Good catch.  This is all resolved in 1.2.9 though.  So, I'm going to close.
