### ISSUE TITLE
Cacti installer is broken on fresh install of 1.2.10

### ISSUE THREAD

**Issue by nuno-silva** [Cacti/cacti#3330]
The cacti installer is broken on fresh install of 1.2.10.

The GUI shows an "action failed" message with a few warnings:
```
Action failed
Sorry, we could not process your last action.
Error:	200 OK
Reason:	
Notice: Undefined index: name in /var/www/cacti-testing/htdocs/cacti/lib/installer.php on line 1079

Notice: Undefined index: name in /var/www/cacti-testing/htdocs/cacti/lib/installer.php on line 1080

Notice: Undefined index: name in /var/www/cacti-testing/htdocs/cacti/lib/installer.php on line 1081

Notice: Undefined index: name in /var/www/cacti-testing/htdocs/cacti/lib/installer.php on line 1088
{"Mode":1,"Step":1,"Errors":[],"Eula":null,"Prev":{"Text":"Previous","Step":0,"Enabled":false,"Visible":true},"Next":{"Text":"Begin","Step":2,"Enabled":false,"Visible":true},"Test":{"Text":"Test Connection","Step":-4,"Enabled":true,"Visible":false},"Theme":"modern","StepData":{"Eula":null,"Theme":"modern","Language":"en-US"},"Html":"
```

Also see attached screenshot.

**To Reproduce**
1. Install a fresh copy of cacti 1.2.10
2. Populate the cacti database (using `cacti.sql`)
3. Edit `include/config.php` with your DB settings
4. Point your browser to the installation site.
5. See error

**Expected behaviour**
Installer should proceed normally and without warnings.

**Screenshots**
![image](https://user-images.githubusercontent.com/6935057/76150711-4911e000-60a5-11ea-958d-ca0c6ebc716f.png)

**Desktop**
 - OS: Gentoo Linux
 - Browser: Chromium 80.0.3987.122 (Developer Build) (64-bit)

**Additional context**
 - PHP 7.2.27

This is somewhat similar to #3323, except this is a fresh install, not an upgrade.

Removing `'Cacti_Stats.xml.gz'` from `install/functions.php`does allow the installation to continue.

**Comment by cigamit** [comment]
This is now fixed again in the 1.2.x branch including the updated Cacti Stats package.  I'll be part of the 1.2.11 release.

**Comment by mckaygerhard** [comment]
this stupid error still persist! how developers can release a broken version? where's the real fix commit due after applied  501009a68d08e21c3b630cc70808aad8682f95bc there's no files or fixeds .. neither commit 8e687065b7f456f969cccad97e2c55e5609638cd not fix anything!

**Comment by netniV** [comment]
I could quite easily ask:

> How can people not search properly to find a simple fix?

I would suggest before berating people, you try asking nicely for help.  For now, this was fixed and verified.

**Comment by TheWitness** [comment]
He's just a miserable person.  Likely lives with his mother too.
