### ISSUE TITLE
Keeping received  CMDPHP WARNING on cacti.log

### ISSUE THREAD

**Issue by DY-1990** [Cacti/cacti#3442]
_#_ Describe the bug

Keeping received "_Date Time_ - CMDPHP WARNING: SNMP Error:'snmp2_get(): No response from _IP_', Device:'_Host Name_', OID:'.1.3.6.1.2.1.25.2.3.1.6.2'" on cacti.log when poller running. almost very added device have this issue, then Disk Graphs show used as "nan".

## To Reproduce

When system runing poller(cmd.php)

## Expected behavior

no error message, no nan in disk used graphs. 

## Screenshots

![cacti](https://user-images.githubusercontent.com/63394625/78875682-da97b780-7a80-11ea-990e-0614e0026008.PNG)

## Desktop (please complete the following information)

- OS: windows 10

- Browser: chrome

- Version: cacti 1.2.5

**Comment by TheWitness** [comment]
That's mainly due to the device timing out trying to reach and oid, or having some other issue.  What version of PHP?

**Comment by DY-1990** [comment]
> That's mainly due to the device timing out trying to reach and oid, or having some other issue. What version of PHP?

thanks for help. PHP info shows below.
Name        : php
Arch        : x86_64
Version     : 5.4.16
Release     : 45.el7
Size        : 4.4 M

**Comment by TheWitness** [comment]
Okay, cool.

**Comment by TheWitness** [comment]
This was fixed here: https://github.com/Cacti/cacti/commit/a1eed00307e53522447f0780ced3252e054d1b0f

Download the 1.2.x branch of lib/snmp.php and test.  If this issue is gone, please close.

**Comment by DY-1990** [comment]
Hello， this issue still exist。 I already replaced snmp.php with attachmed file.

[snmp.php.txt](https://github.com/Cacti/cacti/files/4485129/snmp.php.txt)

**Comment by DY-1990** [comment]
I followed the introduction https://forums.cacti.net/about15136.html, and tried this

snmpget -v 2c -c _community name_ _IP_ .1.3.6.1.2.1.25.2.3.1.6.2
HOST-RESOURCES-MIB::hrStorageUsed.2 = INTEGER: 20674608

**Comment by DY-1990** [comment]
issue solved by increase SNMP Defaults Timeout in settings device default, but I need re-create device to take it effect. It's normal , or is there any better ways to modify this value?
