### ISSUE TITLE
Publish signatures/hashes for published files

### ISSUE THREAD

**Issue by CapitalF** [Cacti/cacti#349]
Please consider publishing a set of signatures/hashes for the published releases on the main cacti site. A sha256 would be great. Just a line with the sig/sum for validation would be great. Nothing fancy needed.

**Comment by ronytomen** [comment]
I was just thinking about doing this on the last release.  So your timing is well, good!

My current plan is to implement a full hash file within the distributed releases for per file verification.  I also plan on doing a `.checksum` for the release distribution files.

**Comment by CapitalF** [comment]
Thanks. Also because your site is not using TLS yet (even self-signed would be great due to cert pinning) this is rather important to me.

**Comment by ronytomen** [comment]
Encrypted communications and signatures are important.

**Comment by Nebelwolf** [comment]
In the meantime you could change the links on the cacti website to something like this:

https://github.com/Cacti/cacti/archive/release/1.1.9.zip
https://github.com/Cacti/cacti/archive/release/1.1.9.tar.gz

Thats better then having to download an untrusted file (http, no hashes) which I can't verify easily.
Thank you for your work on the cacti project, sir!

**Comment by ronytomen** [comment]
I can not, as those links are not true release files.

I'm working on moving the main sites to new infrastructure and all services will be moved to encrypted communications.

**Comment by paulgevers** [comment]
+1 from me/Debian for pgp/gpg signed releases

**Comment by ronytomen** [comment]
Can someone give me examples of how the hash file should be formatted?

As far as pgp/gpg signing goes, yes, we need that, but first I want to get new web servers in place with https and hashes published.

**Comment by paulgevers** [comment]
I have no clue about hash files. The pgp/gpg signature is just a detached file along the file it signs with e.g. .asc extension.

**Comment by Nebelwolf** [comment]
Almost every hash file I have seen looked like this:

```
hash1 filename1
hash2 filename2
hash2 filename2
```

https://en.wikipedia.org/wiki/Md5sum
https://en.wikipedia.org/wiki/Sha1sum

**Comment by cigamit** [comment]
Tony can you make this a priority for the 1.1.17 release to incorporate this into the release packaging and automation?

**Comment by cigamit** [comment]
This is resolved now Rony, we have a cli script md5sum.php in the CLI directory.  If you can add that to your publishing script, we can close this for 1.1.35.

**Comment by Nebelwolf** [comment]
MD5 is compromised for a long time now and the attacker could alter the file so that it still shows the correct md5 sum when hashed.
MD5 is broken, please don't use it for security related stuff.

The links posted by me some time ago was mainly for the "hashfile" examples. 

https://en.wikipedia.org/wiki/Md5sum
> The underlying MD5 algorithm is no longer deemed secure. Thus, while md5sum is well-suited for identifying known files in situations **that are not security related**, it should not be relied on if there is a chance that files have been purposefully and maliciously tampered. In the latter case, the use of a newer hashing tool such as sha256sum is recommended.
