### ISSUE TITLE
Newly Created Graph Templates Not Available

### ISSUE THREAD

**Issue by christh0mas** [Cacti/cacti#363]
I exported some data queries, data templates, graph templates and host templates from my old Cacti server running 0.8.7 and attempted to import them into my new Cacti 1.0.3 but I received the old hash error on some of them.  No big deal, I thought.  I figured that I would just recreate them manually on my 1.0.3 server.  As an example, one that I recreated was the old "Network - Ping" template.  I manually created the data input method, data source, CDEFs and graph template.  The problem occurs when I then try to add that new graph template to a device.  I open the device and hit the "Add Graph Template" drop-down but my new graph is not on the list.  

Not sure if this is a bug or if I'm missing a step somewhere.  
Thanks.

**Comment by CapitalF** [comment]
I have been creating new graph templates and graphs from scratch on 1.0.3 and it works okay. Double check your work and see if you missed something. Go back and make sure the Graph Template exists and that it's valid.

Also I've been exporting templates from 0.8.8h and they will import okay into 1.0.3, so if you wanted to upgrade first you could export/import.

Good luck.

**Comment by cigamit** [comment]
This issue was resolved in Cacti 1.0.4.  Try upgrading to 1.0.4, and the issue should resolve itself.

**Comment by christh0mas** [comment]
I updated to 1.0.4 using the download at cacti.net but I still can't see this new graph.  Do I need to recreate the template from scratch again?
