### ISSUE TITLE
Location filter still does not work properly in 1.2.13

### ISSUE THREAD

**Issue by gdsotirov** [Cacti/cacti#3706]
# Describe the bug

In Cacti 1.2.13 no devices are found with default filters and when location is 'All'. See also #3424.

## To Reproduce

1. Go to Console -> Management -> Devices.

2. With all filters to defaults the system displays "No Devices Found", which is confusing.

3. Select a location - the devices in this location are shown.

4. Select back "All" as location - again "No Devices Found".

## Expected behavior

With default filters (i.e. Location = "All") all matching devices (i.e. regardless of the location or in all locations) should be shown.

## Screenshots

No devices found with default filters:

![изображение](https://user-images.githubusercontent.com/955033/87939983-8a79b980-caa1-11ea-808b-05ffda3f0fb4.png)

With location 'None' devices are properly found:

![изображение](https://user-images.githubusercontent.com/955033/87940407-34f1dc80-caa2-11ea-94c1-940d32d1d1a8.png)

Selecting back "All" shows no devices at all:

![изображение](https://user-images.githubusercontent.com/955033/87940689-ab8eda00-caa2-11ea-9321-a2d83687b467.png)

_Note_: The information printed below the filters was added by me in source `host.php`.

## Desktop (please complete the following information)

- OS: Windows 10 (2004)

- Browser: Firefox 78

## Additional context

Please, note that by default the value of "Location" filter is empty string (i.e. not set). However, as option "All" has value "-1" after it's explicitly selected the filter tries to find devices with such location, but on my instances there are no such devices. Perhaps both empty string and "-1" values should be considered "All" and there shouldn't be SQL clause filtering by `host.location` field in this case.

**Comment by bmfmancini** [comment]
Just curious did you try and grab host.php from the 1.2x branch ?

I know there was a fix pushed out recently and it worked for me

**Comment by gdsotirov** [comment]
Yes, @bmfmancini, I thought it's clear I'm reporting it for 1.2.13 to which I upgraded few hours ago. There was a fix from @netniV for #3424, but I still think "All" option is still not handled properly, so I opened this one. In my installation I currently do not have NULL values for `host.location`, which was the issue before.

**Comment by gdsotirov** [comment]
Hmm... perhaps commit 8c73e8c8ed1f81f3ef7e89e4ef631b088543de80 is the fix?

**Comment by gdsotirov** [comment]
Yep, commit 8c73e8c by @TheWitness solves it for me. I tested also with NULL values, so with this fix Location filter works properly in all cases.

**Comment by bmfmancini** [comment]
@gdsotirov good to know its working for you I think @TheWitness  fixed that bug after the 1.2.13 release so I dont think that fix is in the release zip

**Comment by gdsotirov** [comment]
Yes, @bmfmancini, the fix was committed two days after the release, so hopefully it would be available in the next one from the 1.2 series.

![изображение](https://user-images.githubusercontent.com/955033/88025086-6f0fbc80-cb3c-11ea-87f0-59957431b3da.png)

**Comment by netniV** [comment]
Analysis appears correct.  If it's resolved, you can go ahead and close this issue.
