### ISSUE TITLE
Page refresh in graph.php does not work

### ISSUE THREAD

**Issue by surpadisfa** [Cacti/cacti#3859]
Page graph.php automatic refresh does not work, once the page is loaded is not updated anymore.

I'm using Cacti 1.2.14 on a CentOS 7 (rpm package cacti-1.2.14-1.el7.noarch frpm EPEL repo).
The database is from an older Cacti 0.8.8h upgraded do 1.2.14.
There isn't any plugin loaded.

I had a look at graph.php and i saw the following code

```
$refresh['seconds'] = read_config_option('page_refresh');
$refresh['page']    = 'graph.php?local_graph_id=' . get_request_var('local_graph_id') . '&header=false';
$refresh['logout']  = 'false';
set_page_refresh($refresh);
```

As far as I can see there isn't a 'page_refresh' entry in table 'settings' and I can confirm that $refresh['seconds'] is empty when it is passed to set_page_refresh().

I tried the following change but it didn't get any better, the only difference is that $refresh['seconds'] gets a value but still the page doesn't refresh.

```
$refresh['seconds'] = read_user_setting('page_refresh');
$refresh['page']    = 'graph.php?local_graph_id=' . get_request_var('local_graph_id') . '&header=false';
$refresh['logout']  = 'false';
set_page_refresh($refresh);

```
The issue doesn't seem related to the broswer: I tried with Chrome 85, Firefox 72, Edge 44 and IE 11.

**Comment by TheWitness** [comment]
I started digging into this, and I'm still scratching my head.  For certain drill-downs, it's supposed to be disabled, but for others it should not be.  So, I'm rightfully perplexed at the moment.

**Comment by surpadisfa** [comment]
I can add that if I open the graph.php in a new tab, with the change to the code I described before, it refreshes correctly.

Example:
URL: https://cacti/cacti/graph_view.php?action=tree&node=tbranch-4578&host_id=1567&site_id=-1&host_template_id=-1&hgd=&hyper=true
refresh doesn't work

URL: 
https://cacti/cacti/graph.php?local_graph_id=44175
refresh works properly

**Comment by iskandarbasman** [comment]
Might be related to #3892 this Cacti was upgraded from v1.1.38 to v1.2.14.

**Comment by TheWitness** [comment]
I'll be re-verifying with the latest code to see if the refresh works.

**Comment by TheWitness** [comment]
This is fixed now.  Thanks for your patience.

**Comment by iskandarbasman** [comment]
Hi Witness just want to state that #3859 is not resolved from my testing with the latest developer cacti.
