### ISSUE TITLE
rra not written or WARNING: Poller Output Table not Empty.

### ISSUE THREAD

**Issue by zez3** [Cacti/cacti#389]
I got this "WARNING: Poller Output Table not Empty" after the migration 0.8.8_h-1 -> 1.0.0-1
Currently running 1.0.4-1 but the issue is not yet fixed.

Same issue described here:
http://forums.cacti.net/viewtopic.php?f=21&t=36706
I tried to repopullate, change the polling time and cron with no success.

One strange thing that I saw is that after the migration I have a second Data source Profile

**Comment by zez3** [comment]
![image](https://cloud.githubusercontent.com/assets/22619253/23701547/83c752a6-03f7-11e7-8ef8-f0dfb7edc438.png)

**Comment by cigamit** [comment]
You need to dump you Cacti database and email it.  However, before you do that, please run:

select * from poller_output;

between poller runs and post here.

**Comment by zez3** [comment]
I guess you haven't checked the link that I posted above but anyhow here is the output:
MariaDB [cacti]> select * from poller_output;
+---------------+----------+---------------------+-------------------------------+
| local_data_id | rrd_name | time | output |
+---------------+----------+---------------------+-------------------------------+
| 11 | | 2017-03-06 12:46:02 | CPU_temp:42.7 GPU_temp:42.774 |
| 10 | | 2017-03-06 12:46:02 | CPU_temp:42.7 GPU_temp:42.774 |
| 8 | | 2017-03-06 12:46:02 | Inside:22.6 Outside:8.9 |
| 9 | | 2017-03-06 12:46:02 | Inside:22.6 Outside:8.9 |
+---------------+----------+---------------------+-------------------------------+
4 rows in set (0.00 sec)

MariaDB [cacti]> select * from poller_output;
Empty set (0.00 sec)

MariaDB [cacti]> select * from poller_output;
+---------------+----------+---------------------+-------------------------------+
| local_data_id | rrd_name | time | output |
+---------------+----------+---------------------+-------------------------------+
| 11 | | 2017-03-06 12:47:03 | CPU_temp:42.2 GPU_temp:42.236 |
| 10 | | 2017-03-06 12:47:03 | CPU_temp:41.6 GPU_temp:42.236 |
| 9 | | 2017-03-06 12:47:03 | Inside:22.6 Outside:8.8 |
| 8 | | 2017-03-06 12:47:03 | Inside:22.6 Outside:8.8 |
+---------------+----------+---------------------+-------------------------------+
4 rows in set (0.01 sec)

**Comment by cigamit** [comment]
for the 4 data input methods, can you please dump the contents of the poller_item table?

select * from poller_item when local_data_id in (10,11,9,8);

**Comment by zez3** [comment]
here you go:

```
MariaDB [cacti]> select * from poller_item where local_data_id in (10,11,9,8);
+---------------+-----------+---------+--------+---------+---------------------+-----------+----------------+--------------+---------------+---------------+--------------------+----------------------+--------------------+--------------+----------------+-----------+--------------+----------+--------------------------------------------------------+---------+----------+---------------+------------------------------+------+------+
| local_data_id | poller_id | host_id | action | present | last_updated        | hostname  | snmp_community | snmp_version | snmp_username | snmp_password | snmp_auth_protocol | snmp_priv_passphrase | snmp_priv_protocol | snmp_context | snmp_engine_id | snmp_port | snmp_timeout | rrd_name | rrd_path                                               | rrd_num | rrd_step | rrd_next_step | arg1                         | arg2 | arg3 |
+---------------+-----------+---------+--------+---------+---------------------+-----------+----------------+--------------+---------------+---------------+--------------------+----------------------+--------------------+--------------+----------------+-----------+--------------+----------+--------------------------------------------------------+---------+----------+---------------+------------------------------+------+------+
|             8 |         1 |       1 |      1 |       1 | 2017-03-13 21:07:02 | 127.0.0.1 | public         |            0 |               |               | MD5                |                      | DES                |              |                |       161 |          500 |          | /usr/share/webapps/cacti/rra/localhost_inside_8.rrd    |       1 |       60 |             0 | /opt/scripts/get_temp_cac.sh |      |      |
|             9 |         1 |       1 |      1 |       1 | 2017-03-13 21:07:02 | 127.0.0.1 | public         |            0 |               |               | MD5                |                      | DES                |              |                |       161 |          500 |          | /usr/share/webapps/cacti/rra/localhost_outside_9.rrd   |       1 |       60 |             0 | /opt/scripts/get_temp_cac.sh |      |      |
|            10 |         1 |       1 |      1 |       1 | 2017-03-13 21:07:02 | 127.0.0.1 | public         |            0 |               |               | MD5                |                      | DES                |              |                |       161 |          500 |          | /usr/share/webapps/cacti/rra/localhost_cpu_temp_10.rrd |       1 |       60 |             0 | /opt/scripts/get_sys_temp.sh |      |      |
|            11 |         1 |       1 |      1 |       1 | 2017-03-13 21:07:02 | 127.0.0.1 | public         |            0 |               |               | MD5                |                      | DES                |              |                |       161 |          500 |          | /usr/share/webapps/cacti/rra/localhost_gpu_temp_11.rrd |       1 |       60 |             0 | /opt/scripts/get_sys_temp.sh |      |      |
+---------------+-----------+---------+--------+---------+---------------------+-----------+----------------+--------------+---------------+---------------+--------------------+----------------------+--------------------+--------------+----------------+-----------+--------------+----------+--------------------------------------------------------+---------+----------+---------------+------------------------------+------+------+
4 rows in set (0.01 sec)
```

**Comment by cigamit** [comment]
Hmm.  Can you provide a screen shots of the Data Input Method of one of these in the 'Edit' mode so I can see the field mappings.  Also, the same Data Template for the Data Input method.

**Comment by zez3** [comment]
![image](https://cloud.githubusercontent.com/assets/22619253/23894851/ff1a1578-08a3-11e7-858c-c36068ca598a.png)

![image](https://cloud.githubusercontent.com/assets/22619253/23895124/01c539b4-08a5-11e7-896e-2750806004c4.png)

![image](https://cloud.githubusercontent.com/assets/22619253/23895436/fc0ef8d8-08a5-11e7-8859-36e9d32d863f.png)

![image](https://cloud.githubusercontent.com/assets/22619253/23895023/998d21ae-08a4-11e7-98b7-9459b670afb4.png)

![image](https://cloud.githubusercontent.com/assets/22619253/23895475/221df15a-08a6-11e7-86fb-d28ac74a5a05.png)

![image](https://cloud.githubusercontent.com/assets/22619253/23895389/d5ad8c2c-08a5-11e7-864b-bce9db12ed8f.png)
![image](https://cloud.githubusercontent.com/assets/22619253/23895550/64ce1b10-08a6-11e7-8a0d-cd2d4aacb87f.png)

here are some prt-screens with my config
Let me know if need something else
Thanks

**Comment by cigamit** [comment]
So, you have no data template associated with these?  It's a full manual process from data input method all the way to graph.  I figured no one in their right mind would ever do that since like Cacti 0.6.  This is why it was never tested.  Can you just confirm that?

**Comment by zez3** [comment]
Yes, this was a manually created graph, no template was used indeed.

**Comment by cigamit** [comment]
This should be working now.  You will have to remove the corrupt graphs though.

**Comment by rcmcronny** [comment]
i have had this issue also.
i tdid a new upgrade from 0.8.8h to 1.1.0 and created also a new graph, but this issue persists.
I've had post in the forum (http://forums.cacti.net/viewtopic.php?f=2&t=56908) but no response, its exact the same issue as here mentioned. 
I have now assigned the data queries and graphs to 1 device, so its not device and template less
These graphs worked with 0.x cactis without any issues.

@zez3 does ist work for you with 1.1.0 ?

Thanks Ronny

**Comment by zez3** [comment]
Nope, same here, not working. Tried recreating the graph and data sources. 
```
2017-03-22 14:07:07 - SYSTEM STATS: Time:5.4157 Method:cmd.php Processes:25 Threads:N/A Hosts:2 HostsPerProcess:1 DataSources:4 RRDsProcessed:1
2017-03-22 14:07:07 - POLLER: Poller[1] Time: 3.9423 s, Poller: , Theads: N/A, Devices: 1
2017-03-22 14:07:03 - PING Device[1] PING: UDP Ping Success (0.41 ms)
2017-03-22 14:07:03 - POLLER: Poller[1] NOTE: There are no items in your poller for this polling cycle!
2017-03-22 14:07:02 - POLLER: Poller[1] WARNING: Poller Output Table not Empty. Issues Found: 3, Data Sources: (DS[9]), (DS[10]), (DS[11])
2017-03-22 14:07:02 - POLLER: Poller[1] NOTE: Poller Int: '60', Cron Int: '60', Time Since Last: '60.33', Max Runtime '58', Poller Runs: '1'
2017-03-22 14:06:07 - SYSTEM STATS: Time:5.4233 Method:cmd.php Processes:25 Threads:N/A Hosts:2 HostsPerProcess:1 DataSources:4 RRDsProcessed:1
2017-03-22 14:06:07 - POLLER: Poller[1] Parsed MULTI output field '10min:0.39' [map 10min->load_15min]
2017-03-22 14:06:07 - POLLER: Poller[1] Parsed MULTI output field '5min:0.45' [map 5min->load_5min]
2017-03-22 14:06:07 - POLLER: Poller[1] Parsed MULTI output field '1min:0.66' [map 1min->load_1min]
2017-03-22 14:06:06 - POLLER: Poller[1] Time: 4.0395 s, Poller: , Theads: N/A, Devices: 1
2017-03-22 14:06:02 - PING Device[1] PING: UDP Ping Success (0.34 ms)
2017-03-22 14:06:02 - POLLER: Poller[1] NOTE: There are no items in your poller for this polling cycle!
2017-03-22 14:06:02 - POLLER: Poller[1] WARNING: Poller Output Table not Empty. Issues Found: 4, Data Sources: (DS[9]), (DS[10]), (DS[11]), (DS[15])
2017-03-22 14:06:02 - POLLER: Poller[1] NOTE: Poller Int: '60', Cron Int: '60', Time Since Last: '60.03', Max Runtime '58', Poller Runs: '1'
2017-03-22 14:05:12 - SYSTEM STATS: Time:10.6024 Method:cmd.php Processes:25 Threads:N/A Hosts:2 HostsPerProcess:1 DataSources:5 RRDsProcessed:1
2017-03-22 14:05:12 - POLLER: Poller[1] Time: 8.7256 s, Poller: , Theads: N/A, Devices: 1
2017-03-22 14:05:03 - PING Device[1] PING: UDP Ping Success (0.62 ms)
2017-03-22 14:05:03 - POLLER: Poller[1] NOTE: There are no items in your poller for this polling cycle!
2017-03-22 14:05:02 - POLLER: Poller[1] WARNING: Poller Output Table not Empty. Issues Found: 3, Data Sources: (DS[9]), (DS[10]), (DS[11])
2017-03-22 14:05:02 - POLLER: Poller[1] NOTE: Poller Int: '60', Cron Int: '60', Time Since Last: '61.18', Max Runtime '58', Poller Runs: '1'
2017-03-22 14:04:07 - SYSTEM STATS: Time:5.4116 Method:cmd.php Processes:25 Threads:N/A Hosts:2 HostsPerProcess:1 DataSources:4 RRDsProcessed:1
2017-03-22 14:04:06 - POLLER: Poller[1] Time: 3.9359 s, Poller: , Theads: N/A, Devices: 1
2017-03-22 14:04:02 - PING Device[1] PING: UDP Ping Success (0.4 ms)
2017-03-22 14:04:02 - POLLER: Poller[1] NOTE: There are no items in your poller for this polling cycle!
2017-03-22 14:04:01 - POLLER: Poller[1] WARNING: Poller Output Table not Empty. Issues Found: 3, Data Sources: (DS[9]), (DS[10]), (DS[11])
2017-03-22 14:04:01 - POLLER: Poller[1] NOTE: Poller Int: '60', Cron Int: '60', Time Since Last: '59.85', Max Runtime '58', Poller Runs: '1'
2017-03-22 14:03:08 - SYSTEM STATS: Time:6.4151 Method:cmd.php Processes:25 Threads:N/A Hosts:2 HostsPerProcess:1 DataSources:4 RRDsProcessed:1
2017-03-22 14:03:07 - POLLER: Poller[1] Time: 4.9406 s, Poller: , Theads: N/A, Devices: 1
2017-03-22 14:03:03 - PING Device[1] PING: UDP Ping Success (0.4 ms)
2017-03-22 14:03:02 - POLLER: Poller[1] NOTE: There are no items in your poller for this polling cycle!
2017-03-22 14:03:02 - POLLER: Poller[1] WARNING: Poller Output Table not Empty. Issues Found: 3, Data Sources: (DS[9]), (DS[10]), (DS[11])
2017-03-22 14:03:02 - POLLER: Poller[1] NOTE: Poller Int: '60', Cron Int: '60', Time Since Last: '61.18', Max Runtime '58', Poller Runs: '1'
2017-03-22 14:02:07 - SYSTEM STATS: Time:5.4087 Method:cmd.php Processes:25 Threads:N/A Hosts:2 HostsPerProcess:1 DataSources:4 RRDsProcessed:1
2017-03-22 14:02:06 - POLLER: Poller[1] Time: 4.0499 s, Poller: , Theads: N/A, Devices: 1
2017-03-22 14:02:02 - PING Device[1] PING: UDP Ping Success (0.4 ms)
2017-03-22 14:02:02 - POLLER: Poller[1] NOTE: There are no items in your poller for this polling cycle!
2017-03-22 14:02:02 - POLLER: Poller[1] WARNING: Poller Output Table not Empty. Issues Found: 3, Data Sources: (DS[9]), (DS[10]), (DS[11])
2017-03-22 14:02:01 - POLLER: Poller[1] NOTE: Poller Int: '60', Cron Int: '60', Time Since Last: '59.96', Max Runtime '58', Poller Runs: '1'
2017-03-22 14:01:08 - SYSTEM STATS: Time:5.4435 Method:cmd.php Processes:25 Threads:N/A Hosts:2 HostsPerProcess:1 DataSources:4 RRDsProcessed:1
2017-03-22 14:01:08 - POLLER: Poller[1] Parsed MULTI output field '10min:0.39' [map 10min->load_15min]
2017-03-22 14:01:08 - POLLER: Poller[1] Parsed MULTI output field '5min:0.43' [map 5min->load_5min]
2017-03-22 14:01:08 - POLLER: Poller[1] Parsed MULTI output field '1min:0.51' [map 1min->load_1min]
2017-03-22 14:01:07 - POLLER: Poller[1] Time: 4.0279 s, Poller: , Theads: N/A, Devices: 1
2017-03-22 14:01:03 - PING Device[1] PING: UDP Ping Success (0.51 ms)
2017-03-22 14:01:03 - POLLER: Poller[1] NOTE: There are no items in your poller for this polling cycle!
2017-03-22 14:01:02 - POLLER: Poller[1] WARNING: Poller Output Table not Empty. Issues Found: 4, Data Sources: (DS[9]), (DS[10]), (DS[11]), (DS[15])
2017-03-22 14:01:02 - POLLER: Poller[1] NOTE: Poller Int: '60', Cron Int: '60', Time Since Last: '61.66', Max Runtime '58', Poller Runs: '1'
2017-03-22 14:00:11 - SYSTEM STATS: Time:9.5792 Method:cmd.php Processes:25 Threads:N/A Hosts:2 HostsPerProcess:1 DataSources:5 RRDsProcessed:1
2017-03-22 14:00:11 - POLLER: Poller[1] Time: 7.8688 s, Poller: , Theads: N/A, Devices: 1
2017-03-22 14:00:03 - PING Device[1] PING: UDP Ping Success (0.59 ms)
2017-03-22 14:00:02 - POLLER: Poller[1] NOTE: There are no items in your poller for this polling cycle!
2017-03-22 14:00:02 - POLLER: Poller[1] WARNING: Poller Output Table not Empty. Issues Found: 3, Data Sources: (DS[9]), (DS[10]), (DS[11])
2017-03-22 14:00:02 - POLLER: Poller[1] NOTE: Poller Int: '60', Cron Int: '60', Time Since Last: '59.98', Max Runtime '58', Poller Runs: '1'
2017-03-22 13:59:07 - SYSTEM STATS: Time:5.4132 Method:cmd.php Processes:25 Threads:N/A Hosts:2 HostsPerProcess:1 DataSources:4 RRDsProcessed:1
```
I saw a few red strange graph.php related errors after the upgrade but I did not managed to save them.
I'll try to somehow get them from and archive or rerun the install process.

I think this ticket should be reoppened.

**Comment by zez3** [comment]
So here is what I get after  upgrading to the lastest version:
```
2017-04-01 20:53:07 - SYSTEM STATS: Time:5.2995 Method:cmd.php Processes:25 Threads:N/A Hosts:2 HostsPerProcess:1 DataSources:4 RRDsProcessed:1
2017-04-01 20:53:06 - POLLER: Poller[1] Time: 3.9642 s, Poller: , Theads: N/A, Devices: 1
2017-04-01 20:53:02 - PING Device[1] PING: UDP Ping Success (0.41 ms)
2017-04-01 20:53:02 - POLLER: Poller[1] NOTE: There are no items in your poller for this polling cycle!
2017-04-01 20:53:01 - POLLER: Poller[1] WARNING: Poller Output Table not Empty. Issues Found: 3, Data Sources: (DS[9]), (DS[10]), (DS[11])
2017-04-01 20:53:01 - POLLER: Poller[1] NOTE: Poller Int: '60', Cron Int: '60', Time Since Last: '60.71', Max Runtime '58', Poller Runs: '1'
2017-04-01 20:52:07 - SYSTEM STATS: Time:5.3187 Method:cmd.php Processes:25 Threads:N/A Hosts:2 HostsPerProcess:1 DataSources:4 RRDsProcessed:1
2017-04-01 20:52:06 - POLLER: Poller[1] Time: 3.8798 s, Poller: , Theads: N/A, Devices: 1
2017-04-01 20:52:02 - PING Device[1] PING: UDP Ping Success (0.41 ms)
2017-04-01 20:52:02 - POLLER: Poller[1] NOTE: There are no items in your poller for this polling cycle!
2017-04-01 20:52:01 - POLLER: Poller[1] WARNING: Poller Output Table not Empty. Issues Found: 3, Data Sources: (DS[9]), (DS[10]), (DS[11])
2017-04-01 20:52:01 - POLLER: Poller[1] NOTE: Poller Int: '60', Cron Int: '60', Time Since Last: '59.85', Max Runtime '58', Poller Runs: '1'
2017-04-01 20:51:12 - CMDPHP SQL Backtrace: (/graph_view.php: 313 grow_right_pane_tree)(/lib/html_tree.php: 1000 get_allowed_graphs)(/lib/auth.php: 1027 db_fetch_cell)(/lib/database.php: 201 db_fetch_cell_prepared)(/lib/database.php: 246 cacti_debug_backtrace)
2017-04-01 20:51:12 - CMDPHP SQL Backtrace: (/graph_view.php: 313 grow_right_pane_tree)(/lib/html_tree.php: 1000 get_allowed_graphs)(/lib/auth.php: 1012 db_fetch_assoc)(/lib/database.php: 320 db_fetch_assoc_prepared)(/lib/database.php: 359 cacti_debug_backtrace)
2017-04-01 20:51:12 - DBCALL ERROR: SQL Assoc Failed!, Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'AND gl.host_id=1 HAVING (user0 IS NULL OR (user1 IS NULL OR user2 IS NULL)) ' at line 1
2017-04-01 20:51:12 - DBCALL ERROR: SQL Assoc Failed!, Error:1064, SQL:"SELECT gtg.local_graph_id, h.description, gt.name AS template_name, gtg.title_cache, gtg.width, gtg.height, gl.snmp_index, gl.snmp_query_id, uap0.user_id AS user0, uap1.user_id AS user1, uap2.user_id AS user2 FROM graph_templates_graph AS gtg INNER JOIN graph_local AS gl ON gl.id=gtg.local_graph_id LEFT JOIN graph_templates AS gt ON gt.id=gl.graph_template_id LEFT JOIN host AS h ON h.id=gl.host_id LEFT JOIN user_auth_perms AS uap0 ON (gl.id=uap0.item_id AND uap0.type=1 AND uap0.user_id=1) LEFT JOIN user_auth_perms AS uap1 ON (gl.host_id=uap1.item_id AND uap1.type=3 AND uap1.user_id=1) LEFT JOIN user_auth_perms AS uap2 ON (gl.graph_template_id=uap2.item_id AND uap2.type=4 AND uap2.user_id=1) WHERE gl.graph_template_id= AND gl.host_id=1 HAVING (user0 IS NULL OR (user1 IS NULL OR user2 IS NULL)) ORDER BY gtg.title_cache "
2017-04-01 20:51:09 - CMDPHP SQL Backtrace: (/graph_view.php: 313 grow_right_pane_tree)(/lib/html_tree.php: 1000 get_allowed_graphs)(/lib/auth.php: 1027 db_fetch_cell)(/lib/database.php: 201 db_fetch_cell_prepared)(/lib/database.php: 246 cacti_debug_backtrace)
2017-04-01 20:51:09 - CMDPHP SQL Backtrace: (/graph_view.php: 313 grow_right_pane_tree)(/lib/html_tree.php: 1000 get_allowed_graphs)(/lib/auth.php: 1012 db_fetch_assoc)(/lib/database.php: 320 db_fetch_assoc_prepared)(/lib/database.php: 359 cacti_debug_backtrace)
2017-04-01 20:51:09 - DBCALL ERROR: SQL Assoc Failed!, Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'AND gl.host_id=1 HAVING (user0 IS NULL OR (user1 IS NULL OR user2 IS NULL)) ' at line 1
2017-04-01 20:51:09 - DBCALL ERROR: SQL Assoc Failed!, Error:1064, SQL:"SELECT gtg.local_graph_id, h.description, gt.name AS template_name, gtg.title_cache, gtg.width, gtg.height, gl.snmp_index, gl.snmp_query_id, uap0.user_id AS user0, uap1.user_id AS user1, uap2.user_id AS user2 FROM graph_templates_graph AS gtg INNER JOIN graph_local AS gl ON gl.id=gtg.local_graph_id LEFT JOIN graph_templates AS gt ON gt.id=gl.graph_template_id LEFT JOIN host AS h ON h.id=gl.host_id LEFT JOIN user_auth_perms AS uap0 ON (gl.id=uap0.item_id AND uap0.type=1 AND uap0.user_id=1) LEFT JOIN user_auth_perms AS uap1 ON (gl.host_id=uap1.item_id AND uap1.type=3 AND uap1.user_id=1) LEFT JOIN user_auth_perms AS uap2 ON (gl.graph_template_id=uap2.item_id AND uap2.type=4 AND uap2.user_id=1) WHERE gl.graph_template_id= AND gl.host_id=1 HAVING (user0 IS NULL OR (user1 IS NULL OR user2 IS NULL)) ORDER BY gtg.title_cache "
2017-04-01 20:51:07 - SYSTEM STATS: Time:5.3227 Method:cmd.php Processes:25 Threads:N/A Hosts:2 HostsPerProcess:1 DataSources:4 RRDsProcessed:1
2017-04-01 20:51:07 - POLLER: Poller[1] Parsed MULTI output field '10min:0.41' [map 10min->load_15min]
2017-04-01 20:51:07 - POLLER: Poller[1] Parsed MULTI output field '5min:0.43' [map 5min->load_5min]
2017-04-01 20:51:07 - POLLER: Poller[1] Parsed MULTI output field '1min:0.62' [map 1min->load_1min]
2017-04-01 20:51:06 - POLLER: Poller[1] Time: 3.8388 s, Poller: , Theads: N/A, Devices: 1
2017-04-01 20:51:03 - AUTH LOGIN: User 'admin' Authenticated via Authentication Cookie
2017-04-01 20:51:03 - PING Device[1] PING: UDP Ping Success (0.43 ms)
```

**Comment by cigamit** [comment]
Looking at only the SQL errors, please update to the latest lib/auth.php and see if those go away.

**Comment by cigamit** [comment]
I was speaking more of the SQL error when viewing the Tree.  I'm still not certain of the other issue.

**Comment by cigamit** [comment]
When you goto the poller item table, there is a column 'rrd_num'.  For you example(s), what is that value?  The reason that I ask is that you are specifying two outputs for your Data Input Method, but only using one of them in the graph.  I'm not sure that will work.  We expect that the two output values will be used, in other words, your output should look like "CPU_temp:nn GPU_temp:mm", and that you will have two data sources in your Data template: CPU_temp and GPU_temp.  Your RRDfile also contains a number of data sources that are not in the Data Template.

**Comment by cigamit** [comment]
No feedback.

**Comment by zez3** [comment]
Took you long enough. But it's finally fixed. Version 1.1.13 has fixes this issue

**Comment by majed17** [comment]
so i get this on 1.2.x, while on another 1.2.6 cacti there is no such problem with the same device...

 
 2019/09/24 15:45:02 - POLLER: Poller[Main Poller] WARNING: Poller Output Table not Empty. Issues: 1, DS[Nexus 5000 - Traffic - Ethernet10/1/11] Graphs[Nexus 5000 - Traffic - Ethernet10/1/11 - server ] 
2019/09/24 15:40:07 - SYSTEM STATS: Time:5.9445 Method:spine  Processes:2 Threads:5 Hosts:37 HostsPerProcess:19 DataSources:4290  RRDsProcessed:1603
2019/09/24 15:40:05 - SPINE: Poller[Main Poller] PID[19443] Device[Nexus 5000] HT[1] DS[Nexus 000 - Traffic - Ethernet10/1/11] Graphs[Nexus 5000 - Traffic - Ethernet10/1/11 - server ] WARNING: SNMP timeout detected [500 ms], ignoring host '10.10.234.234'

i tried queering the device and saving  and it logs that is reindexing but then after a while the same thing repeats!
what is this about?

**Comment by cigamit** [comment]
@majed17, old comment.  It's likely due to your Nexus timing out with a small snmp (500ms) timeout.  You have to watch the MaxOID's per get request.  As you increase that number, the device will take longer to respond.  On some of the old Cisco switches, if you got in the 20's, thing became very unstable.

**Comment by majed17** [comment]
wow you nailed it...i was so deceived by the thought that i have 2 nexuses of the same model so it must be the desert plant again sucking up all the water ..  but then i realized, the other nexus has a newer ios, so it's timeout must be fixed.. and now almost a day after reducing the threads and processes to 1, the affected device shut up!

**Comment by sirjana** [comment]
I am getting Cacti log error as:
1/03/2020 12:18:39 PM - CMDPHP: Poller[0] WARNING: SNMP Get Timeout for Host
Due to this all graph seems broken and I tried on different server and working fine. I have increased The Maximum SNMP OID's Per SNMP Get Request and snmp timeout but it's still not working. Any idea? please help

**Comment by netniV** [comment]
It would suggest that Cacti can't retrieve the data from that device for that interface.  If that is true, disable the source and everything else should be working.  Whilst that is disabled, check and verify why it's not presenting itself using the snmpwalk command line tools from the cacti server.

**Comment by sirjana** [comment]
Thank you for the comment @netniV. snmpwalk is working fine and data can be query but there is break between graph on certain interval.
![cacti](https://user-images.githubusercontent.com/16487387/71950396-25dec780-31ff-11ea-9b5d-c9be38a5cc08.png)

**Comment by netniV** [comment]
Then that would suggest either the device is getting too busy to respond at that time or your server is

**Comment by sirjana** [comment]
It might be. Trying to reduce unwanted hosts. Lets see this will solve the problem.

**Comment by netniV** [comment]
Because something didn’t get polled either a crash or too many items or non responsiveness from an endpoint.
