### ISSUE TITLE
SNMP Engine ID (v3) field too short

### ISSUE THREAD

**Issue by Yannis100** [Cacti/cacti#400]
Hello,

I have to monitor some PaloAlto FW devices and the EngineID is longer than the maximum allowed char in the form field, therefore I can't use SNMPv3 at the moment (tried without setting the engineID without success)

e.g. of a PaloAlto EngineID 0x80001F8804303031383031303035363833

Can you increase the field size or help me with this issue ?

Thanks for you dedicated work on this amazing tool :)

Regards

**Comment by cigamit** [comment]
Resolved, thanks for testing.  Will be a part of 1.0.5

**Comment by Yannis100** [comment]
Hello,

Thanks ! But I'm still facing issue :(

I don't know if I did anything wrong when updating, I was already on pre-1.0.5 so install/upgrade said it was already in last version, I ran the update commands manually in the SQL server.
![image](https://cloud.githubusercontent.com/assets/3008631/23892059/6bb29256-0899-11e7-800e-e0cf23162fe4.png)
Unfortunately the field has still a length of 30, I changed the engineID directly in DB to test and I face the previous error (tried without the 0x too)

**Comment by cigamit** [comment]
Width issue is solved.  As indicated, please test from the command line.  If it's working from there, please let us know.
