### ISSUE TITLE
Graphs -> Apply Automation rules

### ISSUE THREAD

**Issue by stivnnik** [Cacti/cacti#401]
Hello,

I am experiencing the following errors when I try to apply automation rules:
```
[Thu Mar 09 17:28:32 2017] [error] [client 192.168.124.224] PHP Notice:  Undefined variable: action in /usr/share/cacti/graphs.php on line 659, referer: http://192.168.124.116/cacti/graphs.php
[Thu Mar 09 17:28:32 2017] [error] [client 192.168.124.224] PHP Fatal error:  Call to undefined function execute_graph_create_tree() in /usr/share/cacti/graphs.php on line 663, referer: http://192.168.124.116/cacti/graphs.php
```

Tested on 1.0.3 and 1.0.4.

Thank you,
Stefan Nikolov

**Comment by cigamit** [comment]
Resolved, thanks for taking the time to report!

**Comment by stivnnik** [comment]
Thank you! I have checked the commit and applied it locally, but the issue persists.
Digging a bit deeper:
```
[root@netcacti cacti]# grep -rni "execute_graph_create_tree" .
./graphs.php:664:                                       execute_graph_create_tree($selected_items[$i]);
./lib/api_automation.php:2019:  automation_execute_graph_create_tree($data['id']);
./lib/api_automation.php:2204:function automation_execute_graph_create_tree($graph_id) {
```

The function actually isn't defined.
Tried to replace execute_graph_create_tree with automation_execute_graph_create_tree in graphs.php:664. Now the PHP Fatal Error is gone, but the trees are still not created and the graphs are still not added to them although there are matching Tree Rules (including the default ones).

Could you please check again?

Thank you,
Stefan Nikolov

**Comment by cigamit** [comment]
Ope, I missed that.  Sorry.  Fixing the function error now.  Then it's a debug issue.

**Comment by cigamit** [comment]
Should be resolved again now.  You will have to update lib/api_automation.php.  Thanks again for reporting.
