### ISSUE TITLE
Cacti->Management->Devices search return black screen if device name contain # character 

### ISSUE THREAD

**Issue by ikorzha** [Cacti/cacti#4192]
Cacti->Management->Devices search return black screen if device name contain # character .
Using the Cacti version 1.2.16, Broswer Crome.

here is the url when error occurs: /host.php?host_status=-1&host_template_id=-1&site_id=-1&criticality=-1&poller_id=-1&rows=-1&filter=Aruba%20VDI%207210%20EDC%20#&page=undefined&

![cacti-search-bug](https://user-images.githubusercontent.com/11211789/112034521-f327a300-8b14-11eb-9a1c-be66a2f01834.gif)

**Comment by TheWitness** [comment]
Well, that one caught me off guard.  A bug for sure.

**Comment by TheWitness** [comment]
Okay, this is fixed now, though if you are using the 'monitor' plugin, it'll have to be updated too.

**Comment by ikorzha** [comment]
TheWitness, my apologies, in case I am wrong. I have pulled an updated host.php file into 1.2.16 Cacti in use in my prod and I am still seeing an identical behavior with # in search. Can you please test it yourself..
Thank you in advance

**Comment by TheWitness** [comment]
You need to update monitor.
