### ISSUE TITLE
Pressing Back often fails to work as expected

### ISSUE THREAD

**Issue by stivnnik** [Cacti/cacti#430]
Hello,

The back button is not working as expected. It is a bit frustrating while browsing graphs.
Also the browser's URL field does not correctly reflect the current location for Time Graph View.
For example: Start browsing some graphs in tree view and click Time Graph View for a specific graph. The URL stays the same (reflecting the tree) and you can't send it as a hyperlink to someone.

Kind regards,
Stefan Nikolov

**Comment by cigamit** [comment]
This is a known issue.  jsTree supports deep linking using a state object, but the documentation is not so good on how to construct it.  It's something we wanted to do before the initial 1.0.x release.  However, we have been addressing so many little issues in the weekly releases that we have not had time to address this to date.

**Comment by ronytomen** [comment]
This is a bug because of removed functionality.

I have been asked in person about this particular issue...

**Comment by cigamit** [comment]
This should be resolved now.  Update to 1.1.34, and then apply the layout.js and global_session.php from the develop branch, or wait till the release of 1.1.35.

**Comment by netniV** [comment]
On the dev branch, this is still not quite right.  To demonstrate:

* Console -> Data Collection -> Data Input Method
* Edit one of the methods
* Edit a field
* Press back (single nostate=true appears)
* Press back (single nostate=true disappears) but your on the same page
* Press back (two nostate=true appears but you do end up at data_input.php)
