### ISSUE TITLE
CMDPHP PHP ERROR Backtrace and other errors

### ISSUE THREAD

**Issue by densenator** [Cacti/cacti#4548]
<html>
<body>
I get some errors in my log file.
Please help me

08.02.2022 10:21:09 - CMDPHP PHP ERROR Backtrace: (/graph_realtime.php[218]:rrdtool_function_graph(), /lib/rrd.php[1949]:rrd_substitute_host_query_data(), /lib/rrd.php[2515]:substitute_host_data(), /lib/variables.php[313]:get_uptime(), /lib/functions.php[5181]:get_daysfromtime(), /lib/functions.php[5203]:CactiErrorHandler())
--
08.02.2022 10:21:09 - ERROR PHP DEPRECATED: Implicit conversion from float 2741440.6 to int loses precision in file: /var/www/html/lib/functions.php on line: 5203
08.02.2022 10:21:09 - CMDPHP PHP ERROR Backtrace: (/graph_realtime.php[218]:rrdtool_function_graph(), /lib/rrd.php[1583]:rrd_substitute_host_query_data(), /lib/rrd.php[2515]:substitute_host_data(), /lib/variables.php[313]:get_uptime(), /lib/functions.php[5181]:get_daysfromtime(), /lib/functions.php[5203]:CactiErrorHandler())
08.02.2022 10:21:09 - ERROR PHP DEPRECATED: Implicit conversion from float 2741440.6 to int loses precision in file: /var/www/html/lib/functions.php on line: 5203
08.02.2022 10:21:09 - CMDPHP PHP ERROR Backtrace: (/graph_realtime.php[218]:rrdtool_function_graph(), /lib/rrd.php[1583]:rrd_substitute_host_query_data(), /lib/rrd.php[2515]:substitute_host_data(), /lib/variables.php[313]:get_uptime(), /lib/functions.php[5181]:get_daysfromtime(), /lib/functions.php[5203]:CactiErrorHandler())
08.02.2022 10:21:09 - ERROR PHP DEPRECATED: Implicit conversion from float 2741440.6 to int loses precision in file: /var/www/html/lib/functions.php on line: 5203
08.02.2022 10:21:09 - CMDPHP PHP ERROR Backtrace: (/graph_realtime.php[218]:rrdtool_function_graph(), /lib/rrd.php[1583]:rrd_substitute_host_query_data(), /lib/rrd.php[2515]:substitute_host_data(), /lib/variables.php[313]:get_uptime(), /lib/functions.php[5181]:get_daysfromtime(), /lib/functions.php[5203]:CactiErrorHandler())
08.02.2022 10:21:09 - ERROR PHP DEPRECATED: Implicit conversion from float 2741440.6 to int loses precision in file: /var/www/html/lib/functions.php on line: 5203
08.02.2022 10:21:09 - CMDPHP PHP ERROR Backtrace: (/graph_realtime.php[218]:rrdtool_function_graph(), /lib/rrd.php[1583]:rrd_substitute_host_query_data(), /lib/rrd.php[2515]:substitute_host_data(), /lib/variables.php[313]:get_uptime(), /lib/functions.php[5181]:get_daysfromtime(), /lib/functions.php[5203]:CactiErrorHandler())
08.02.2022 10:21:09 - ERROR PHP DEPRECATED: Implicit conversion from float 2741440.6 to int loses precision in file: /var/www/html/lib/functions.php on line: 5203
08.02.2022 10:21:09 - CMDPHP PHP ERROR Backtrace: (/graph_realtime.php[218]:rrdtool_function_graph(), /lib/rrd.php[1583]:rrd_substitute_host_query_data(), /lib/rrd.php[2515]:substitute_host_data(), /lib/variables.php[313]:get_uptime(), /lib/functions.php[5181]:get_daysfromtime(), /lib/functions.php[5203]:CactiErrorHandler())
08.02.2022 10:21:09 - ERROR PHP DEPRECATED: Implicit conversion from float 2741440.6 to int loses precision in file: /var/www/html/lib/functions.php on line: 5203
08.02.2022 10:21:09 - CMDPHP PHP ERROR Backtrace: (/graph_realtime.php[218]:rrdtool_function_graph(), /lib/rrd.php[1583]:rrd_substitute_host_query_data(), /lib/rrd.php[2515]:substitute_host_data(), /lib/variables.php[313]:get_uptime(), /lib/functions.php[5181]:get_daysfromtime(), /lib/functions.php[5203]:CactiErrorHandler())
08.02.2022 10:21:09 - ERROR PHP DEPRECATED: Implicit conversion from float 2741440.6 to int loses precision in file: /var/www/html/lib/functions.php on line: 5203
08.02.2022 10:21:09 - CMDPHP PHP ERROR Backtrace: (/graph_realtime.php[218]:rrdtool_function_graph(), /lib/rrd.php[1583]:rrd_substitute_host_query_data(), /lib/rrd.php[2515]:substitute_host_data(), /lib/variables.php[313]:get_uptime(), /lib/functions.php[5181]:get_daysfromtime(), /lib/functions.php[5203]:CactiErrorHandler())
08.02.2022 10:21:09 - ERROR PHP DEPRECATED: Implicit conversion from float 2741440.6 to int loses precision in file: /var/www/html/lib/functions.php on line: 5203
08.02.2022 10:21:09 - CMDPHP PHP ERROR Backtrace: (/graph_realtime.php[218]:rrdtool_function_graph(), /lib/rrd.php[1583]:rrd_substitute_host_query_data(), /lib/rrd.php[2515]:substitute_host_data(), /lib/variables.php[313]:get_uptime(), /lib/functions.php[5181]:get_daysfromtime(), /lib/functions.php[5203]:CactiErrorHandler())
08.02.2022 10:21:09 - ERROR PHP DEPRECATED: Implicit conversion from float 2741440.6 to int loses precision in file: /var/www/html/lib/functions.php on line: 5203
08.02.2022 10:21:09 - CMDPHP PHP ERROR Backtrace: (/graph_realtime.php[218]:rrdtool_function_graph(), /lib/rrd.php[1583]:rrd_substitute_host_query_data(), /lib/rrd.php[2515]:substitute_host_data(), /lib/variables.php[313]:get_uptime(), /lib/functions.php[5181]:get_daysfromtime(), /lib/functions.php[5203]:CactiErrorHandler())
08.02.2022 10:21:09 - ERROR PHP DEPRECATED: Implicit conversion from float 2741440.6 to int loses precision in file: /var/www/html/lib/functions.php on line: 5203
08.02.2022 10:21:09 - CMDPHP PHP ERROR Backtrace: (/graph_realtime.php[218]:rrdtool_function_graph(), /lib/rrd.php[1583]:rrd_substitute_host_query_data(), /lib/rrd.php[2515]:substitute_host_data(), /lib/variables.php[313]:get_uptime(), /lib/functions.php[5181]:get_daysfromtime(), /lib/functions.php[5203]:CactiErrorHandler())
08.02.2022 10:21:09 - ERROR PHP DEPRECATED: Implicit conversion from float 2741440.6 to int loses precision in file: /var/www/html/lib/functions.php on line: 5203

</body>
</html>

## Desktop (please complete the following information)

- OS: debian 11.2.0
- php 8.1
- Apache 2.4.52
- 10.5.12-MariaDB-0+deb11u1 Debian 11
- installed on root directory instead of cacti
-cacti Version 1.2.20

- chrome 98.0.4758.82

**Comment by densenator** [comment]
![image](https://user-images.githubusercontent.com/18443709/152956612-f33b75f3-c35b-4414-8ea2-2a5de3e7630b.png)

**Comment by TheWitness** [comment]
Change the command from `intval()` to `floor()` and see if the problem goes away.  It's here:

```php
        $allindex    = ($elements - 1) * $p;
        $intvalindex = floor($allindex);
        $floatval    = $allindex - $intvalindex;
```

**Comment by TheWitness** [comment]
I committed the update.

**Comment by densenator** [comment]
yes, fixed, thank you

**Comment by densenator** [comment]
<html>
<body>

Not fixed.


09.02.2022 11:49:29 - CMDPHP PHP ERROR Backtrace: (/data_templates.php[44]:form_save(), /data_templates.php[253]:push_out_data_source(), /lib/template.php[221]:update_data_source_title_cache_from_template(), /lib/variables.php[37]:update_data_source_title_cache(), /lib/variables.php[99]:get_data_source_title(), /lib/functions.php[2449]:expand_title(), /lib/variables.php[234]:substitute_host_data(), /lib/variables.php[313]:get_uptime(), /lib/functions.php[5181]:get_daysfromtime(), /lib/functions.php[5203]:CactiErrorHandler())
--
09.02.2022 11:49:29 - ERROR PHP DEPRECATED: Implicit conversion from float 59626.9 to int loses precision in file: /var/www/html/lib/functions.php on line: 5203


</body>
</html>

**Comment by TheWitness** [comment]
What's on line 5203 in your version?

**Comment by densenator** [comment]
foreach ($mods as $index => $mod) {
                if ($mod > 0 || $secs) {
                        if ($time >= $mod) {
                                if ($mod < 1) {
                                        $mod = 1;
                                }
                                $val   = floor($time/$mod);
5203 -                               $time %= $mod;
                        } else {
                                $val   = 0;
                        }

                        if ($all || $val > 0) {
                                $result .= padleft($pad, $val, 2) . $text['prefix'] . $text[$index] . $text['suffix'];
                                $all = true;
                        }
                }
        }

**Comment by TheWitness** [comment]
In my version of lib/functions.php `$time %= $mod;` is line 5269.  Can you confirm?

**Comment by TheWitness** [comment]
I did another update following your back-trace and not the line numbers since they don't even match on the 1.2.x branch.

**Comment by densenator** [comment]
Nope. I changed this to $time = floor($mod);
and it is solved my errors.
That's right?

**Comment by TheWitness** [comment]
Well, that's one, but I also looked at the backtrace and what is happening is that the hosts sysUptimeInstance was being divided by 100, which is proper, and that converted the "time" value that was sent to the next function was a float, which having a modulus on a float could also throw the loss of precision error.  So, I converted it to an integer (I think).  You need to make the next update and see if the backtraces go away.

**Comment by TheWitness** [comment]
I may have to add use `inval()` instead of `floor()` or `round()`.  You need to continue to test.  I don't have a PHP8.1 env at the moment.

**Comment by TheWitness** [comment]
Let's not mess with tickets.  I'm only caring about 1.2.x in this ticket.

**Comment by TheWitness** [comment]
Right now, I'm not even working on 1.3 tickets.  @netniV and I have to get it back into shape after the 1.2.20 release.
