### ISSUE TITLE
CMDPHP ERROR: A DB Row Failed!, Error: MySQL server has gone away

### ISSUE THREAD

**Issue by ISekan** [Cacti/cacti#4789]
Cacti 1.2.21
Centos7
MariaDB 10.2.33
PHP 7.3.22

31-May-2022 04:27:50 - POLLER: Poller[1] PID[98455] WARNING: There are 2 Data Sources not returning all data leaving rows in the poller output table.  Details to follow.
31-May-2022 04:27:50 - POLLER: Poller[1] PID[98455] WARNING: Data Template 'Interface - Traffic' is impacted by lack of complete information
31-May-2022 04:27:50 - SYSTEM STATS: Time:48.8446 Method:spine Processes:1 Threads:13 Hosts:398 HostsPerProcess:398 DataSources:40100 RRDsProcessed:0
31-May-2022 04:28:18 - SYSTEM BOOST STATS: Time:86.73 ProcessNumber:2 RRDUpdates:439216
31-May-2022 04:28:28 - SYSTEM BOOST STATS: Time:96.80 ProcessNumber:1 RRDUpdates:425454
31-May-2022 04:28:29 - SYSTEM BOOST STATS: Time:98.22 RRDUpdates:864670
31-May-2022 04:28:53 - CMDPHP ERROR: A DB Exec Failed!, Error: PDOStatement::execute(): send of 89 bytes failed with errno=32 Broken pipe
31-May-2022 04:28:53 - CMDPHP ERROR: A DB Row Failed!, Error: MySQL server has gone away
31-May-2022 04:28:53 - CMDPHP ERROR: A DB Row Failed!, Error: MySQL server has gone away
31-May-2022 04:28:53 - CMDPHP ERROR: A DB Row Failed!, Error: MySQL server has gone away
31-May-2022 04:28:53 - CMDPHP ERROR: A DB Row Failed!, Error: MySQL server has gone away
31-May-2022 04:28:53 - CMDPHP ERROR: A DB Row Failed!, Error: MySQL server has gone away
31-May-2022 04:28:53 - CMDPHP ERROR: A DB Row Failed!, Error: MySQL server has gone away
31-May-2022 04:28:53 - CMDPHP ERROR: A DB Row Failed!, Error: MySQL server has gone away
31-May-2022 04:28:53 - CMDPHP ERROR: A DB Row Failed!, Error: MySQL server has gone away

**Comment by bmfmancini** [comment]
What is your mysql max packet set to?

**Comment by ISekan** [comment]
max_allowed_packet = 128M

**Comment by bmfmancini** [comment]
Is this on a remote poller?

Try raising it to 256M

**Comment by TheWitness** [comment]
I would be curious to see if there is anything logged on you Database servers /var/log/mariadb/mariadb.log.

**Comment by ISekan** [comment]
Just added 1GB RAM to server and the problem was solved

**Comment by dovi5988** [comment]
I have the same issue. I never had till I upgraded Cacit. I have set set global max_allowed_packet = 512*1024*1024; and it still happens.

**Comment by TheWitness** [comment]
I recently set `net_read_timeout` to 0 and it seemed to help.
