### ISSUE TITLE
Aggregate Graph Permissions not working as expected

### ISSUE THREAD

**Issue by densenator** [Cacti/cacti#4921]
# Describe the bug

My device have only 5 graphs.
But in tree i see this:
![image](https://user-images.githubusercontent.com/18443709/188825990-579c0107-5f67-4d43-b404-8344fac85437.png)

In tree i have only device.
In device i see 5 graphs

Also i don't able to change some aggregate graph items
And users don't see some graphs in preview mode

**Comment by TheWitness** [comment]
Got into Debug mode for the two graphs and output the RRDtool syntax and it's result.

**Comment by densenator** [comment]
In device i see only 5 graphs
It's tree mode bug. I don't know where is debug mode for this.

Also i don't able to change some aggregate graph items
And users don't see some graphs in preview mode.

**Comment by TheWitness** [comment]
That's a Cacti error.  Check permissions from the User page.  Report back.

**Comment by densenator** [comment]
My permission is full because i go from admin.
I tried create another user with full permission. It's the same. Maybe i need to create my aggregate graph again? But I have seen them before.

**Comment by TheWitness** [comment]
You should be able to edit the user in question and see this graph from the graph permissions tab, and then if you hover over the effective permission, you can see where and how the access is blocked.

**Comment by j66h** [comment]
Hi,
I have the same problem.
Updated cacti by using "git clone -b 1.2.x  https://github.com/Cacti/cacti.git" on 09/12/2022.
Did "chown www-data:www-data -R /var/www/html/cacti/" after update.

I get the following for all aggregate graphs:
![image](https://user-images.githubusercontent.com/54892435/191497578-4dc4051f-1ff4-49ae-aaed-7b904b43f5e4.png)

This is shown in Graph preview with debug turned on.
![image](https://user-images.githubusercontent.com/54892435/191497839-c9d9832c-bc2c-483b-8abd-475a7d9ac615.png)

Happens, regardless which user I use. Permissions below are from builtin local admin account:
![image](https://user-images.githubusercontent.com/54892435/191498043-8974cb88-8e07-40a7-84ab-29b4dbbaaba1.png)

Just for reference, this is shown for another admin account, who inherits all settings from Admin Gourp:
![image](https://user-images.githubusercontent.com/54892435/191498239-aafbdd39-69ab-412f-9636-4c9af7658051.png)


Please tell me, If I can show further things to help analyze this.
Best Regards, JHH

**Comment by TheWitness** [comment]
I would need a database dump to make a call on this.  Also, under `Console > Settings > General` let me know your Graph Permission Method.

![image](https://user-images.githubusercontent.com/1439914/192105808-de7971fc-8a7b-43e6-9892-34d6352199f3.png)

**Comment by j66h** [comment]
Graph Permission Mode is set tp "Permissive". I now have tested the three other options too. All four behave in the same way.

Do you have some hints to anonymize a database dump (exchange Hostnames, IP Adresses, Credentials and the like with anonymized values)? If I can anonymize, I can share without asking data security departement...

Do you have some private upload area? Or a way to privately send a link for you to download? I cannot share the dump in github...

**Comment by TheWitness** [comment]
Best thing is email.  If too big, then we will have to use box or eauiv.

**Comment by j66h** [comment]
Tried to send mail to address of your profile.
Got a return to sender, that our mailserver is open relay with a link to spamhaus webpage. At that webpage it says, that our server does not have an issue but that the server of the recipient is misconfigured.

I involved our mail admins. maybe you can elaborate too?

I'll resend later that week. Maybe it just was a spamhaus hickup...

**Comment by j66h** [comment]
No SPAM problems anymore, but now "message too big". The zipped dump is approximately 5 MByte in Size.
I can provide it on a onedrive share, if you like?

**Comment by TheWitness** [comment]
Fixed now.  Just download `lib/auth.php` from the 1.2.x branch.

**Comment by j66h** [comment]
as built in admin I now see only aggregates.
as other admin authenticated by active drietory I still have the same problem
![image](https://user-images.githubusercontent.com/54892435/193038916-f401ba8a-d8b1-4d5a-a533-371e659637a6.png)
![image](https://user-images.githubusercontent.com/54892435/193038956-2c14074c-213e-4417-9b6b-1849feaca396.png)

**Comment by TheWitness** [comment]
View that other graph in debug mode as the user.

**Comment by j66h** [comment]
![image](https://user-images.githubusercontent.com/54892435/193043541-8a8fe1e8-ec8f-47ad-b4ae-6d45331390b6.png)

**Comment by j66h** [comment]
![image](https://user-images.githubusercontent.com/54892435/193043703-a9944cb1-6251-4e4c-84a9-78c6f4e4b911.png)

**Comment by TheWitness** [comment]
Okay, all fixed up now.

**Comment by TheWitness** [comment]
Thanks again for reporting!!!
