### ISSUE TITLE
Graphs not rendering - ERROR PHP NOTICE: Undefined index: id in file: C:\Cacti\Apache24\htdocs\cacti\lib\functions.php on line: 2965 

### ISSUE THREAD

**Issue by timeslice** [Cacti/cacti#4946]
Any Graphs other than advanced ping seem to have this issue, ie. Interface stats CPU etc.

Graphs not rendering at all and - ERROR PHP NOTICE: Undefined index: id in file: C:\Cacti\Apache24\htdocs\cacti\lib\functions.php on line: 2965

If I inspect the graph HTML and Open just this the img tag in chrome in a new tab I see the graph and get the below error:

So chrome appears to be able to render the image but not when it's in the Cacti Interface.
----------------------------------------------
This page contains the following errors:
error on line 872 at column 1: Extra content at the end of the document
Below is a rendering of the page up to the first error.

Any help apprected.

**Comment by bmfmancini** [comment]
This was fixed in the 1.2.x branch pull down the latest lib/functions file

**Comment by timeslice** [comment]
We dd try that and are on v1.2.22

**Comment by bmfmancini** [comment]
It was fixed after the 1.2.22 release
Did you pull the functions file after the install of 1.2.22?

**Comment by timeslice** [comment]
I've just tried pulling the below file and restarting apache and still appear to have the issue

https://raw.githubusercontent.com/Cacti/cacti/1.2.x/lib/functions.php

We may have been doing the dev branch before but this definitely appears to be the 1.2.x branch

I'm now not seeing that same error in the logs though but graphs still empty

**Comment by bmfmancini** [comment]
Ok so two issues then
Since the error is gone that functions fixed it for you

Check you graph template to ensure its is not using svg I believe there is
a WIndows thing with svg and the graphs switch it to png

**Comment by timeslice** [comment]
That seems to have resolved it. Thanks again for your help.

**Comment by TheWitness** [comment]
Don't forget to close your tickets when the issue is solved.  I'll do it this time.
