### ISSUE TITLE
Minor Bug with Device Ownership Selection

### ISSUE THREAD

**Issue by reubenfarrelly** [Cacti/cacti#509]
I have a use case where I want to stage a graph on a test host and then relocate it to a new device.  There appears to be two ways to do this in the UI:

1. Management -> Graphs -> Click on the graph -> select Unlock Graph and then choose the Device that the Graph belongs to.  For me this only ever shows one option in the dropdown, which is the existing host that the graph is already associated with.

[Incidentally there seems to be a minor UI issue with 'Unlock Graph' text link not being bolded like the other 3 options?]

2. Management -> Graphs -> Select the tickbox for the graph(s) on the right hand side, and "Choose an action" of "Change Device".  This seems to allow a graph or graphs to be re-associated to a new host and gives the option of multiple hosts for the graph to be associated to.

To my way of thinking option 1 should also show all other potential hosts that the graph could be moved to - in the same way option 2 does.

**Comment by cigamit** [comment]
Which theme are you using.  If using anything but 'Classic', you just need to change the Device Name, and the options will start to appear.  I'll review the other themes and find the highlight issue.

**Comment by cigamit** [comment]
Never mind.  Should be resolved now.

**Comment by reubenfarrelly** [comment]
Still not quite right.  I'm seeing the same problem within the Data Sources Management - cannot change the host from the dropdown menu.
I've confirmed this does not work with Chrome and Firefox.
I can also confirm it works fine with the Classic theme, but does not work with the Modern theme.  So it looks like a theme specific problem.

**Comment by cigamit** [comment]
I just confirmed that with the new themes you can change the host, you simply have to clear the first one first.  However, when you change the host, the host of the Data Sources does not update which causes the graph to break.  I'll reopen to fix that.  But you can change the host.

**Comment by cigamit** [comment]
Looking at this in more detail, moving some type of Graphs to another Device is dangerous as the Data Source is not moved, which set's up all sorts of issues.  Also, when changing a Data Query based Data Source, then all Data Sources need to be moved.  This is very evil stuff.  Thoughts?

**Comment by cigamit** [comment]
Fixed
