### ISSUE TITLE
1.3.0 - QA Send email problem after upgrade

### ISSUE THREAD

**Issue by xmacan** [Cacti/cacti#5104]
FreeBSD 12.2, PHP 8.1.12

1.2.23 on the same OS/PHP works without problem (no matter the mail service method). 

 1.3.0 - Dev f2c13bd5e @ 2022-12-06 17:15, **mail service PHP mail() function**:
Fatal error: Uncaught ArgumentCountError: mailer(): Argument #3 ($cc) not passed in /usr/local/share/cacti_develop/lib/functions.php:4862 Stack trace: #0 /usr/local/share/cacti_develop/lib/functions.php(4820): mailer(Array, '', NULL, NULL, NULL, 'Cacti Test Mess...', 'This is a test ...', NULL, NULL, NULL, true, false) #1 /usr/local/share/cacti_develop/lib/functions.php(5426): send_mail('', Array, 'Cacti Test Mess...', 'This is a test ...', NULL, NULL, true) #2 /usr/local/share/cacti_develop/settings.php(343): email_test() #3 {main} thrown in /usr/local/share/cacti_develop/lib/functions.php on line 4862

 1.3.0 - Dev f2c13bd5e @ 2022-12-06 17:15, **mail service sendmail**:
Unable to send test email - nothing will happen after click "Send a test email"

**Comment by TheWitness** [comment]
`Fatal Error`.  So yea.

**Comment by TheWitness** [comment]
Try this in the near term.  @netniV is implementing some bleeding edge stuff that will have to be tested on 8.0-8.2.

![image](https://user-images.githubusercontent.com/1439914/208317557-c74a7d20-dc27-4c4b-a5b7-cc61a10731f9.png)

**Comment by TheWitness** [comment]
Aparently, NULL may not be a good default, even though he has performed multi-typing to include null|array|string.  I suspect a PHP bug, which means we may have to soften this approach and make it "string|array", and make "" the default.

**Comment by netniV** [comment]
Leave that with me. I can run through the scenarios

**Comment by TheWitness** [comment]
Yea, I had already assigned it to you.

**Comment by netniV** [comment]
I don't have time to fully test right now, but I pushed a small change.  See if that helps.  If not, I'll take another look tomorrow.

**Comment by xmacan** [comment]
not resolved:
2022-12-19 15:03:00 - ERROR PHP ERROR: Uncaught ArgumentCountError: mailer(): Argument #3 **($cc) not passed in** /usr/local/share/cacti_develop/lib/functions.php:4862 Stack trace: #0 /usr/local/share/cacti_develop/lib/functions.php(4820): mailer(Array, '"Administrator"...', NULL, NULL, NULL, 'Cacti System Wa...', 'WARNING: Cron i...', NULL, Array, Array, true, true) #1 /usr/local/share/cacti_develop/lib/functions.php(4784): send_mail('"Administrator"...', Array, 'Cacti System Wa...', 'WARNING: Cron i...', Array, Array, true, true) #2 /usr/local/share/cacti_develop/poller.php(369): admin_email('Cacti System Wa...', 'WARNING: Cron i...') #3 {main} thrown in file: /usr/local/share/cacti_develop/lib/functions.php on line: 4862

**Comment by xmacan** [comment]
actual develop branch and still not working:
2022-12-21 08:58:00 - ERROR PHP ERROR: Uncaught ArgumentCountError: mailer(): Argument #3 ($cc) not passed in /usr/local/share/cacti_develop/lib/functions.php:4969 Stack trace: #0 /usr/local/share/cacti_develop/lib/functions.php(4927): mailer(Array, '"Administrator"...', NULL, NULL, NULL, 'Cacti System Wa...', 'WARNING: Cron i...', NULL, Array, Array, true, true) #1 /usr/local/share/cacti_develop/lib/functions.php(4888): send_mail('"Administrator"...', Array, 'Cacti System Wa...', 'WARNING: Cron i...', Array, Array, true, true) #2 /usr/local/share/cacti_develop/poller.php(369): admin_email('Cacti System Wa...', 'WARNING: Cron i...') #3 {main} thrown in file: /usr/local/share/cacti_develop/lib/functions.php on line: 4969

**Comment by xmacan** [comment]
more problems with email:
Fatal error: Uncaught TypeError: text_substitute(): Argument #1 ($text) must be of type array|string, null given, called in /usr/local/share/cacti_develop/lib/functions.php on line 5138 and defined in /usr/local/share/cacti_develop/lib/functions.php:8079

can the text be null or not?

**Comment by netniV** [comment]
Text should not be null no.  that doesn't seem like the full stack trace though

**Comment by xmacan** [comment]
It is true. I modified mailer() function (remove cc,bcc and replyto input parameters) and in fuction text_sustitute allow null $text.
Everything was falling down on sending me emails.

**Comment by xmacan** [comment]
ok, all changes reverted. In log is now:
2022-12-21 12:52:59 - POLLER: Poller[1] PID[98075] Maximum runtime of 58 seconds exceeded. Exiting.
2022-12-21 12:52:59 - ERROR PHP ERROR: Uncaught ArgumentCountError: mailer(): Argument #3 ($cc) not passed in /usr/local/share/cacti_develop/lib/functions.php:4970 Stack trace: #0 /usr/local/share/cacti_develop/lib/functions.php(4927): mailer(Array, '"Administrator"...', NULL, NULL, NULL, 'Cacti System Wa...', 'Maximum runtime...', NULL, Array, Array, true, true) #1 /usr/local/share/cacti_develop/lib/functions.php(4888): send_mail('"Administrator"...', Array, 'Cacti System Wa...', 'Maximum runtime...', Array, Array, true, true) #2 /usr/local/share/cacti_develop/poller.php(721): admin_email('Cacti System Wa...', 'Maximum runtime...') #3 {main} thrown in file: /usr/local/share/cacti_develop/lib/functions.php on line: 4970
2022-12-21 12:52:59 - CMDPHP PHP ERROR Backtrace:  (CactiShutdownHandler())

**Comment by thurban** [comment]
I just added a line right before the text_substitute part to get it working.
```
        if ($body_text == null) { $body_text = ""; }
        $body      = text_substitute($body, true, $expandIds, $conversion_array);
        $body_text = text_substitute($body_text, false, $expandIds, $conversion_array);
```

Resulted in this:
 2022-12-22 15:57:33 - MAILER INFO: Mail successfully sent via PHP Mail() Function from 'Thomas Urban <thomas.urban@gmail.com>', to 'thomasurban@urban-software.de', cc '', and took 0.24 seconds, Subject 'Cacti Test Message' 

Btw, I also updated the PHPMailer to 6.7.1

**Comment by netniV** [comment]
Ah the problem here is not that the body is null but that the text only version is null.  Btw, the body_text could probably be shortened to `$body_text = $body_text ?? '';` 

We also try to avoid single line `if`'s 👍 

Great work on the diagnosis.  If you want to put a PR together we can merge it.

**Comment by netniV** [comment]
Actually, never mind, I've updated PHP Mailer and put in a fix in 66cab888b for the nulls.

See if that works for you.

**Comment by xmacan** [comment]
actual develop branch and still error:
2023-01-02 08:34:00 - POLLER: Poller[1] PID[55990] NOTE: Poller Int: '60', Cron Int: '60', Time Since Last: '1010040.14', Max Runtime '58', Poller Runs: '1'
2023-01-02 08:34:00 - POLLER: Poller[1] PID[55990] WARNING: Cron is out of sync with the Poller Interval!  The Poller Interval is '60' seconds, with a maximum of......................
2023-01-02 08:34:00 - ERROR PHP ERROR: Uncaught ArgumentCountError: mailer(): Argument #3 ($cc) not passed in /usr/local/share/cacti_develop/lib/functions.php:4967 Stack trace: #0 /usr/local/share/cacti_develop/lib/functions.php(4925): mailer(Array, '"Administrator"...', NULL, NULL, NULL, 'Cacti System Wa...', 'WARNING: Cron i...', NULL, Array, Array, true, true) #1 /usr/local/share/cacti_develop/lib/functions.php(4886): send_mail('"Administrator"...', Array, 'Cacti System Wa...', 'WARNING: Cron i...', Array, Array, true, true) #2 /usr/local/share/cacti_develop/poller.php(379): admin_email('Cacti System Wa...', 'WARNING: Cron i...') #3 {main} thrown in file: /usr/local/share/cacti_develop/lib/functions.php on line: 4967
2023-01-02 08:34:00 - CMDPHP PHP ERROR Backtrace:  (CactiShutdownHandler())

**Comment by netniV** [comment]
$cc is optional, you don't need it.  This makes no sense but I will look into it more.

**Comment by netniV** [comment]
OK, I think I found the issue.  A non-default later parameter caused the issue.

**Comment by xmacan** [comment]
It is working now!
