### ISSUE TITLE
Realtime graph on remote poller not working in 1.2.23

### ISSUE THREAD

**Issue by c0sm1n** [Cacti/cacti#5197]
Real-time Graphing does not work on any graphs that are managed on the remote poller.

The following errors are seen in cacti.log on the remote poller: 

2023/01/27 14:36:11 - CMDPHP Validation Error, Variable:poller_id, Value:f18ab1c955eab34b5daf2660ccaa4c271c0848779842f867d1c2b5375a7eaabf Backtrace:  (/remote_agent.php[66]:poll_for_data(), /remote_agent.php[301]:get_filter_request_var(), /lib/html_utility.php[493]:die_html_input_error(), /lib/html_validate.php[64]:cacti_debug_backtrace())
2023/01/27 14:36:12 - CMDPHP Validation Error, Variable:poller_id, Value:f18ab1c955eab34b5daf2660ccaa4c271c0848779842f867d1c2b5375a7eaabf Backtrace:  (/remote_agent.php[66]:poll_for_data(), /remote_agent.php[301]:get_filter_request_var(), /lib/html_utility.php[493]:die_html_input_error(), /lib/html_validate.php[64]:cacti_debug_backtrace())

<img width="482" alt="Screenshot 2023-01-27 at 1 35 19 PM" src="https://user-images.githubusercontent.com/26253207/215181839-65aff400-5086-4e91-bd3c-202d5aabf7f8.png">

**Comment by TheWitness** [comment]
Good catch!

**Comment by TheWitness** [comment]
Fixed, thanks for reporting.

**Comment by c0sm1n** [comment]
Thank you for the quick response. I no longer see the PHP validation errors in the logs, however the realtime graph still does not render. I get the same error as before.

![Screenshot 2023-01-30 at 12 14 51 PM](https://user-images.githubusercontent.com/26253207/215561319-7c53b8ee-2ab9-42d8-84ab-9c41d7fa4e5e.png)

**Comment by TheWitness** [comment]
What do you see in the Cacti log when you attempt to view these?

**Comment by c0sm1n** [comment]
This is all I get in the log after setting the log level to debug when I launch the realtime graphs

2023/01/31 21:18:42 - WEBUI Connection: online, Previous Mode: online, Page: /cacti/clog.php
2023/01/31 21:19:29 - WEBUI Connection: online, Previous Mode: notset
2023/01/31 21:19:29 - AUTH DEBUG: Using remote client IP Address found in header (REMOTE_ADDR):  
2023/01/31 21:19:30 - WEBUI Connection: online, Previous Mode: notset
2023/01/31 21:19:30 - AUTH DEBUG: Using remote client IP Address found in header (REMOTE_ADDR): 
2023/01/31 21:19:41 - WEBUI Connection: online, Previous Mode: notset
2023/01/31 21:19:41 - AUTH DEBUG: Using remote client IP Address found in header (REMOTE_ADDR):  
2023/01/31 21:19:47 - WEBUI Connection: online, Previous Mode: online, Page: /cacti/clog.php
2023/01/31 21:19:52 - WEBUI Connection: online, Previous Mode: notset

**Comment by TheWitness** [comment]
Okay, I had it fixed and then I was messing around with regular expressions and messed it up without re-testing.  Update remote agent and you will be all set.

**Comment by c0sm1n** [comment]
That did it - it's working again. Thank you so much!
