### ISSUE TITLE
[1.3 QA] Brand new install - Error deleting graphs

### ISSUE THREAD

**Issue by dallenk** [Cacti/cacti#5543]
# Describe the bug

Linux nmsdev 5.15.0-87-generic #97-Ubuntu SMP Mon Oct 2 21:09:21 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

mysql-server/jammy-updates,jammy-security,now 8.0.34-0ubuntu0.22.04.1 all [installed]
php8.1/jammy-updates,jammy-security,now 8.1.2-1ubuntu2.14 all [installed,automatic]
php8.1-cli/jammy-updates,jammy-security,now 8.1.2-1ubuntu2.14 amd64 [installed,automatic]
php8.1-common/jammy-updates,jammy-security,now 8.1.2-1ubuntu2.14 amd64 [installed,automatic]
php8.1-gd/jammy-updates,jammy-security,now 8.1.2-1ubuntu2.14 amd64 [installed,automatic]
php8.1-gmp/jammy-updates,jammy-security,now 8.1.2-1ubuntu2.14 amd64 [installed,automatic]
php8.1-intl/jammy-updates,jammy-security,now 8.1.2-1ubuntu2.14 amd64 [installed,automatic]
php8.1-ldap/jammy-updates,jammy-security,now 8.1.2-1ubuntu2.14 amd64 [installed,automatic]
php8.1-mbstring/jammy-updates,jammy-security,now 8.1.2-1ubuntu2.14 amd64 [installed,automatic]
php8.1-mysql/jammy-updates,jammy-security,now 8.1.2-1ubuntu2.14 amd64 [installed,automatic]
php8.1-opcache/jammy-updates,jammy-security,now 8.1.2-1ubuntu2.14 amd64 [installed,automatic]
php8.1-readline/jammy-updates,jammy-security,now 8.1.2-1ubuntu2.14 amd64 [installed,automatic]
php8.1-snmp/jammy-updates,jammy-security,now 8.1.2-1ubuntu2.14 amd64 [installed,automatic]
php8.1-xml/jammy-updates,jammy-security,now 8.1.2-1ubuntu2.14 amd64 [installed]

Action Failed:
Sorry, we could not process your last action.
Error:	500 Internal Server Error
Reason:	The response to the last action was unexpected.

## To Reproduce

1. Go to 'Management/Graphs'
2. Select a graph
3. choose delete from dropdown

## Expected behavior

graph to be deleted and returned to the list of available graphs.

## Screenshots
![image](https://github.com/Cacti/cacti/assets/2725066/1d9fb745-c781-4a62-b4e5-87729f30ea94)

Cacti Log error:

```
2023-10-29 13:40:28 - PHP ERROR Backtrace: (CactiShutdownHandler())

2023-10-29 13:40:28 - ERROR PHP ERROR: Uncaught TypeError: array_rekey(): Argument #1 ($array) must be of type array, bool given, called in /var/www/html/lib/utility.php on line 2106 and defined in /var/www/html/lib/functions.php:1315 Stack trace: #0 /var/www/html/lib/utility.php(2106): array_rekey() #1 /var/www/html/lib/api_graph.php(35): object_cache_get_totals() #2 /var/www/html/graphs.php(1215): api_delete_graphs() #3 /var/www/html/graphs.php(79): form_actions() #4 {main} thrown in file: /var/www/html/lib/functions.php on line: 1315
2023-10-29 13:40:28 - SQL Backtrace: (/graphs.php[79]:form_actions(), /graphs.php[1215]:api_delete_graphs(), /lib/api_graph.php[35]:object_cache_get_totals(), /lib/utility.php[2104]:db_fetch_assoc(), /lib/database.php[810]:db_fetch_assoc_prepared(), /lib/database.php[834]:db_execute_prepared())
2023-10-29 13:40:28 - CMDPHP ERROR: A DB Row Failed!, Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'id, COUNT(*) AS totals FROM graph_local AS gl WHERE id IN() GROUP BY host_id' at line 1
2023-10-29 13:40:28 - PHP ERROR Backtrace: (/graphs.php[79]:form_actions(), /graphs.php[1215]:api_delete_graphs(), /lib/api_graph.php[35]:object_cache_get_totals(), /lib/utility.php[1929]:explode(), CactiErrorHandler())
2023-10-29 13:40:28 - ERROR PHP DEPRECATED: explode(): Passing null to parameter #2 ($string) of type string is deprecated in file: /var/www/html/lib/utility.php on line: 1929
2023-10-29 13:40:28 - PHP ERROR WARNING Backtrace: (/graphs.php[79]:form_actions(), /graphs.php[1215]:api_delete_graphs(), /lib/api_graph.php[35]:CactiErrorHandler())
2023-10-29 13:40:28 - ERROR PHP WARNING: Undefined variable $local_data_ids in file: /var/www/html/lib/api_graph.php on line: 35

```

**Comment by TheWitness** [comment]
Thanks for testing.  We will be reviewing.

**Comment by dallenk** [comment]
Apologies for bumping this.  Anyone else experiencing this issue? or is it just me?

**Comment by TheWitness** [comment]
I'm out till Friday.

**Comment by TheWitness** [comment]
Okay, I've got this fixed now.

**Comment by dallenk** [comment]
yup, working great now with latest pull.
Amazing work, thank you.

**Comment by dallenk** [comment]
sorry to re-open, deleting works great, but some SQL errors remain.   deleted multiple graphs at the same time.

```
2023-11-13 18:56:13 - SQL Backtrace: (/graphs.php[79]:form_actions(), /graphs.php[1203]:api_delete_graphs(), /lib/api_graph.php[35]:object_cache_get_totals(), /lib/utility.php[2243]:db_fetch_assoc(), /lib/database.php[810]:db_fetch_assoc_prepared(), /lib/database.php[834]:db_execute_prepared())
2023-11-13 18:56:13 - CMDPHP ERROR: A DB Row Failed!, Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ') GROUP BY data_source_profile_id' at line 1
2023-11-13 18:56:13 - SQL Backtrace: (/graphs.php[79]:form_actions(), /graphs.php[1203]:api_delete_graphs(), /lib/api_graph.php[35]:object_cache_get_totals(), /lib/utility.php[2229]:db_fetch_assoc(), /lib/database.php[810]:db_fetch_assoc_prepared(), /lib/database.php[834]:db_execute_prepared())
2023-11-13 18:56:13 - CMDPHP ERROR: A DB Row Failed!, Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ') GROUP BY data_input_id' at line 1
2023-11-13 18:56:13 - SQL Backtrace: (/graphs.php[79]:form_actions(), /graphs.php[1203]:api_delete_graphs(), /lib/api_graph.php[35]:object_cache_get_totals(), /lib/utility.php[2215]:db_fetch_assoc(), /lib/database.php[810]:db_fetch_assoc_prepared(), /lib/database.php[834]:db_execute_prepared())
2023-11-13 18:56:13 - CMDPHP ERROR: A DB Row Failed!, Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ') GROUP BY gprint_id' at line 1
2023-11-13 18:56:13 - SQL Backtrace: (/graphs.php[79]:form_actions(), /graphs.php[1203]:api_delete_graphs(), /lib/api_graph.php[35]:object_cache_get_totals(), /lib/utility.php[2203]:db_fetch_assoc(), /lib/database.php[810]:db_fetch_assoc_prepared(), /lib/database.php[834]:db_execute_prepared())
2023-11-13 18:56:13 - CMDPHP ERROR: A DB Row Failed!, Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ') GROUP BY color_id' at line 1
2023-11-13 18:56:13 - SQL Backtrace: (/graphs.php[79]:form_actions(), /graphs.php[1203]:api_delete_graphs(), /lib/api_graph.php[35]:object_cache_get_totals(), /lib/utility.php[2191]:db_fetch_assoc(), /lib/database.php[810]:db_fetch_assoc_prepared(), /lib/database.php[834]:db_execute_prepared())
2023-11-13 18:56:13 - CMDPHP ERROR: A DB Row Failed!, Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ') GROUP BY vdef_id' at line 1
2023-11-13 18:56:13 - SQL Backtrace: (/graphs.php[79]:form_actions(), /graphs.php[1203]:api_delete_graphs(), /lib/api_graph.php[35]:object_cache_get_totals(), /lib/utility.php[2179]:db_fetch_assoc(), /lib/database.php[810]:db_fetch_assoc_prepared(), /lib/database.php[834]:db_execute_prepared())
2023-11-13 18:56:13 - CMDPHP ERROR: A DB Row Failed!, Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ') GROUP BY cdef_id' at line 1
2023-11-13 18:56:13 - SQL Backtrace: (/graphs.php[79]:form_actions(), /graphs.php[1203]:api_delete_graphs(), /lib/api_graph.php[35]:object_cache_get_totals(), /lib/utility.php[2167]:db_fetch_assoc(), /lib/database.php[810]:db_fetch_assoc_prepared(), /lib/database.php[834]:db_execute_prepared())
2023-11-13 18:56:13 - CMDPHP ERROR: A DB Row Failed!, Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'FROM data_local AS dl WHERE local_graph_id IN() GROUP BY snmp_query_id' at line 1
2023-11-13 18:56:13 - SQL Backtrace: (/graphs.php[79]:form_actions(), /graphs.php[1203]:api_delete_graphs(), /lib/api_graph.php[35]:object_cache_get_totals(), /lib/utility.php[2153]:db_fetch_assoc(), /lib/database.php[810]:db_fetch_assoc_prepared(), /lib/database.php[834]:db_execute_prepared())
2023-11-13 18:56:13 - CMDPHP ERROR: A DB Row Failed!, Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ') GROUP BY data_template_id' at line 1
2023-11-13 18:56:13 - SQL Backtrace: (/graphs.php[79]:form_actions(), /graphs.php[1203]:api_delete_graphs(), /lib/api_graph.php[35]:object_cache_get_totals(), /lib/utility.php[2142]:db_fetch_assoc(), /lib/database.php[810]:db_fetch_assoc_prepared(), /lib/database.php[834]:db_execute_prepared())
2023-11-13 18:56:13 - CMDPHP ERROR: A DB Row Failed!, Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ') GROUP BY graph_template_id' at line 1
2023-11-13 18:56:13 - SQL Backtrace: (/graphs.php[79]:form_actions(), /graphs.php[1203]:api_delete_graphs(), /lib/api_graph.php[35]:object_cache_get_totals(), /lib/utility.php[2133]:db_fetch_assoc(), /lib/database.php[810]:db_fetch_assoc_prepared(), /lib/database.php[834]:db_execute_prepared())
2023-11-13 18:56:13 - CMDPHP ERROR: A DB Row Failed!, Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ') GROUP BY host_id' at line 1
2023-11-13 18:56:13 - SQL Backtrace: (/graphs.php[79]:form_actions(), /graphs.php[1203]:api_delete_graphs(), /lib/api_graph.php[35]:object_cache_get_totals(), /lib/utility.php[2120]:db_fetch_assoc(), /lib/database.php[810]:db_fetch_assoc_prepared(), /lib/database.php[834]:db_execute_prepared())
2023-11-13 18:56:13 - CMDPHP ERROR: A DB Row Failed!, Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'id, COUNT(*) AS totals FROM graph_local AS gl WHERE id IN() GROUP BY host_id' at line 1
2023-11-13 18:56:13 - PHP ERROR Backtrace: (/graphs.php[79]:form_actions(), /graphs.php[1203]:api_delete_graphs(), /lib/api_graph.php[35]:object_cache_get_totals(), /lib/utility.php[1929]:explode(), CactiErrorHandler())
2023-11-13 18:56:13 - ERROR PHP DEPRECATED: explode(): Passing null to parameter #2 ($string) of type string is deprecated in file: /var/www/html/cacti/lib/utility.php on line: 1929
2023-11-13 18:56:13 - PHP ERROR WARNING Backtrace: (/graphs.php[79]:form_actions(), /graphs.php[1203]:api_delete_graphs(), /lib/api_graph.php[35]:CactiErrorHandler())
2023-11-13 18:56:13 - ERROR PHP WARNING: Undefined variable $local_data_ids in file: /var/www/html/cacti/lib/api_graph.php on line: 35
```

**Comment by TheWitness** [comment]
Yea, I saw it and blew it off.  Must be getting tired.  Very many balls afloat right now.

**Comment by TheWitness** [comment]
The error should be gone now, but I'm concerned that the counts are off in this corner case.  I still have to investigate.  Will do it in final QA before release.
