### ISSUE TITLE
Some Tooltips no more working on 1.2.26 (SOLUTION FOUND NEED TO APPLY)

### ISSUE THREAD

**Issue by nicolapiazzi** [Cacti/cacti#5666]
# Describe the bug

in a fresh 1.2.26 install some tooltips not workind, in my previous version 1.2.17 there was no problem

## To Reproduce

Install a fresh copy and put mouse on any question marks or put mouse on devide descrription lines

## Screenshots
![cacti tooltips](https://github.com/Cacti/cacti/assets/54310887/e9071fb2-f287-4b98-8953-9cac8f97683d)

## Desktop (please complete the following information)

- OS: Win 11 client, Rocky 9.3 Server

- Browser [e.g. chrome, safari] Chrome, Edge, Firefox are the same

**Comment by nicolapiazzi** [comment]
IN SOURCE : cacti/include/layout.js
THERE IS THIS LINE WITH A WRONG FUNCTION DOMPurity INSTEAD DOMPurify :
var text = DOMPurity.sanitize($(this).find('span').html());

**Comment by xmacan** [comment]
It was fixed here 
https://github.com/Cacti/cacti/commit/59e39b34f8f1d80b28d38a391d7aa6e7a3302f5b

**Comment by xmacan** [comment]
Try to clear cache, reload page, try another browser. It is working in 1.2.26 (actual 1.2.x branch) with firefox/edge, ...

**Comment by nicolapiazzi** [comment]
THis is into an rdp session with an Edge that never seen cacti before
but still the same
I tryed Chrome, Edge, Firexox
No more tooltips over these lines
OS : Rocky 9.3
httpd.x86_64                          2.4.57-5.el9
php.x86_64                            8.3.2-1.el9.remi
MariaDB-server.x86_64                 10.11.7-1.el9

![image](https://github.com/Cacti/cacti/assets/54310887/ffb4f09c-8061-434a-9ec5-8b9831041d0e)

**Comment by TheWitness** [comment]
Yea, this does not exist.  If using Firefox, there are some nice plugins to purge your browser cache for a site.
