### ISSUE TITLE
[CACTI 1.2.x - latest] When we try to delete graphs we see ERRORs into cacti log

### ISSUE THREAD

**Issue by anarkia1976** [Cacti/cacti#5887]
Hi @xmacan ,

When we try to delete graphs we see ERRORs into cacti log:

`2024-10-28 08:16:43 - MAINT /xxxxxxxxx_-_yyyyy_fg_sslvpnuserslogin_17958.rrd ERROR: RRDfile Maintenance unable to delete from /var/www/html/cacti/rra!`

RRD file is removed, but we we have to manually act on ---- RRDfile Cleaner - Rescan - Delete All --- otherwise the error continues to infinite loop and then it saturating the cacti log.

thanks a lot. stefano.

**Comment by TheWitness** [comment]
@anarkia1976. if you update poller_maintenance.php from the 1.2.x branch, this should be fixed now.

**Comment by anarkia1976** [comment]
> @anarkia1976. if you update poller_maintenance.php from the 1.2.x branch, this should be fixed now.

Sorry @TheWitness but the problem isn't fixed:
2024-10-30 09:05:40 - MAINT /xxxxxx_-_single_fg_sslvpnuserslogin_18028.rrd ERROR: RRDfile Maintenance unable to delete from /var/www/html/cacti/rra!

thanks a lot

**Comment by xmacan** [comment]
@anarkia1976 show permission of file xxxxxx_-_single_fg_sslvpnuserslogin_18028.rrd 
There is condition:
```
if (file_exists($source_file) && unlink($source_file)) {
           maint_debug('Deleted: ' . $file['name']);
} else {
         cacti_log($file['name'] . " ERROR: RRDfile Maintenance unable to delete from $rra_path!", true, 'MAINT');
}
```
So file exists but it isn't possible to delete it

**Comment by anarkia1976** [comment]
> xxxxxx_-_single_fg_sslvpnuserslogin_18028.rrd

ls -lrt xxxxxx_-_single_fg_sslvpnuserslogin_18028.rrd
ls: cannot access 'xxxxxx_-_single_fg_sslvpnuserslogin_18028.rrd': No such file or directory

but the error is present:
2024-10-30 09:05:40 - MAINT /xxxxxx_-_single_fg_sslvpnuserslogin_18028.rrd ERROR: RRDfile Maintenance unable to delete from /var/www/html/cacti/rra!

to reproduced:
delete a graphs from -- graphs management.
wait poller run
errors is rised

to fix:
utilties - rrdfile cleaner - rescan - delete all 

thanks a lot. stefano.

**Comment by xmacan** [comment]
Do you have actual code? What you have in poller_maintenance.php on line 564? Correct is
if (file_exists($source_file) && unlink($source_file)) {

**Comment by morganfw** [comment]
> Do you have actual code? What you have in poller_maintenance.php on line 564? Correct is if (file_exists($source_file) && unlink($source_file)) {

Hi @xmacan
we have actual code, we performed a git pull on this morning, the `poller_maintenance.php` file already contains the string

```
if (file_exists($source_file) && unlink($source_file)) {
```

![image](https://github.com/user-attachments/assets/60a53670-4d1d-4fba-8d39-fdefafd06b19)

**Comment by TheWitness** [comment]
Logic error.

**Comment by xmacan** [comment]
@TheWitness   where? I had only few minutes, cannot reproduce it

**Comment by TheWitness** [comment]
If the file does not exist, that test will fail.  We don't care if it does not exist.

**Comment by TheWitness** [comment]
@anarkia1976 , grab the latest poller_maintenance.php and see if that clear's things up.  @xmacan made the update this morning.

**Comment by morganfw** [comment]
Hi @TheWitness @xmacan,
grabbed latest commit and tried to delete a graph, now there's not error messages in the cacti.log, but at the next poller run new error log appears

`2024-10-30 14:55:57 - POLLER: Poller[[cacti-collector](https://cacti/cacti/pollers.php?action=edit&id=1)] PID[2298614] ERROR: Process being killed due to timeout! (maintenance, master, 1, Process 2276247, Time 1730295948, Timeout 300, Timestamp 1730296557)`

again to fix:
utilities - rrdfile cleaner - rescan - delete all

Regards

**Comment by TheWitness** [comment]
Well, that's interesting.  Let me test.

**Comment by TheWitness** [comment]
@morganfw, @anarkia1976, and @xmacan,

This should be all fixed up now.  It's remarkable what can be done by simply testing ;)

Larry

**Comment by TheWitness** [comment]
```sh
[root@vmhost5 cacti]# php -q poller_maintenance.php --debug
DEBUG: Checking for Purge Actions
DEBUG: Purging Required - Files Found 1
DEBUG: Grabbing 1000 RRDfiles to Remove
DEBUG: RRDClean is now running on 1 items
DEBUG: Deleted: /var/www/html/cacti/rra/84/16/2268.rrd
DEBUG: Delete from data_source_purge_action: <path_rra>/84/16/2268.rrd
DEBUG: Removing Data Source: 2268
DEBUG: RRDClean has finished a purge pass of 1 items
DEBUG: Grabbing 1000 RRDfiles to Remove
2024-10-30 12:29:26 - SYSTEM RRDMAINT STATS: Time:0.0347 Purged:1 Archived:0
DEBUG: Checking for Account / Password expiration
```

**Comment by TheWitness** [comment]
Found one more issue with structured paths....

```sh
[root@vmhost5 cacti]# php -q poller_maintenance.php --debug
DEBUG: Checking for Purge Actions
DEBUG: Purging Required - Files Found 2
DEBUG: Grabbing 1000 RRDfiles to Remove
DEBUG: RRDClean is now running on 2 items
2024-10-30 12:40:19 - MAINT WARNING: RRDfile Maintenance is unable to move /var/www/html/cacti/rra/20/16/402.rrd to /var/www/html/cacti/rra/archive!
DEBUG: Delete from data_source_purge_action: <path_rra>/20/16/402.rrd
DEBUG: Removing Data Source: 402
2024-10-30 12:40:19 - MAINT WARNING: RRDfile Maintenance is unable to move /var/www/html/cacti/rra/49/16/902.rrd to /var/www/html/cacti/rra/archive!
DEBUG: Delete from data_source_purge_action: <path_rra>/49/16/902.rrd
DEBUG: Removing Data Source: 902
DEBUG: RRDClean has finished a purge pass of 2 items
DEBUG: Grabbing 1000 RRDfiles to Remove
2024-10-30 12:40:19 - SYSTEM RRDMAINT STATS: Time:0.0501 Purged:0 Archived:0
DEBUG: Checking for Account / Password expiration
```

Fixed now like this:

```sh
[root@vmhost5 cacti]# php -q poller_maintenance.php --debug
DEBUG: Checking for Purge Actions
DEBUG: Purging Required - Files Found 2
DEBUG: Grabbing 1000 RRDfiles to Remove
DEBUG: RRDClean is now running on 2 items
DEBUG: Moved: /var/www/html/cacti/rra/69/16/1544.rrd to: /var/www/html/cacti/rra/archive//69/16/1544.rrd
DEBUG: Delete from data_source_purge_action: <path_rra>/69/16/1544.rrd
DEBUG: Removing Data Source: 1544
DEBUG: Moved: /var/www/html/cacti/rra/70/16/1541.rrd to: /var/www/html/cacti/rra/archive//70/16/1541.rrd
DEBUG: Delete from data_source_purge_action: <path_rra>/70/16/1541.rrd
DEBUG: Removing Data Source: 1541
DEBUG: RRDClean has finished a purge pass of 2 items
DEBUG: Grabbing 1000 RRDfiles to Remove
2024-10-30 12:43:38 - SYSTEM RRDMAINT STATS: Time:0.0468 Purged:0 Archived:2
DEBUG: Checking for Account / Password expiration
```

**Comment by morganfw** [comment]
Hi @TheWitness,
grabbed the latest commit and fix tested by remove a graph from GUI, at the next poller run no errors in log and RRDMAINT STATS log reports that 1 Graph was purged:

`2024-11-04 09:21:10 - SYSTEM RRDMAINT STATS: Time:0.0404 Purged:1 Archived:0`

Thank you for the support.
Regards

**Comment by TheWitness** [comment]
Great!!
