### ISSUE TITLE
[1.3]  - errors when clicking treeview or preview mode 

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/cacti#6013]
```
<html><body>
<!--StartFragment-->
2024-12-24 10:05:30 - PHP ERROR Backtrace:  (CactiShutdownHandler())
--
2024-12-24 10:05:30 - ERROR PHP ERROR: Uncaught DivisionByZeroError:  Division by zero in /var/www/html/cacti/lib/html_utility.php:1495 Stack  trace: #0 /var/www/html/cacti/lib/html.php(606): get_page_list() #1  /var/www/html/cacti/lib/html_graph.php(893): html_nav_bar() #2  /var/www/html/cacti/graph_view.php(82): html_graph_preview_view() #3  {main} thrown in file: /var/www/html/cacti/lib/html_utility.php on line:  1495
2024-12-24 10:05:30 - SQL Backtrace:   (/graph_view.php[82]:html_graph_preview_view(),  /lib/html_graph.php[891]:get_allowed_graphs(),  /lib/auth.php[1534]:db_fetch_assoc(),  /lib/database.php[885]:db_fetch_assoc_prepared(),  /lib/database.php[909]:db_execute_prepared())
2024-12-24 10:05:30 - CMDPHP ERROR: A DB Row Failed!, Error: You  have an error in your SQL syntax; check the manual that corresponds to  your MariaDB server version for the right syntax to use near '' at line 1
2024-12-24 10:05:26 - PHP ERROR Backtrace:  (CactiShutdownHandler())
2024-12-24 10:05:26 - ERROR PHP ERROR: Uncaught DivisionByZeroError:  Division by zero in /var/www/html/cacti/lib/html_utility.php:1495 Stack  trace: #0 /var/www/html/cacti/lib/html.php(606): get_page_list() #1  /var/www/html/cacti/lib/html_graph.php(893): html_nav_bar() #2  /var/www/html/cacti/graph_view.php(82): html_graph_preview_view() #3  {main} thrown in file: /var/www/html/cacti/lib/html_utility.php on line:  1495
2024-12-24 10:05:26 - SQL Backtrace:   (/graph_view.php[82]:html_graph_preview_view(),  /lib/html_graph.php[891]:get_allowed_graphs(),  /lib/auth.php[1534]:db_fetch_assoc(),  /lib/database.php[885]:db_fetch_assoc_prepared(),  /lib/database.php[909]:db_execute_prepared())
2024-12-24 10:05:26 - CMDPHP ERROR: A DB Row Failed!, Error: You  have an error in your SQL syntax; check the manual that corresponds to  your MariaDB server version for the right syntax to use near '' at line 1

<!--EndFragment-->
</body>
</html>
```

**Comment by TheWitness** [comment]
Can you update your install?  I think this was fixed last night.  I can not reproduce it this morning.

**Comment by TheWitness** [comment]
Okay, found it.

**Comment by bmfmancini** [comment]
Still seeing an issue
I am on commit commit de4ae06be2d0a3cfdddc27c6ba942a8fa7c6e655 

```
2024-12-27 10:00:45 - PHP ERROR Backtrace:  (CactiShutdownHandler())
--
2024-12-27 10:00:45 - ERROR PHP ERROR: Uncaught DivisionByZeroError:  Division by zero in /var/www/html/cacti/lib/html_utility.php:1495 Stack  trace: #0 /var/www/html/cacti/lib/html.php(606): get_page_list() #1  /var/www/html/cacti/lib/html_graph.php(893): html_nav_bar() #2  /var/www/html/cacti/graph_view.php(82): html_graph_preview_view() #3  {main} thrown in file: /var/www/html/cacti/lib/html_utility.php on line:  1495
2024-12-27 10:00:45 - SQL Backtrace:   (/graph_view.php[82]:html_graph_preview_view(),  /lib/html_graph.php[891]:get_allowed_graphs(),  /lib/auth.php[1534]:db_fetch_assoc(),  /lib/database.php[885]:db_fetch_assoc_prepared(),  /lib/database.php[909]:db_execute_prepared())
2024-12-27 10:00:45 - CMDPHP ERROR: A DB Row Failed!, Error: You  have an error in your SQL syntax; check the manual that corresponds to  your MariaDB server version for the right syntax to use near '' at line 1
2024-12-27 10:00:38 - PHP ERROR Backtrace:  (CactiShutdownHandler())
2024-12-27 10:00:38 - ERROR PHP ERROR: Uncaught DivisionByZeroError:  Division by zero in /var/www/html/cacti/lib/html_utility.php:1495 Stack  trace: #0 /var/www/html/cacti/lib/html.php(606): get_page_list() #1  /var/www/html/cacti/lib/html_tree.php(1543): html_nav_bar() #2  /var/www/html/cacti/lib/html_tree.php(2071): grow_right_pane_tree() #3  /var/www/html/cacti/graph_view.php(78): html_tree_get_content() #4  {main} thrown in file: /var/www/html/cacti/lib/html_utility.php on line:  1495
```

**Comment by TheWitness** [comment]
Run this query:

```sql
select * from settings_user where name = 'preview_graph_per_page' AND user_id = ?;
```

Let me know the output.

**Comment by TheWitness** [comment]
I'm pretty sure it's fixed now.

**Comment by bmfmancini** [comment]
SQL error is fixed but still seeing a divsion by zero

**Comment by bmfmancini** [comment]
```
2024-12-27 12:35:05 - PHP ERROR Backtrace:  (CactiShutdownHandler())
--
2024-12-27 12:35:05 - ERROR PHP ERROR: Uncaught DivisionByZeroError:  Division by zero in /var/www/html/cacti/lib/html_utility.php:1495 Stack  trace: #0 /var/www/html/cacti/lib/html.php(606): get_page_list() #1  /var/www/html/cacti/lib/html_tree.php(1543): html_nav_bar() #2  /var/www/html/cacti/lib/html_tree.php(2071): grow_right_pane_tree() #3  /var/www/html/cacti/graph_view.php(79): html_tree_get_content() #4  {main} thrown in file: /var/www/html/cacti/lib/html_utility.php on line:  1495
2024-12-27 12:35:04 - WEBUI NOTE: Cacti Log file /var/www/html/cacti/log/cacti.log, Removed by user admin
2024-12-27 12:35:04 - WEBUI NOTE: Cacti Log Cleared from Web Management Interface.
```

**Comment by seanmancini** [comment]
confirmed this is working now

**Comment by bmfmancini** [comment]
confirmed this is working now
