### ISSUE TITLE
[develop] api_scheduler errors in logs every polling cycle

### ISSUE THREAD

**Issue by dallenk** [Cacti/cacti#6039]
# Describe the bug

Not sure if this is acutally causing issues, I see it in the logs every polling cycle.
## To Reproduce

view logs, every cycle I see this one.

```
2025-01-03 09:09:13 - PHP ERROR WARNING Backtrace: (/poller_reports.php[164]:api_scheduler_is_time_to_start(), /lib/api_scheduler.php[391]:CactiErrorHandler())
2025-01-03 09:09:13 - ERROR PHP WARNING: Undefined array key "sched_type" in file: /var/www/html/cacti/lib/api_scheduler.php on line: 391
2025-01-03 09:09:13 - PHP ERROR WARNING Backtrace: (/poller_reports.php[164]:api_scheduler_is_time_to_start(), /lib/api_scheduler.php[391]:CactiErrorHandler())
2025-01-03 09:09:13 - ERROR PHP WARNING: Undefined array key "sched_type" in file: /var/www/html/cacti/lib/api_scheduler.php on line: 391
2025-01-03 09:09:13 - PHP ERROR WARNING Backtrace: (/poller_reports.php[164]:api_scheduler_is_time_to_start(), /lib/api_scheduler.php[391]:CactiErrorHandler())
2025-01-03 09:09:13 - ERROR PHP WARNING: Undefined array key "sched_type" in file: /var/www/html/cacti/lib/api_scheduler.php on line: 391
```

**Comment by TheWitness** [comment]
This was resolved already.  Avoid using reports till after the weekend.  More changes coming.  Almost there though.

**Comment by dallenk** [comment]
OK cool sorry!   I held off reporting it for a few days since I know your working on things currently.    I need to slow down on some reports that are clearly just in-between keyboard time for you.  :)

**Comment by dallenk** [comment]
sorry to do this again.  I still see these errors in my logs every polling cycle.  should they be cleared in this commit?
f09d5b2a6 (HEAD -> develop, origin/develop, origin/HEAD, v1.3) PHPstorm committed empty files.

```
2025-01-09 09:28:10 - PHP ERROR WARNING Backtrace: (/poller_reports.php[164]:api_scheduler_is_time_to_start(), /lib/api_scheduler.php[391]:CactiErrorHandler())
2025-01-09 09:28:10 - ERROR PHP WARNING: Undefined array key "sched_type" in file: /var/www/html/cacti/lib/api_scheduler.php on line: 391
2025-01-09 09:28:10 - PHP ERROR WARNING Backtrace: (/poller_reports.php[164]:api_scheduler_is_time_to_start(), /lib/api_scheduler.php[391]:CactiErrorHandler())
2025-01-09 09:28:10 - ERROR PHP WARNING: Undefined array key "sched_type" in file: /var/www/html/cacti/lib/api_scheduler.php on line: 391
2025-01-09 09:28:10 - PHP ERROR WARNING Backtrace: (/poller_reports.php[164]:api_scheduler_is_time_to_start(), /lib/api_scheduler.php[391]:CactiErrorHandler())
2025-01-09 09:28:10 - ERROR PHP WARNING: Undefined array key "sched_type" in file: /var/www/html/cacti/lib/api_scheduler.php on line: 391
```

**Comment by TheWitness** [comment]
```sh
cd /var/www/html/cacti/cli
php -q upgrade_database.php --forcever=1.2.29
```

**Comment by TheWitness** [comment]
Then do a full browser refresh (F5).
