### ISSUE TITLE
Remove Spikes feature spits out Backtraces when run

### ISSUE THREAD

**Issue by reubenfarrelly** [Cacti/cacti#605]
This one is also pretty easy to reproduce for me.  If I have an existing graph in Graphs -> Device: switch-1 -> and then I click on "Kill Spikes" -> "Dry Run StdDev" then I get a nasty flurry of backtraces like this logged:

2017-04-23 20:39:18 - SPIKEKILL CactiUser:reuben, File:95.rrd, Method:StdDev, StdDevs:10, AvgNan:last, Kills:5, Outliers:5
2017-04-23 20:39:19 - ERROR PHP WARNING: A non-numeric value encountered in file: /var/www/cacti.reub.net/htdocs/cli/removespikes.php  on line: 889
2017-04-23 20:39:19 - CMDPHP PHP ERROR WARNING Backtrace: (/cli/removespikes.php: 641 calculateOverallStatistics)(/cli/removespikes.php: 889 CactiErrorHandler)(/lib/functions.php: 4298 cacti_debug_backtrace)
2017-04-23 20:39:19 - ERROR PHP WARNING: A non-numeric value encountered in file: /var/www/cacti.reub.net/htdocs/cli/removespikes.php  on line: 889
2017-04-23 20:39:19 - CMDPHP PHP ERROR WARNING Backtrace: (/cli/removespikes.php: 641 calculateOverallStatistics)(/cli/removespikes.php: 889 CactiErrorHandler)(/lib/functions.php: 4298 cacti_debug_backtrace)
2017-04-23 20:39:19 - ERROR PHP WARNING: A non-numeric value encountered in file: /var/www/cacti.reub.net/htdocs/cli/removespikes.php  on line: 889
2017-04-23 20:39:19 - CMDPHP PHP ERROR WARNING Backtrace: (/cli/removespikes.php: 641 calculateOverallStatistics)(/cli/removespikes.php: 889 CactiErrorHandler)(/lib/functions.php: 4298 cacti_debug_backtrace)
2017-04-23 20:39:19 - ERROR PHP WARNING: A non-numeric value encountered in file: /var/www/cacti.reub.net/htdocs/cli/removespikes.php  on line: 889
2017-04-23 20:39:19 - CMDPHP PHP ERROR WARNING Backtrace: (/cli/removespikes.php: 641 calculateOverallStatistics)(/cli/removespikes.php: 889 CactiErrorHandler)(/lib/functions.php: 4298 cacti_debug_backtrace)
2017-04-23 20:39:19 - ERROR PHP WARNING: A non-numeric value encountered in file: /var/www/cacti.reub.net/htdocs/cli/removespikes.php  on line: 889
2017-04-23 20:39:19 - CMDPHP PHP ERROR WARNING Backtrace: (/cli/removespikes.php: 641 calculateOverallStatistics)(/cli/removespikes.php: 889 CactiErrorHandler)(/lib/functions.php: 4298 cacti_debug_backtrace)
2017-04-23 20:39:19 - ERROR PHP WARNING: A non-numeric value encountered in file: /var/www/cacti.reub.net/htdocs/cli/removespikes.php  on line: 889
2017-04-23 20:39:19 - CMDPHP PHP ERROR WARNING Backtrace: (/cli/removespikes.php: 641 calculateOverallStatistics)(/cli/removespikes.php: 889 CactiErrorHandler)(/lib/functions.php: 4298 cacti_debug_backtrace)
2017-04-23 20:39:19 - ERROR PHP WARNING: A non-numeric value encountered in file: /var/www/cacti.reub.net/htdocs/cli/removespikes.php  on line: 889
2017-04-23 20:39:19 - CMDPHP PHP ERROR WARNING Backtrace: (/cli/removespikes.php: 641 calculateOverallStatistics)(/cli/removespikes.php: 889 CactiErrorHandler)(/lib/functions.php: 4298 cacti_debug_backtrace)
2017-04-23 20:39:19 - ERROR PHP WARNING: A non-numeric value encountered in file: /var/www/cacti.reub.net/htdocs/cli/removespikes.php  on line: 889
2017-04-23 20:39:19 - CMDPHP PHP ERROR WARNING Backtrace: (/cli/removespikes.php: 641 calculateOverallStatistics)(/cli/removespikes.php: 889 CactiErrorHandler)(/lib/functions.php: 4298 cacti_debug_backtrace)
2017-04-23 20:39:19 - ERROR PHP WARNING: A non-numeric value encountered in file: /var/www/cacti.reub.net/htdocs/cli/removespikes.php  on line: 889
2017-04-23 20:39:19 - CMDPHP PHP ERROR WARNING Backtrace: (/cli/removespikes.php: 641 calculateOverallStatistics)(/cli/removespikes.php: 889 CactiErrorHandler)(/lib/functions.php: 4298 cacti_debug_backtrace)
2017-04-23 20:39:19 - ERROR PHP WARNING: A non-numeric value encountered in file: /var/www/cacti.reub.net/htdocs/cli/removespikes.php  on line: 889

The table does come up with the data after some time though.

**Comment by cigamit** [comment]
Please let me know what version of RRDtool you are using.  And please upload an rrdtool dump of one of the problematic RRDfiles.

**Comment by cigamit** [comment]
I committed a fix to stop the warnings, but I need to see one of these outputs to insure that nothing in the output changed.

**Comment by reubenfarrelly** [comment]
thunderstorm rra # rrdtool --version
RRDtool 1.6.01.6.0  Copyright by Tobias Oetiker <tobi@oetiker.ch>
               Compiled Apr 25 2016 18:47:15

[95.rrd.gz](https://github.com/Cacti/cacti/files/949635/95.rrd.gz)

It appears that the actual spikes aren't being removed either even if I do a normal (not a dry) run.

**Comment by reubenfarrelly** [comment]
Thanks  - that has quietened down the warnings.

Output now:

2017-04-23 21:13:15 - SPIKEKILL CactiUser:reuben, File:95.rrd, Method:StdDev, StdDevs:10, AvgNan:last, Kills:5, Outliers:5

Still doesn't seem to be killing the spikes though as the graph still has a few massive 240P values showing up which should have been removed.

**Comment by cigamit** [comment]
It has to be the rrdtool output.  This might take a little while to fix.  You might want to consider downgrading RRDtool in the mean time.

**Comment by cigamit** [comment]
Can you upload the output of 'rrdtool dump 95.rrd' please.

**Comment by reubenfarrelly** [comment]
Sure.  Here you go:

[95-rrd.xml.gz](https://github.com/Cacti/cacti/files/949710/95-rrd.xml.gz)

**Comment by cigamit** [comment]
There are differences in the old and new file formats.  This might take a while, but it's likely simpler than I though.

**Comment by cigamit** [comment]
I did not see anything interesting in the output.  But there was an update for range file and gap fill.  Can you update and then run from the command line using --debug and --dryrun options and let me know the output.

**Comment by reubenfarrelly** [comment]
Sure:

thunderstorm cli # php removespikes.php --rrdfile=../95.rrd --method=variance --avgnan=last --dryrun --debug
DEBUG: Var Kill: Value '5.0728e+15', VarianceDev '3.4913e+5', VarianceLimit '3.4948e+8'
DEBUG: Var Kill: Value '5.1754e+15', VarianceDev '3.4913e+5', VarianceLimit '3.4948e+8'
DEBUG: Var Kill: Value '5.0728e+15', VarianceDev '2.6376e+4', VarianceLimit '2.6402e+7'
DEBUG: Var Kill: Value '5.1754e+15', VarianceDev '2.6376e+4', VarianceLimit '2.6402e+7'
DEBUG: Var Kill: Value '2.5620e+15', VarianceDev '3.5778e+5', VarianceLimit '3.5813e+8'
DEBUG: Var Kill: Value '2.5620e+15', VarianceDev '3.5778e+5', VarianceLimit '3.5813e+8'
DEBUG: Var Kill: Value '2.5620e+15', VarianceDev '2.8007e+4', VarianceLimit '2.8035e+7'
DEBUG: Var Kill: Value '2.5620e+15', VarianceDev '2.8007e+4', VarianceLimit '2.8035e+7'
DEBUG: Var Kill: Value '1.0782e+14', VarianceDev '2.2470e+5', VarianceLimit '2.2493e+8'
DEBUG: Var Kill: Value '2.1350e+14', VarianceDev '2.2470e+5', VarianceLimit '2.2493e+8'
DEBUG: Var Kill: Value '2.1805e+14', VarianceDev '2.2470e+5', VarianceLimit '2.2493e+8'
DEBUG: Var Kill: Value '1.0782e+14', VarianceDev '1.3865e+4', VarianceLimit '1.3879e+7'
DEBUG: Var Kill: Value '2.1350e+14', VarianceDev '1.3865e+4', VarianceLimit '1.3879e+7'
DEBUG: Var Kill: Value '2.1805e+14', VarianceDev '1.3865e+4', VarianceLimit '1.3879e+7'
DEBUG: Var Kill: Value '3.0437e+16', VarianceDev '5.0124e+5', VarianceLimit '5.0174e+8'
DEBUG: Var Kill: Value '3.0437e+16', VarianceDev '5.0124e+5', VarianceLimit '5.0174e+8'
DEBUG: Var Kill: Value '3.0437e+16', VarianceDev '5.0631e+4', VarianceLimit '5.0681e+7'
DEBUG: Var Kill: Value '3.0437e+16', VarianceDev '5.0631e+4', VarianceLimit '5.0681e+7'
DEBUG: Var Kill: Value '3.0437e+16', VarianceDev '7.7671e+5', VarianceLimit '7.7749e+8'
DEBUG: Var Kill: Value '3.0437e+16', VarianceDev '7.7671e+5', VarianceLimit '7.7749e+8'
DEBUG: Var Kill: Value '3.0437e+16', VarianceDev '8.5682e+4', VarianceLimit '8.5768e+7'
DEBUG: Var Kill: Value '3.0437e+16', VarianceDev '8.5682e+4', VarianceLimit '8.5768e+7'
DEBUG: Var Kill: Value '3.0437e+16', VarianceDev '1.0518e+6', VarianceLimit '1.0528e+9'
DEBUG: Var Kill: Value '3.0437e+16', VarianceDev '1.0518e+6', VarianceLimit '1.0528e+9'
DEBUG: Var Kill: Value '3.0437e+16', VarianceDev '1.0518e+6', VarianceLimit '1.0528e+9'
DEBUG: Var Kill: Value '3.0437e+16', VarianceDev '1.2977e+5', VarianceLimit '1.2990e+8'
DEBUG: Var Kill: Value '3.0437e+16', VarianceDev '1.2977e+5', VarianceLimit '1.2990e+8'
DEBUG: Var Kill: Value '3.0437e+16', VarianceDev '1.2977e+5', VarianceLimit '1.2990e+8'
DEBUG: Var Kill: Value '3.0437e+16', VarianceDev '3.4467e+5', VarianceLimit '3.4501e+8'
DEBUG: Var Kill: Value '3.0437e+16', VarianceDev '2.3986e+4', VarianceLimit '2.4010e+7'
NOTE: Creating XML file '/tmp/95.dump.1659861774' from '../95.rrd'
NOTE: Searching for Spikes in XML file '/tmp/95.dump.1659861774'

      Size       DataSource         CF Samples  NonNan        Avg     StdDev   MaxValue   MinValue  MaxStdDev  MinStdDev  StdKilled  VarKilled WindFilled  StdDevAvg     VarAvg
----------  --------------- ---------- ------- ------- ---------- ---------- ---------- ---------- ---------- ---------- ---------- ---------- ---------- ----------
    5 mins       traffic_in    AVERAGE     500     500  418195.73  294382.45  2.0468e+6   19078.35          0          0          0          0          0  418195.73  398488.86 
    5 mins      traffic_out    AVERAGE     500     500   31038.08    63756.6  1.0620e+6     7888.1          0          0          0          0          0   31038.08   24060.55 
    5 mins       traffic_in    AVERAGE     600     600  456613.42  290911.02  2.0468e+6   19078.35          0          0          0          0          0  456613.42  440845.23 
    5 mins      traffic_out    AVERAGE     600     600    29384.7   58513.23  1.0620e+6     7888.1          0          0          0          0          0    29384.7   23561.78 
   30 mins       traffic_in    AVERAGE     700     691 1.4831e+13 2.7352e+14 5.1754e+15   28702.01          0          0          0          2          0 14830956874846  349126.63 
   30 mins      traffic_out    AVERAGE     700     691 1.4831e+13 2.7352e+14 5.1754e+15    8152.18          0          0          0          2          0 14830956812834    26375.6 
   2 hours       traffic_in    AVERAGE     775     770 6.6547e+12 1.2998e+14 2.5620e+15   24700.58          0          0          0          2          0 6654669866071  357775.45 
   2 hours      traffic_out    AVERAGE     775     770 6.6547e+12 1.2998e+14 2.5620e+15    7452.68          0          0          0          2          0 6654669602056.4   28007.08 
    1 days       traffic_in    AVERAGE     797     797 6.7675e+11 1.1444e+13 2.1805e+14   60454.61          0          0          0          3          0 676750673128.12  224701.98 
    1 days      traffic_out    AVERAGE     797     797 6.7675e+11 1.1444e+13 2.1805e+14    1472.92          0          0          0          3          0 676750469926.9   13864.86 
    5 mins       traffic_in        MIN     600     600  456613.42  290911.02  2.0468e+6   19078.35          0          0          0          0          0  456613.42  440845.23 
    5 mins      traffic_out        MIN     600     600    29384.7   58513.23  1.0620e+6     7888.1          0          0          0          0          0    29384.7   23561.78 
   30 mins       traffic_in        MIN     700     693  268648.75  271949.27  1.3008e+6    1809.51          0          0          0          0          0  268648.75  256810.04 
   30 mins      traffic_out        MIN     700     693   15016.59    17445.5  434922.77    1302.77          0          0          0          0          0   15016.59   13985.99 
   2 hours       traffic_in        MIN     775     772  114621.86  173898.22  767667.01     432.01          0          0          0          0          0  114621.86  108099.82 
   2 hours      traffic_out        MIN     775     772   11326.55   10593.73   169120.6      478.9          0          0          0          0          0   11326.55      10538 
    1 days       traffic_in        MIN     797     797    6619.92    5216.27   44938.92          0          0          0          0          0          0    6619.92    6370.25 
    1 days      traffic_out        MIN     797     797    2987.63    2180.08   12142.17          0          0          0          0          0          0    2987.63       2909 
    5 mins       traffic_in        MAX     500     500  418195.73  294382.45  2.0468e+6   19078.35          0          0          0          0          0  418195.73  398488.86 
    5 mins      traffic_out        MAX     500     500   31038.08    63756.6  1.0620e+6     7888.1          0          0          0          0          0   31038.08   24060.55 
    5 mins       traffic_in        MAX     600     600  456613.42  290911.02  2.0468e+6   19078.35          0          0          0          0          0  456613.42  440845.23 
    5 mins      traffic_out        MAX     600     600    29384.7   58513.23  1.0620e+6     7888.1          0          0          0          0          0    29384.7   23561.78 
   30 mins       traffic_in        MAX     700     691 8.8094e+13 1.6246e+15 3.0437e+16   41279.87          0          0          0          2          0 88094396655000  501241.57 
   30 mins      traffic_out        MAX     700     691 8.8094e+13 1.6246e+15 3.0437e+16     8630.5          0          0          0          2          0 88094397775461    50630.8 
   2 hours       traffic_in        MAX     775     770 7.9057e+13 1.5442e+15 3.0437e+16    50666.1          0          0          0          2          0 79056807922987  776708.43 
   2 hours      traffic_out        MAX     775     770 7.9057e+13 1.5442e+15 3.0437e+16    9793.31          0          0          0          2          0 79056808036478   85682.48 
    1 days       traffic_in        MAX     797     797 1.1457e+14 1.8639e+15 3.0437e+16  281144.64          0          0          0          3          0 1.1456821700816E+14  1.0518e+6 
    1 days      traffic_out        MAX     797     797 1.1457e+14 1.8639e+15 3.0437e+16    5477.98          0          0          0          3          0 1.1456821818784E+14  129766.76 
    5 mins       traffic_in       LAST     600     600  456613.42  290911.02  2.0468e+6   19078.35          0          0          0          0          0  456613.42  440845.23 
    5 mins      traffic_out       LAST     600     600    29384.7   58513.23  1.0620e+6     7888.1          0          0          0          0          0    29384.7   23561.78 
   30 mins       traffic_in       LAST     700     687 4.4304e+13 1.1496e+15 3.0437e+16   15735.27          0          0          0          1          0 44303659541607  344666.58 
   30 mins      traffic_out       LAST     700     687 4.4304e+13 1.1496e+15 3.0437e+16    7430.13          0          0          0          1          0 44303660016537   23985.77 
   2 hours       traffic_in       LAST     775     766  335830.04  460671.32  7.2831e+6   11021.72          0          0          0          0          0  335830.04  303131.27 
   2 hours      traffic_out       LAST     775     766   26726.32   30789.14  434922.77    6577.51          0          0          0          0          0   26726.32   24218.29 
    1 days       traffic_in       LAST     797     793  261824.19  257463.44  4.8600e+6     254.38          0          0          0          0          0  261824.19  245577.99 
    1 days      traffic_out       LAST     797     793   18155.53  118089.22  3.3052e+6     414.28          0          0          0          0          0   18155.53   12467.57 

NOTE: Dryrun requested.  No updates performed
thunderstorm cli #

**Comment by cigamit** [comment]
Looks like it's working then.

**Comment by reubenfarrelly** [comment]
There's still something wrong here.  I have run the command multiple times and the large spikes aren't being removed from the graph.

The debug output from one time to the next seems to indicate that the same analysis is being done and the spike values aren't actually being removed from the RRD at all:

First run:

apache@thunderstorm ~/cacti.reub.net/htdocs/cli $ php removespikes.php --rrdfile=../rra/8/95.rrd --avgnan=last --method=variance --debug
DEBUG: Var Kill: Value '5.0728e+15', VarianceDev '3.5157e+5', VarianceLimit '3.5192e+8'
DEBUG: Var Kill: Value '5.1754e+15', VarianceDev '3.5157e+5', VarianceLimit '3.5192e+8'
DEBUG: Var Kill: Value '5.0728e+15', VarianceDev '2.6471e+4', VarianceLimit '2.6497e+7'
DEBUG: Var Kill: Value '5.1754e+15', VarianceDev '2.6471e+4', VarianceLimit '2.6497e+7'
DEBUG: Var Kill: Value '2.5620e+15', VarianceDev '3.5576e+5', VarianceLimit '3.5612e+8'
DEBUG: Var Kill: Value '2.5620e+15', VarianceDev '3.5576e+5', VarianceLimit '3.5612e+8'
DEBUG: Var Kill: Value '2.5620e+15', VarianceDev '2.8033e+4', VarianceLimit '2.8061e+7'
DEBUG: Var Kill: Value '2.5620e+15', VarianceDev '2.8033e+4', VarianceLimit '2.8061e+7'
DEBUG: Var Kill: Value '1.0782e+14', VarianceDev '2.2504e+5', VarianceLimit '2.2526e+8'
DEBUG: Var Kill: Value '2.1350e+14', VarianceDev '2.2504e+5', VarianceLimit '2.2526e+8'
DEBUG: Var Kill: Value '2.1805e+14', VarianceDev '2.2504e+5', VarianceLimit '2.2526e+8'
DEBUG: Var Kill: Value '1.0782e+14', VarianceDev '1.3900e+4', VarianceLimit '1.3913e+7'
DEBUG: Var Kill: Value '2.1350e+14', VarianceDev '1.3900e+4', VarianceLimit '1.3913e+7'
DEBUG: Var Kill: Value '2.1805e+14', VarianceDev '1.3900e+4', VarianceLimit '1.3913e+7'
DEBUG: Var Kill: Value '3.0437e+16', VarianceDev '5.0630e+5', VarianceLimit '5.0681e+8'
DEBUG: Var Kill: Value '3.0437e+16', VarianceDev '5.0630e+5', VarianceLimit '5.0681e+8'
DEBUG: Var Kill: Value '3.0437e+16', VarianceDev '5.1216e+4', VarianceLimit '5.1267e+7'
DEBUG: Var Kill: Value '3.0437e+16', VarianceDev '5.1216e+4', VarianceLimit '5.1267e+7'
DEBUG: Var Kill: Value '3.0437e+16', VarianceDev '7.8249e+5', VarianceLimit '7.8328e+8'
DEBUG: Var Kill: Value '3.0437e+16', VarianceDev '7.8249e+5', VarianceLimit '7.8328e+8'
DEBUG: Var Kill: Value '3.0437e+16', VarianceDev '8.6462e+4', VarianceLimit '8.6548e+7'
DEBUG: Var Kill: Value '3.0437e+16', VarianceDev '8.6462e+4', VarianceLimit '8.6548e+7'
DEBUG: Var Kill: Value '3.0437e+16', VarianceDev '1.0535e+6', VarianceLimit '1.0546e+9'
DEBUG: Var Kill: Value '3.0437e+16', VarianceDev '1.0535e+6', VarianceLimit '1.0546e+9'
DEBUG: Var Kill: Value '3.0437e+16', VarianceDev '1.0535e+6', VarianceLimit '1.0546e+9'
DEBUG: Var Kill: Value '3.0437e+16', VarianceDev '1.3044e+5', VarianceLimit '1.3057e+8'
DEBUG: Var Kill: Value '3.0437e+16', VarianceDev '1.3044e+5', VarianceLimit '1.3057e+8'
DEBUG: Var Kill: Value '3.0437e+16', VarianceDev '1.3044e+5', VarianceLimit '1.3057e+8'
DEBUG: Var Kill: Value '3.0437e+16', VarianceDev '3.4468e+5', VarianceLimit '3.4503e+8'
DEBUG: Var Kill: Value '3.0437e+16', VarianceDev '2.3872e+4', VarianceLimit '2.3895e+7'
NOTE: Creating XML file '/tmp/95.dump.867763013' from '../rra/8/95.rrd'
NOTE: Searching for Spikes in XML file '/tmp/95.dump.867763013'

      Size       DataSource         CF Samples  NonNan        Avg     StdDev   MaxValue   MinValue  MaxStdDev  MinStdDev  StdKilled  VarKilled WindFilled  StdDevAvg     VarAvg
----------  --------------- ---------- ------- ------- ---------- ---------- ---------- ---------- ---------- ---------- ---------- ---------- ---------- ----------
    5 mins       traffic_in    AVERAGE     500     500  361149.69  474854.15  6.8727e+6   17671.73          0          0          0          0          0  361149.69  320820.18 
    5 mins      traffic_out    AVERAGE     500     500   26640.01   45493.27   573589.5    7744.18          0          0          0          0          0   26640.01    21424.8 
    5 mins       traffic_in    AVERAGE     600     600  378556.63  446124.71  6.8727e+6   17671.73          0          0          0          0          0  378556.63  345357.67 
    5 mins      traffic_out    AVERAGE     600     600   25829.96   42998.99   573589.5    7744.18          0          0          0          0          0   25829.96   21261.78 
   30 mins       traffic_in    AVERAGE     700     692 1.4810e+13 2.7352e+14 5.1754e+15   28832.37          0          0          0          2          0 14809524861215  351565.01 
   30 mins      traffic_out    AVERAGE     700     691 1.4831e+13 2.7352e+14 5.1754e+15    8187.39          0          0          0          2          0 14830956812927   26470.76 
   2 hours       traffic_in    AVERAGE     775     772 6.6374e+12 1.2998e+14 2.5620e+15   24700.58          0          0          0          2          0 6637429787635.4  355760.09 
   2 hours      traffic_out    AVERAGE     775     771 6.6460e+12 1.2998e+14 2.5620e+15    7452.68          0          0          0          2          0 6646038383438.4   28032.81 
    1 days       traffic_in    AVERAGE     797     797 6.7675e+11 1.1444e+13 2.1805e+14   60454.61          0          0          0          3          0 676750673457.63  225035.67 
    1 days      traffic_out    AVERAGE     797     797 6.7675e+11 1.1444e+13 2.1805e+14    1472.92          0          0          0          3          0 676750469961.2   13899.59 
    5 mins       traffic_in        MIN     600     600  378556.63  446124.71  6.8727e+6   17671.73          0          0          0          0          0  378556.63  345357.67 
    5 mins      traffic_out        MIN     600     600   25829.96   42998.99   573589.5    7744.18          0          0          0          0          0   25829.96   21261.78 
   30 mins       traffic_in        MIN     700     696  268368.29  269547.34  1.3008e+6    1809.51          0          0          0          0          0  268368.29  256577.26 
   30 mins      traffic_out        MIN     700     695   15015.66    17400.4  434922.77    1302.77          0          0          0          0          0   15015.66   13988.06 
   2 hours       traffic_in        MIN     775     775  113826.21   173373.1  767667.01     432.01          0          0          0          0          0  113826.21  107319.35 
   2 hours      traffic_out        MIN     775     774   11316.96   10575.03   169120.6      478.9          0          0          0          0          0   11316.96   10530.35 
    1 days       traffic_in        MIN     797     797    6643.54    5229.99   44938.92          0          0          0          0          0          0    6643.54    6394.17 
    1 days      traffic_out        MIN     797     797    2997.02    2185.03   12142.17          0          0          0          0          0          0    2997.02    2918.52 
    5 mins       traffic_in        MAX     500     500  361149.69  474854.15  6.8727e+6   17671.73          0          0          0          0          0  361149.69  320820.18 
    5 mins      traffic_out        MAX     500     500   26640.01   45493.27   573589.5    7744.18          0          0          0          0          0   26640.01    21424.8 
    5 mins       traffic_in        MAX     600     600  378556.63  446124.71  6.8727e+6   17671.73          0          0          0          0          0  378556.63  345357.67 
    5 mins      traffic_out        MAX     600     600   25829.96   42998.99   573589.5    7744.18          0          0          0          0          0   25829.96   21261.78 
   30 mins       traffic_in        MAX     700     692 8.7967e+13 1.6246e+15 3.0437e+16   41279.87          0          0          0          2          0 87967092625341  506302.64 
   30 mins      traffic_out        MAX     700     691 8.8094e+13 1.6246e+15 3.0437e+16     8630.5          0          0          0          2          0 88094397776121    51216.1 
   2 hours       traffic_in        MAX     775     772 7.8852e+13 1.5442e+15 3.0437e+16    50666.1          0          0          0          2          0 78851997547817  782493.56 
   2 hours      traffic_out        MAX     775     771 7.8954e+13 1.5442e+15 3.0437e+16    9793.31          0          0          0          2          0 78954270024340   86461.69 
    1 days       traffic_in        MAX     797     797 1.1457e+14 1.8639e+15 3.0437e+16  281144.64          0          0          0          3          0 1.1456821700986E+14  1.0535e+6 
    1 days      traffic_out        MAX     797     797 1.1457e+14 1.8639e+15 3.0437e+16    5477.98          0          0          0          3          0 1.1456821818851E+14  130443.95 
    5 mins       traffic_in       LAST     600     600  378556.63  446124.71  6.8727e+6   17671.73          0          0          0          0          0  378556.63  345357.67 
    5 mins      traffic_out       LAST     600     600   25829.96   42998.99   573589.5    7744.18          0          0          0          0          0   25829.96   21261.78 
   30 mins       traffic_in       LAST     700     690 4.4111e+13 1.1496e+15 3.0437e+16   15735.27          0          0          0          1          0 44111034936421  344684.02 
   30 mins      traffic_out       LAST     700     689 4.4175e+13 1.1496e+15 3.0437e+16    7430.13          0          0          0          1          0 44175057229799   23871.55 
   2 hours       traffic_in       LAST     775     769  334055.92  460326.35  7.2831e+6   11021.72          0          0          0          0          0  334055.92  301463.02 
   2 hours      traffic_out       LAST     775     768   26725.28   30821.67  434922.77    6577.51          0          0          0          0          0   26725.28   24223.85 
    1 days       traffic_in       LAST     797     796   261803.2  256965.67  4.8600e+6     254.38          0          0          0          0          0   261803.2  245618.74 
    1 days      traffic_out       LAST     797     795    18242.2   118100.9  3.3052e+6     414.28          0          0          0          0          0    18242.2   12569.84 

NOTE: Backing Up '../rra/8/95.rrd' to '/var/www/cacti.reub.net/htdocs/cache/spikekill//95.rrd.867763013'
NOTE: Re-Importing '/tmp/95.dump.867763013' to '../rra/8/95.rrd'
NOTE: Spikes Found and Remediated.  Total Spikes (49)
apache@thunderstorm ~/cacti.reub.net/htdocs/cli $ 

then run again straight away:

apache@thunderstorm ~/cacti.reub.net/htdocs/cli $ php removespikes.php --rrdfile=../rra/8/95.rrd --avgnan=last --method=variance --debug
DEBUG: Var Kill: Value '5.0728e+15', VarianceDev '3.5157e+5', VarianceLimit '3.5192e+8'
DEBUG: Var Kill: Value '5.1754e+15', VarianceDev '3.5157e+5', VarianceLimit '3.5192e+8'
DEBUG: Var Kill: Value '5.0728e+15', VarianceDev '2.6493e+4', VarianceLimit '2.6519e+7'
DEBUG: Var Kill: Value '5.1754e+15', VarianceDev '2.6493e+4', VarianceLimit '2.6519e+7'
DEBUG: Var Kill: Value '2.5620e+15', VarianceDev '3.5594e+5', VarianceLimit '3.5630e+8'
DEBUG: Var Kill: Value '2.5620e+15', VarianceDev '3.5594e+5', VarianceLimit '3.5630e+8'
DEBUG: Var Kill: Value '2.5620e+15', VarianceDev '2.8056e+4', VarianceLimit '2.8084e+7'
DEBUG: Var Kill: Value '2.5620e+15', VarianceDev '2.8056e+4', VarianceLimit '2.8084e+7'
DEBUG: Var Kill: Value '1.0782e+14', VarianceDev '2.2504e+5', VarianceLimit '2.2526e+8'
DEBUG: Var Kill: Value '2.1350e+14', VarianceDev '2.2504e+5', VarianceLimit '2.2526e+8'
DEBUG: Var Kill: Value '2.1805e+14', VarianceDev '2.2504e+5', VarianceLimit '2.2526e+8'
DEBUG: Var Kill: Value '1.0782e+14', VarianceDev '1.3900e+4', VarianceLimit '1.3913e+7'
DEBUG: Var Kill: Value '2.1350e+14', VarianceDev '1.3900e+4', VarianceLimit '1.3913e+7'
DEBUG: Var Kill: Value '2.1805e+14', VarianceDev '1.3900e+4', VarianceLimit '1.3913e+7'
DEBUG: Var Kill: Value '3.0437e+16', VarianceDev '5.0630e+5', VarianceLimit '5.0681e+8'
DEBUG: Var Kill: Value '3.0437e+16', VarianceDev '5.0630e+5', VarianceLimit '5.0681e+8'
DEBUG: Var Kill: Value '3.0437e+16', VarianceDev '5.1244e+4', VarianceLimit '5.1295e+7'
DEBUG: Var Kill: Value '3.0437e+16', VarianceDev '5.1244e+4', VarianceLimit '5.1295e+7'
DEBUG: Var Kill: Value '3.0437e+16', VarianceDev '7.8281e+5', VarianceLimit '7.8359e+8'
DEBUG: Var Kill: Value '3.0437e+16', VarianceDev '7.8281e+5', VarianceLimit '7.8359e+8'
DEBUG: Var Kill: Value '3.0437e+16', VarianceDev '8.6501e+4', VarianceLimit '8.6587e+7'
DEBUG: Var Kill: Value '3.0437e+16', VarianceDev '8.6501e+4', VarianceLimit '8.6587e+7'
DEBUG: Var Kill: Value '3.0437e+16', VarianceDev '1.0535e+6', VarianceLimit '1.0546e+9'
DEBUG: Var Kill: Value '3.0437e+16', VarianceDev '1.0535e+6', VarianceLimit '1.0546e+9'
DEBUG: Var Kill: Value '3.0437e+16', VarianceDev '1.0535e+6', VarianceLimit '1.0546e+9'
DEBUG: Var Kill: Value '3.0437e+16', VarianceDev '1.3044e+5', VarianceLimit '1.3057e+8'
DEBUG: Var Kill: Value '3.0437e+16', VarianceDev '1.3044e+5', VarianceLimit '1.3057e+8'
DEBUG: Var Kill: Value '3.0437e+16', VarianceDev '1.3044e+5', VarianceLimit '1.3057e+8'
DEBUG: Var Kill: Value '3.0437e+16', VarianceDev '3.4489e+5', VarianceLimit '3.4523e+8'
DEBUG: Var Kill: Value '3.0437e+16', VarianceDev '2.3985e+4', VarianceLimit '2.4008e+7'
NOTE: Creating XML file '/tmp/95.dump.1255718871' from '../rra/8/95.rrd'
NOTE: Searching for Spikes in XML file '/tmp/95.dump.1255718871'

      Size       DataSource         CF Samples  NonNan        Avg     StdDev   MaxValue   MinValue  MaxStdDev  MinStdDev  StdKilled  VarKilled WindFilled  StdDevAvg     VarAvg
----------  --------------- ---------- ------- ------- ---------- ---------- ---------- ---------- ---------- ---------- ---------- ---------- ---------- ----------
    5 mins       traffic_in    AVERAGE     500     500  361149.69  474854.15  6.8727e+6   17671.73          0          0          0          0          0  361149.69  320820.18 
    5 mins      traffic_out    AVERAGE     500     500   26640.01   45493.27   573589.5    7744.18          0          0          0          0          0   26640.01    21424.8 
    5 mins       traffic_in    AVERAGE     600     600  378556.63  446124.71  6.8727e+6   17671.73          0          0          0          0          0  378556.63  345357.67 
    5 mins      traffic_out    AVERAGE     600     600   25829.96   42998.99   573589.5    7744.18          0          0          0          0          0   25829.96   21261.78 
   30 mins       traffic_in    AVERAGE     700     692 1.4810e+13 2.7352e+14 5.1754e+15   28832.37          0          0          0          2          0 14809524861215  351565.01 
   30 mins      traffic_out    AVERAGE     700     692 1.4810e+13 2.7352e+14 5.1754e+15    8187.39          0          0          0          2          0 14809524794471    26492.6 
   2 hours       traffic_in    AVERAGE     775     773 6.6288e+12 1.2998e+14 2.5620e+15   24700.58          0          0          0          2          0 6628843203816.5  355943.41 
   2 hours      traffic_out    AVERAGE     775     773 6.6288e+12 1.2998e+14 2.5620e+15    7452.68          0          0          0          2          0 6628842941403.4   28056.08 
    1 days       traffic_in    AVERAGE     797     797 6.7675e+11 1.1444e+13 2.1805e+14   60454.61          0          0          0          3          0 676750673457.63  225035.67 
    1 days      traffic_out    AVERAGE     797     797 6.7675e+11 1.1444e+13 2.1805e+14    1472.92          0          0          0          3          0 676750469961.2   13899.59 
    5 mins       traffic_in        MIN     600     600  378556.63  446124.71  6.8727e+6   17671.73          0          0          0          0          0  378556.63  345357.67 
    5 mins      traffic_out        MIN     600     600   25829.96   42998.99   573589.5    7744.18          0          0          0          0          0   25829.96   21261.78 
   30 mins       traffic_in        MIN     700     698  269141.46  269555.89  1.3008e+6    1809.51          0          0          0          0          0  269141.46  257395.94 
   30 mins      traffic_out        MIN     700     698   15024.26   17374.52  434922.77    1302.77          0          0          0          0          0   15024.26   14001.27 
   2 hours       traffic_in        MIN     775     775  113826.21   173373.1  767667.01     432.01          0          0          0          0          0  113826.21  107319.35 
   2 hours      traffic_out        MIN     775     775   11312.75   10567.87   169120.6      478.9          0          0          0          0          0   11312.75    10527.1 
    1 days       traffic_in        MIN     797     797    6643.54    5229.99   44938.92          0          0          0          0          0          0    6643.54    6394.17 
    1 days      traffic_out        MIN     797     797    2997.02    2185.03   12142.17          0          0          0          0          0          0    2997.02    2918.52 
    5 mins       traffic_in        MAX     500     500  361149.69  474854.15  6.8727e+6   17671.73          0          0          0          0          0  361149.69  320820.18 
    5 mins      traffic_out        MAX     500     500   26640.01   45493.27   573589.5    7744.18          0          0          0          0          0   26640.01    21424.8 
    5 mins       traffic_in        MAX     600     600  378556.63  446124.71  6.8727e+6   17671.73          0          0          0          0          0  378556.63  345357.67 
    5 mins      traffic_out        MAX     600     600   25829.96   42998.99   573589.5    7744.18          0          0          0          0          0   25829.96   21261.78 
   30 mins       traffic_in        MAX     700     692 8.7967e+13 1.6246e+15 3.0437e+16   41279.87          0          0          0          2          0 87967092625341  506302.64 
   30 mins      traffic_out        MAX     700     692 8.7967e+13 1.6246e+15 3.0437e+16     8630.5          0          0          0          2          0 87967093733193   51243.79 
   2 hours       traffic_in        MAX     775     773 7.8750e+13 1.5442e+15 3.0437e+16    50666.1          0          0          0          2          0 78749989790344  782806.39 
   2 hours      traffic_out        MAX     775     773 7.8750e+13 1.5442e+15 3.0437e+16    9793.31          0          0          0          2          0 78749989895174   86500.68 
    1 days       traffic_in        MAX     797     797 1.1457e+14 1.8639e+15 3.0437e+16  281144.64          0          0          0          3          0 1.1456821700986E+14  1.0535e+6 
    1 days      traffic_out        MAX     797     797 1.1457e+14 1.8639e+15 3.0437e+16    5477.98          0          0          0          3          0 1.1456821818851E+14  130443.95 
    5 mins       traffic_in       LAST     600     600  378556.63  446124.71  6.8727e+6   17671.73          0          0          0          0          0  378556.63  345357.67 
    5 mins      traffic_out       LAST     600     600   25829.96   42998.99   573589.5    7744.18          0          0          0          0          0   25829.96   21261.78 
   30 mins       traffic_in       LAST     700     691 4.4047e+13 1.1496e+15 3.0437e+16   15735.27          0          0          0          1          0 44047198417675  344887.41 
   30 mins      traffic_out       LAST     700     691 4.4047e+13 1.1496e+15 3.0437e+16    7430.13          0          0          0          1          0 44047198887780   23984.51 
   2 hours       traffic_in       LAST     775     771  333909.74  460212.87  7.2831e+6   11021.72          0          0          0          0          0  333909.74  301400.58 
   2 hours      traffic_out       LAST     775     771   26774.26   30792.89  434922.77    6577.51          0          0          0          0          0   26774.26   24283.35 
    1 days       traffic_in       LAST     797     797  261786.92   256798.9  4.8600e+6     254.38          0          0          0          0          0  261786.92  245622.82 
    1 days      traffic_out       LAST     797     797   18279.82  118099.85  3.3052e+6     414.28          0          0          0          0          0   18279.82   12622.36 

NOTE: Backing Up '../rra/8/95.rrd' to '/var/www/cacti.reub.net/htdocs/cache/spikekill//95.rrd.1255718871'
NOTE: Re-Importing '/tmp/95.dump.1255718871' to '../rra/8/95.rrd'
NOTE: Spikes Found and Remediated.  Total Spikes (44)
apache@thunderstorm ~/cacti.reub.net/htdocs/cli $ 

Note that the Var Kill Values are not changing at all and the spikes are still persistent in the graph (also tried this without the debug flag set and the same problem occurs).

**Comment by cigamit** [comment]
I've got nothing.  I would say verify that the import actuall is working.  My suspicion is that maybe there is some RRDtool or permission issue causing the write of the RRDfile to fail.  Balls in your court as I can not reproduce this.

**Comment by reubenfarrelly** [comment]
I've downgraded RRDtool to 1.5.5 - no change.  The RRD file appears to be being written, based on the timestamp, and there aren't any permission problems as far as I can tell.  The permissions are apache:apache and the same as all of the other RRDs and all are updating normally during the polling cycle.

I'm certain something is wrong, and I can readily demonstrate it.  This after multiple attempts to remove the spikes from the web UI:

![image](https://cloud.githubusercontent.com/assets/8552189/25564376/6f1d8bc2-2df5-11e7-8dd6-396d8861d2df.png)

Note the enormous data value in the middle which is clearly out of place.  No matter if I choose removal based on StdDev or Variance (Variance is really be what I want) this massive spike is not removed either from the graph nor from the data itself.

I don't know if it's relevant or not but this data is a couple of weeks back in time and is far enough back to not be in the "Daily" Data Source Profile Timespan any longer.

Any further advice on what I can provide to get to the bottom of this would be appreciated.

**Comment by cigamit** [comment]
You can always play around with the code yourself.  You can run it from the CLI on a separate version of the file until you have the root cause nailed down.

**Comment by cigamit** [comment]
Paste a screen shot of the dryrun data.  The other posts were unreadable.

**Comment by reubenfarrelly** [comment]
Sure.  Here's the graph before the run:

![image](https://user-images.githubusercontent.com/8552189/27993997-8a0908b0-64f7-11e7-84a4-41074fa2a9d6.png)

Then we run Spikekill from the GUI - just a dry run, and remove variance.  This is logged:

09/Jul/2017 22:38:04 - SPIKEKILL CactiUser:reuben, File:92.rrd, Method:Variance, AvgNan:last, Kills:8, Outliers:8, Percent:1000
09/Jul/2017 22:38:05 - WEBUI WARNING: Removed '11' Spikes from '/var/www/cacti.reub.net/htdocs/rra/8/92.rrd', Method:'2'

So far looks good.

Now we go back to the graph:

![image](https://user-images.githubusercontent.com/8552189/27993999-a0e9f940-64f7-11e7-8fd7-d35ad8cd1a4b.png)

Note that the Maximum value hasn't changed - the graph date has changed but the graph has not.  It still shows the enormous peaks that should have been removed.

Here's the dryrun data:

![image](https://user-images.githubusercontent.com/8552189/27994008-f359c296-64f7-11e7-9e73-f2ba8ed052ed.png)

It looks like the data is being calculated but not being applied back to the original RRD.  I don't believe this to be a permissions issue:

thunderstorm 8 # ls -la 92.rrd 
-rw-r--r-- 1 apache apache 189024 Jul  9 22:40 92.rrd
thunderstorm 8 # 

Apache is running as user apache, and even if it wasn't I imagine the Cacti Log would be showing a permissions error for this operation (it doesn't).

(incidentally it would be great if the SpikeKill Results pane could be expanded to be able to show all of the data, but it seems to be a fixed height which means there is always a need to scroll down)

**Comment by cigamit** [comment]
Well, open a separate issue for the visualization piece.  The original issue is fixed now.  Glad I was able to find it.

**Comment by cigamit** [comment]
I made one minor change after this commit to make the code a little more readable and to correct one logic bug.

**Comment by reubenfarrelly** [comment]
Sorry to say - something is still not right.  Here's the output from the command line that I ran earlier today.  First was a dryrun, then a non dryrun which should have removed the spikes, and then a dryrun again.  It appears that the same spikes are being detected in all three runs.  I was expecting that the spikes in the final run would be different (and less) due to the spikes being killed.

```
apache@thunderstorm ~/cacti.reub.net/htdocs/cli $ php removespikes.php --rrdfile=/var/www/cacti.reub.net/htdocs/rra/8/95.rrd --method=variance --outliers=10 --debug --dryrun
DEBUG: Var Kill: Value '1.0782e+14', VarianceDev '2.3712e+5', VarianceLimit '2.3735e+8'
DEBUG: Var Kill: Value '2.1350e+14', VarianceDev '2.3712e+5', VarianceLimit '2.3735e+8'
DEBUG: Var Kill: Value '2.1805e+14', VarianceDev '2.3712e+5', VarianceLimit '2.3735e+8'
DEBUG: Var Kill: Value '1.0782e+14', VarianceDev '1.5789e+4', VarianceLimit '1.5805e+7'
DEBUG: Var Kill: Value '2.1350e+14', VarianceDev '1.5789e+4', VarianceLimit '1.5805e+7'
DEBUG: Var Kill: Value '2.1805e+14', VarianceDev '1.5789e+4', VarianceLimit '1.5805e+7'
DEBUG: Var Kill: Value '3.0437e+16', VarianceDev '1.1201e+6', VarianceLimit '1.1212e+9'
DEBUG: Var Kill: Value '3.0437e+16', VarianceDev '1.1201e+6', VarianceLimit '1.1212e+9'
DEBUG: Var Kill: Value '3.0437e+16', VarianceDev '1.1201e+6', VarianceLimit '1.1212e+9'
DEBUG: Var Kill: Value '3.0437e+16', VarianceDev '1.4830e+5', VarianceLimit '1.4845e+8'
DEBUG: Var Kill: Value '3.0437e+16', VarianceDev '1.4830e+5', VarianceLimit '1.4845e+8'
DEBUG: Var Kill: Value '3.0437e+16', VarianceDev '1.4830e+5', VarianceLimit '1.4845e+8'
DEBUG: Either variance or out_kills found
NOTE: Creating XML file '/tmp/95.dump.1975273485' from '/var/www/cacti.reub.net/htdocs/rra/8/95.rrd'
NOTE: Searching for Spikes in XML file '/tmp/95.dump.1975273485'

      Size       DataSource         CF Samples  NonNan        Avg     StdDev   MaxValue   MinValue  MaxStdDev  MinStdDev  StdKilled  VarKilled WindFilled  StdDevAvg     VarAvg
----------  --------------- ---------- ------- ------- ---------- ---------- ---------- ---------- ---------- ---------- ---------- ---------- ---------- ---------- ----------
    5 mins       traffic_in    AVERAGE     500     500  333998.68  300211.46  1.3746e+6   14944.05          0          0          0          0          0  333998.68  300348.66
    5 mins      traffic_out    AVERAGE     500     500   26666.15   66431.94  968253.19    4165.33          0          0          0          0          0   26666.15   19403.01
    5 mins       traffic_in    AVERAGE     600     598  335625.79  308694.57  1.3746e+6    1738.79          0          0          0          0          0  335625.79  304748.14
    5 mins      traffic_out    AVERAGE     600     598   27697.92   63750.97  968253.19    1193.15          0          0          0          0          0   27697.92   20702.78
   30 mins       traffic_in    AVERAGE     700     699  294558.54   266256.4  1.5844e+6   19286.43          0          0          0          0          0  294558.54  272509.44
   30 mins      traffic_out    AVERAGE     700     699   30180.45   48338.06  749596.44     4505.8          0          0          0          0          0   30180.45    24161.7
   2 hours       traffic_in    AVERAGE     775     774   317741.7  213505.15  1.4576e+6   27360.83          0          0          0          0          0   317741.7  301675.35
   2 hours      traffic_out    AVERAGE     775     774   36159.79   44730.68  228886.09    5614.73          0          0          0          0          0   36159.79   31800.14
    1 days       traffic_in    AVERAGE     797     797 6.7675e+11 1.1444e+13 2.1805e+14   60454.61          0          0          0          3          0 6.7675e+11  237115.64
    1 days      traffic_out    AVERAGE     797     797 6.7675e+11 1.1444e+13 2.1805e+14    1680.96          0          0          0          3          0 6.7675e+11   15789.49
    5 mins       traffic_in        MIN     600     594  331300.31  302042.64  1.3746e+6    1738.79          0          0          0          0          0  331300.31  301680.43
    5 mins      traffic_out        MIN     600     594   27600.07   63763.91  968253.19    1193.15          0          0          0          0          0   27600.07   20552.77
   30 mins       traffic_in        MIN     700     699  216380.31   243590.6  1.2765e+6    1738.79          0          0          0          0          0  216380.31  197233.96
   30 mins      traffic_out        MIN     700     699   17429.54   40584.11  704824.01    1193.15          0          0          0          0          0   17429.54   11800.12
   2 hours       traffic_in        MIN     775     774   86747.36  135790.15  833708.96      460.5          0          0          0          0          0   86747.36   73630.84
   2 hours      traffic_out        MIN     775     774   13241.94   30338.26  196876.83     481.88          0          0          0          0          0   13241.94     8924.8
    1 days       traffic_in        MIN     797     797    8117.67    6289.43   58166.85          0          0          0          0          0          0    8117.67    7555.97
    1 days      traffic_out        MIN     797     797    3190.95    2129.86   12142.17          0          0          0          0          0          0    3190.95    3050.86
    5 mins       traffic_in        MAX     500     500  333998.68  300211.46  1.3746e+6   14944.05          0          0          0          0          0  333998.68  300348.66
    5 mins      traffic_out        MAX     500     500   26666.15   66431.94  968253.19    4165.33          0          0          0          0          0   26666.15   19403.01
    5 mins       traffic_in        MAX     600     594  331300.31  302042.64  1.3746e+6    1738.79          0          0          0          0          0  331300.31  301680.43
    5 mins      traffic_out        MAX     600     594   27600.07   63763.91  968253.19    1193.15          0          0          0          0          0   27600.07   20552.77
   30 mins       traffic_in        MAX     700     699  440009.51  371534.07  3.5992e+6   27891.57          0          0          0          0          0  440009.51  403698.73
   30 mins      traffic_out        MAX     700     699   54717.07   92649.78  1.1317e+6    5212.83          0          0          0          0          0   54717.07   42779.46
   2 hours       traffic_in        MAX     775     774  758962.97  720155.13  9.1072e+6    47934.8          0          0          0          0          0  758962.97  675738.95
   2 hours      traffic_out        MAX     775     774  106168.22  165690.73  2.0022e+6    8613.76          0          0          0          0          0  106168.22   85137.56
    1 days       traffic_in        MAX     797     797 1.1457e+14 1.8639e+15 3.0437e+16  288231.07          0          0          0          3          0 1.1457e+14  1.1201e+6
    1 days      traffic_out        MAX     797     797 1.1457e+14 1.8639e+15 3.0437e+16    7808.59          0          0          0          3          0 1.1457e+14   148302.9
    5 mins       traffic_in       LAST     600     594  331300.31  302042.64  1.3746e+6    1738.79          0          0          0          0          0  331300.31  301680.43
    5 mins      traffic_out       LAST     600     594   27600.07   63763.91  968253.19    1193.15          0          0          0          0          0   27600.07   20552.77
   30 mins       traffic_in       LAST     700     696  295206.27  290049.12  1.7565e+6   13538.93          0          0          0          0          0  295206.27  269343.65
   30 mins      traffic_out       LAST     700     696   30353.19   54203.68  755165.11    3852.44          0          0          0          0          0   30353.19   23674.92
   2 hours       traffic_in       LAST     775     771   302432.3  313040.09  3.9036e+6      460.5          0          0          0          0          0   302432.3  276005.83
   2 hours      traffic_out       LAST     775     771    34885.1   61289.43  900730.08     481.88          0          0          0          0          0    34885.1   28606.26
    1 days       traffic_in       LAST     797     796  271504.55  256971.08  4.8600e+6     310.02          0          0          0          0          0  271504.55  248606.02
    1 days      traffic_out       LAST     797     796   21796.31   119590.8  3.3052e+6     502.96          0          0          0          0          0   21796.31   13962.33

NOTE: Dryrun requested.  No updates performed
apache@thunderstorm ~/cacti.reub.net/htdocs/cli $ php removespikes.php --rrdfile=/var/www/cacti.reub.net/htdocs/rra/8/95.rrd --method=variance --outliers=10 --debug
DEBUG: Var Kill: Value '1.0782e+14', VarianceDev '2.3712e+5', VarianceLimit '2.3735e+8'
DEBUG: Var Kill: Value '2.1350e+14', VarianceDev '2.3712e+5', VarianceLimit '2.3735e+8'
DEBUG: Var Kill: Value '2.1805e+14', VarianceDev '2.3712e+5', VarianceLimit '2.3735e+8'
DEBUG: Var Kill: Value '1.0782e+14', VarianceDev '1.5789e+4', VarianceLimit '1.5805e+7'
DEBUG: Var Kill: Value '2.1350e+14', VarianceDev '1.5789e+4', VarianceLimit '1.5805e+7'
DEBUG: Var Kill: Value '2.1805e+14', VarianceDev '1.5789e+4', VarianceLimit '1.5805e+7'
DEBUG: Var Kill: Value '3.0437e+16', VarianceDev '1.1201e+6', VarianceLimit '1.1212e+9'
DEBUG: Var Kill: Value '3.0437e+16', VarianceDev '1.1201e+6', VarianceLimit '1.1212e+9'
DEBUG: Var Kill: Value '3.0437e+16', VarianceDev '1.1201e+6', VarianceLimit '1.1212e+9'
DEBUG: Var Kill: Value '3.0437e+16', VarianceDev '1.4830e+5', VarianceLimit '1.4845e+8'
DEBUG: Var Kill: Value '3.0437e+16', VarianceDev '1.4830e+5', VarianceLimit '1.4845e+8'
DEBUG: Var Kill: Value '3.0437e+16', VarianceDev '1.4830e+5', VarianceLimit '1.4845e+8'
DEBUG: Either variance or out_kills found
NOTE: Creating XML file '/tmp/95.dump.1765363513' from '/var/www/cacti.reub.net/htdocs/rra/8/95.rrd'
NOTE: Searching for Spikes in XML file '/tmp/95.dump.1765363513'

      Size       DataSource         CF Samples  NonNan        Avg     StdDev   MaxValue   MinValue  MaxStdDev  MinStdDev  StdKilled  VarKilled WindFilled  StdDevAvg     VarAvg
----------  --------------- ---------- ------- ------- ---------- ---------- ---------- ---------- ---------- ---------- ---------- ---------- ---------- ---------- ----------
    5 mins       traffic_in    AVERAGE     500     500  333998.68  300211.46  1.3746e+6   14944.05          0          0          0          0          0  333998.68  300348.66
    5 mins      traffic_out    AVERAGE     500     500   26666.15   66431.94  968253.19    4165.33          0          0          0          0          0   26666.15   19403.01
    5 mins       traffic_in    AVERAGE     600     598  335625.79  308694.57  1.3746e+6    1738.79          0          0          0          0          0  335625.79  304748.14
    5 mins      traffic_out    AVERAGE     600     598   27697.92   63750.97  968253.19    1193.15          0          0          0          0          0   27697.92   20702.78
   30 mins       traffic_in    AVERAGE     700     699  294558.54   266256.4  1.5844e+6   19286.43          0          0          0          0          0  294558.54  272509.44
   30 mins      traffic_out    AVERAGE     700     699   30180.45   48338.06  749596.44     4505.8          0          0          0          0          0   30180.45    24161.7
   2 hours       traffic_in    AVERAGE     775     774   317741.7  213505.15  1.4576e+6   27360.83          0          0          0          0          0   317741.7  301675.35
   2 hours      traffic_out    AVERAGE     775     774   36159.79   44730.68  228886.09    5614.73          0          0          0          0          0   36159.79   31800.14
    1 days       traffic_in    AVERAGE     797     797 6.7675e+11 1.1444e+13 2.1805e+14   60454.61          0          0          0          3          0 6.7675e+11  237115.64
    1 days      traffic_out    AVERAGE     797     797 6.7675e+11 1.1444e+13 2.1805e+14    1680.96          0          0          0          3          0 6.7675e+11   15789.49
    5 mins       traffic_in        MIN     600     594  331300.31  302042.64  1.3746e+6    1738.79          0          0          0          0          0  331300.31  301680.43
    5 mins      traffic_out        MIN     600     594   27600.07   63763.91  968253.19    1193.15          0          0          0          0          0   27600.07   20552.77
   30 mins       traffic_in        MIN     700     699  216380.31   243590.6  1.2765e+6    1738.79          0          0          0          0          0  216380.31  197233.96
   30 mins      traffic_out        MIN     700     699   17429.54   40584.11  704824.01    1193.15          0          0          0          0          0   17429.54   11800.12
   2 hours       traffic_in        MIN     775     774   86747.36  135790.15  833708.96      460.5          0          0          0          0          0   86747.36   73630.84
   2 hours      traffic_out        MIN     775     774   13241.94   30338.26  196876.83     481.88          0          0          0          0          0   13241.94     8924.8
    1 days       traffic_in        MIN     797     797    8117.67    6289.43   58166.85          0          0          0          0          0          0    8117.67    7555.97
    1 days      traffic_out        MIN     797     797    3190.95    2129.86   12142.17          0          0          0          0          0          0    3190.95    3050.86
    5 mins       traffic_in        MAX     500     500  333998.68  300211.46  1.3746e+6   14944.05          0          0          0          0          0  333998.68  300348.66
    5 mins      traffic_out        MAX     500     500   26666.15   66431.94  968253.19    4165.33          0          0          0          0          0   26666.15   19403.01
    5 mins       traffic_in        MAX     600     594  331300.31  302042.64  1.3746e+6    1738.79          0          0          0          0          0  331300.31  301680.43
    5 mins      traffic_out        MAX     600     594   27600.07   63763.91  968253.19    1193.15          0          0          0          0          0   27600.07   20552.77
   30 mins       traffic_in        MAX     700     699  440009.51  371534.07  3.5992e+6   27891.57          0          0          0          0          0  440009.51  403698.73
   30 mins      traffic_out        MAX     700     699   54717.07   92649.78  1.1317e+6    5212.83          0          0          0          0          0   54717.07   42779.46
   2 hours       traffic_in        MAX     775     774  758962.97  720155.13  9.1072e+6    47934.8          0          0          0          0          0  758962.97  675738.95
   2 hours      traffic_out        MAX     775     774  106168.22  165690.73  2.0022e+6    8613.76          0          0          0          0          0  106168.22   85137.56
    1 days       traffic_in        MAX     797     797 1.1457e+14 1.8639e+15 3.0437e+16  288231.07          0          0          0          3          0 1.1457e+14  1.1201e+6
    1 days      traffic_out        MAX     797     797 1.1457e+14 1.8639e+15 3.0437e+16    7808.59          0          0          0          3          0 1.1457e+14   148302.9
    5 mins       traffic_in       LAST     600     594  331300.31  302042.64  1.3746e+6    1738.79          0          0          0          0          0  331300.31  301680.43
    5 mins      traffic_out       LAST     600     594   27600.07   63763.91  968253.19    1193.15          0          0          0          0          0   27600.07   20552.77
   30 mins       traffic_in       LAST     700     696  295206.27  290049.12  1.7565e+6   13538.93          0          0          0          0          0  295206.27  269343.65
   30 mins      traffic_out       LAST     700     696   30353.19   54203.68  755165.11    3852.44          0          0          0          0          0   30353.19   23674.92
   2 hours       traffic_in       LAST     775     771   302432.3  313040.09  3.9036e+6      460.5          0          0          0          0          0   302432.3  276005.83
   2 hours      traffic_out       LAST     775     771    34885.1   61289.43  900730.08     481.88          0          0          0          0          0    34885.1   28606.26
    1 days       traffic_in       LAST     797     796  271504.55  256971.08  4.8600e+6     310.02          0          0          0          0          0  271504.55  248606.02
    1 days      traffic_out       LAST     797     796   21796.31   119590.8  3.3052e+6     502.96          0          0          0          0          0   21796.31   13962.33

NOTE: Backing Up '/var/www/cacti.reub.net/htdocs/rra/8/95.rrd' to '/var/www/cacti.reub.net/htdocs/cache/spikekill//95.rrd.1765363513'
NOTE: Re-Importing '/tmp/95.dump.1765363513' to '/var/www/cacti.reub.net/htdocs/rra/8/95.rrd'
NOTE: Spikes Found and Remediated.  Total Spikes (8)
apache@thunderstorm ~/cacti.reub.net/htdocs/cli $ php removespikes.php --rrdfile=/var/www/cacti.reub.net/htdocs/rra/8/95.rrd --method=variance --outliers=10 --debug --dryrun
DEBUG: Var Kill: Value '1.0782e+14', VarianceDev '2.3712e+5', VarianceLimit '2.3735e+8'
DEBUG: Var Kill: Value '2.1350e+14', VarianceDev '2.3712e+5', VarianceLimit '2.3735e+8'
DEBUG: Var Kill: Value '2.1805e+14', VarianceDev '2.3712e+5', VarianceLimit '2.3735e+8'
DEBUG: Var Kill: Value '1.0782e+14', VarianceDev '1.5789e+4', VarianceLimit '1.5805e+7'
DEBUG: Var Kill: Value '2.1350e+14', VarianceDev '1.5789e+4', VarianceLimit '1.5805e+7'
DEBUG: Var Kill: Value '2.1805e+14', VarianceDev '1.5789e+4', VarianceLimit '1.5805e+7'
DEBUG: Var Kill: Value '3.0437e+16', VarianceDev '1.1201e+6', VarianceLimit '1.1212e+9'
DEBUG: Var Kill: Value '3.0437e+16', VarianceDev '1.1201e+6', VarianceLimit '1.1212e+9'
DEBUG: Var Kill: Value '3.0437e+16', VarianceDev '1.1201e+6', VarianceLimit '1.1212e+9'
DEBUG: Var Kill: Value '3.0437e+16', VarianceDev '1.4830e+5', VarianceLimit '1.4845e+8'
DEBUG: Var Kill: Value '3.0437e+16', VarianceDev '1.4830e+5', VarianceLimit '1.4845e+8'
DEBUG: Var Kill: Value '3.0437e+16', VarianceDev '1.4830e+5', VarianceLimit '1.4845e+8'
DEBUG: Either variance or out_kills found
NOTE: Creating XML file '/tmp/95.dump.739735293' from '/var/www/cacti.reub.net/htdocs/rra/8/95.rrd'
NOTE: Searching for Spikes in XML file '/tmp/95.dump.739735293'

      Size       DataSource         CF Samples  NonNan        Avg     StdDev   MaxValue   MinValue  MaxStdDev  MinStdDev  StdKilled  VarKilled WindFilled  StdDevAvg     VarAvg
----------  --------------- ---------- ------- ------- ---------- ---------- ---------- ---------- ---------- ---------- ---------- ---------- ---------- ---------- ----------
    5 mins       traffic_in    AVERAGE     500     500  333998.68  300211.46  1.3746e+6   14944.05          0          0          0          0          0  333998.68  300348.66
    5 mins      traffic_out    AVERAGE     500     500   26666.15   66431.94  968253.19    4165.33          0          0          0          0          0   26666.15   19403.01
    5 mins       traffic_in    AVERAGE     600     600  334600.01  308597.99  1.3746e+6    1738.79          0          0          0          0          0  334600.01  303793.47
    5 mins      traffic_out    AVERAGE     600     600   27648.22   63736.78  968253.19    1193.15          0          0          0          0          0   27648.22   20675.48
   30 mins       traffic_in    AVERAGE     700     700  294295.16  266114.99  1.5844e+6   19286.43          0          0          0          0          0  294295.16  272270.73
   30 mins      traffic_out    AVERAGE     700     700   30164.67   48326.42  749596.44     4505.8          0          0          0          0          0   30164.67    24154.3
   2 hours       traffic_in    AVERAGE     775     775  317658.02  213212.95  1.4576e+6   27360.83          0          0          0          0          0  317658.02  301610.74
   2 hours      traffic_out    AVERAGE     775     775   36132.66   44718.21  228886.09    5614.73          0          0          0          0          0   36132.66   31778.07
    1 days       traffic_in    AVERAGE     797     797 6.7675e+11 1.1444e+13 2.1805e+14   60454.61          0          0          0          3          0 6.7675e+11  237115.64
    1 days      traffic_out    AVERAGE     797     797 6.7675e+11 1.1444e+13 2.1805e+14    1680.96          0          0          0          3          0 6.7675e+11   15789.49
    5 mins       traffic_in        MIN     600     594  331300.31  302042.64  1.3746e+6    1738.79          0          0          0          0          0  331300.31  301680.43
    5 mins      traffic_out        MIN     600     594   27600.07   63763.91  968253.19    1193.15          0          0          0          0          0   27600.07   20552.77
   30 mins       traffic_in        MIN     700     699  216380.31   243590.6  1.2765e+6    1738.79          0          0          0          0          0  216380.31  197233.96
   30 mins      traffic_out        MIN     700     699   17429.54   40584.11  704824.01    1193.15          0          0          0          0          0   17429.54   11800.12
   2 hours       traffic_in        MIN     775     774   86747.36  135790.15  833708.96      460.5          0          0          0          0          0   86747.36   73630.84
   2 hours      traffic_out        MIN     775     774   13241.94   30338.26  196876.83     481.88          0          0          0          0          0   13241.94     8924.8
    1 days       traffic_in        MIN     797     797    8117.67    6289.43   58166.85          0          0          0          0          0          0    8117.67    7555.97
    1 days      traffic_out        MIN     797     797    3190.95    2129.86   12142.17          0          0          0          0          0          0    3190.95    3050.86
    5 mins       traffic_in        MAX     500     500  333998.68  300211.46  1.3746e+6   14944.05          0          0          0          0          0  333998.68  300348.66
    5 mins      traffic_out        MAX     500     500   26666.15   66431.94  968253.19    4165.33          0          0          0          0          0   26666.15   19403.01
    5 mins       traffic_in        MAX     600     594  331300.31  302042.64  1.3746e+6    1738.79          0          0          0          0          0  331300.31  301680.43
    5 mins      traffic_out        MAX     600     594   27600.07   63763.91  968253.19    1193.15          0          0          0          0          0   27600.07   20552.77
   30 mins       traffic_in        MAX     700     699  440009.51  371534.07  3.5992e+6   27891.57          0          0          0          0          0  440009.51  403698.73
   30 mins      traffic_out        MAX     700     699   54717.07   92649.78  1.1317e+6    5212.83          0          0          0          0          0   54717.07   42779.46
   2 hours       traffic_in        MAX     775     774  758962.97  720155.13  9.1072e+6    47934.8          0          0          0          0          0  758962.97  675738.95
   2 hours      traffic_out        MAX     775     774  106168.22  165690.73  2.0022e+6    8613.76          0          0          0          0          0  106168.22   85137.56
    1 days       traffic_in        MAX     797     797 1.1457e+14 1.8639e+15 3.0437e+16  288231.07          0          0          0          3          0 1.1457e+14  1.1201e+6
    1 days      traffic_out        MAX     797     797 1.1457e+14 1.8639e+15 3.0437e+16    7808.59          0          0          0          3          0 1.1457e+14   148302.9
    5 mins       traffic_in       LAST     600     594  331300.31  302042.64  1.3746e+6    1738.79          0          0          0          0          0  331300.31  301680.43
    5 mins      traffic_out       LAST     600     594   27600.07   63763.91  968253.19    1193.15          0          0          0          0          0   27600.07   20552.77
   30 mins       traffic_in       LAST     700     696  295206.27  290049.12  1.7565e+6   13538.93          0          0          0          0          0  295206.27  269343.65
   30 mins      traffic_out       LAST     700     696   30353.19   54203.68  755165.11    3852.44          0          0          0          0          0   30353.19   23674.92
   2 hours       traffic_in       LAST     775     771   302432.3  313040.09  3.9036e+6      460.5          0          0          0          0          0   302432.3  276005.83
   2 hours      traffic_out       LAST     775     771    34885.1   61289.43  900730.08     481.88          0          0          0          0          0    34885.1   28606.26
    1 days       traffic_in       LAST     797     796  271504.55  256971.08  4.8600e+6     310.02          0          0          0          0          0  271504.55  248606.02
    1 days      traffic_out       LAST     797     796   21796.31   119590.8  3.3052e+6     502.96          0          0          0          0          0   21796.31   13962.33

NOTE: Dryrun requested.  No updates performed
apache@thunderstorm ~/cacti.reub.net/htdocs/cli $
```
Spikes are being detected correctly from what I can see, but not removed.
The graph of course still shows these big 240F spikes on the yearly view.
