### ISSUE TITLE
Illegal string offset

### ISSUE THREAD

**Issue by dsclassen** [Cacti/cacti#61]
When I switch to the Graph tab these errors are being triggering:

```
2016-09-02 10:43:23 - CMDPHP PHP ERROR WARNING Backtrace: (/graph_view.php: 229 api_tree_get_main)(/lib/api_tree.php: 556 draw_dhtml_tree_level_graphing)(/lib/html_tree.php: 394 CactiErrorHandler)(/lib/functions.php: 4137 cacti_debug_backtrace)
2016-09-02 10:43:23 - ERROR PHP WARNING: Illegal string offset 'id' in file: /www/cacti/lib/html_tree.php on line: 394
2016-09-02 10:43:23 - CMDPHP PHP ERROR WARNING Backtrace: (/graph_view.php: 229 api_tree_get_main)(/lib/api_tree.php: 556 draw_dhtml_tree_level_graphing)(/lib/html_tree.php: 394 CactiErrorHandler)(/lib/functions.php: 4137 cacti_debug_backtrace)
2016-09-02 10:43:23 - ERROR PHP WARNING: Illegal string offset 'id' in file: /www/cacti/lib/html_tree.php on line: 394
2016-09-02 10:43:23 - CMDPHP PHP ERROR WARNING Backtrace: (/graph_view.php: 229 api_tree_get_main)(/lib/api_tree.php: 556 draw_dhtml_tree_level_graphing)(/lib/html_tree.php: 394 CactiErrorHandler)(/lib/functions.php: 4137 cacti_debug_backtrace)
2016-09-02 10:43:23 - ERROR PHP WARNING: Illegal string offset 'id' in file: /www/cacti/lib/html_tree.php on line: 394
2016-09-02 10:43:23 - CMDPHP PHP ERROR WARNING Backtrace: (/graph_view.php: 229 api_tree_get_main)(/lib/api_tree.php: 556 draw_dhtml_tree_level_graphing)(/lib/html_tree.php: 400 CactiErrorHandler)(/lib/functions.php: 4137 cacti_debug_backtrace)
2016-09-02 10:43:23 - ERROR PHP WARNING: Illegal string offset 'id' in file: /www/cacti/lib/html_tree.php on line: 400
2016-09-02 10:43:23 - CMDPHP PHP ERROR WARNING Backtrace: (/graph_view.php: 229 api_tree_get_main)(/lib/api_tree.php: 556 draw_dhtml_tree_level_graphing)(/lib/html_tree.php: 400 CactiErrorHandler)(/lib/functions.php: 4137 cacti_debug_backtrace)
2016-09-02 10:43:23 - ERROR PHP WARNING: Illegal string offset 'id' in file: /www/cacti/lib/html_tree.php on line: 400
2016-09-02 10:43:23 - CMDPHP PHP ERROR WARNING Backtrace: (/graph_view.php: 229 api_tree_get_main)(/lib/api_tree.php: 556 draw_dhtml_tree_level_graphing)(/lib/html_tree.php: 400 CactiErrorHandler)(/lib/functions.php: 4137 cacti_debug_backtrace)
2016-09-02 10:43:23 - ERROR PHP WARNING: Illegal string offset 'id' in file: /www/cacti/lib/html_tree.php on line: 400
2016-09-02 10:43:23 - CMDPHP PHP ERROR WARNING Backtrace: (/graph_view.php: 229 api_tree_get_main)(/lib/api_tree.php: 556 draw_dhtml_tree_level_graphing)(/lib/html_tree.php: 400 CactiErrorHandler)(/lib/functions.php: 4137 cacti_debug_backtrace)
2016-09-02 10:43:23 - ERROR PHP WARNING: Illegal string offset 'id' in file: /www/cacti/lib/html_tree.php on line: 400
2016-09-02 10:43:23 - CMDPHP PHP ERROR WARNING Backtrace: (/graph_view.php: 229 api_tree_get_main)(/lib/api_tree.php: 556 draw_dhtml_tree_level_graphing)(/lib/html_tree.php: 400 CactiErrorHandler)(/lib/functions.php: 4137 cacti_debug_backtrace)
2016-09-02 10:43:23 - ERROR PHP WARNING: Illegal string offset 'id' in file: /www/cacti/lib/html_tree.php on line: 400
2016-09-02 10:43:23 - CMDPHP PHP ERROR WARNING Backtrace: (/graph_view.php: 229 api_tree_get_main)(/lib/api_tree.php: 556 draw_dhtml_tree_level_graphing)(/lib/html_tree.php: 400 CactiErrorHandler)(/lib/functions.php: 4137 cacti_debug_backtrace)
2016-09-02 10:43:23 - ERROR PHP WARNING: Illegal string offset 'id' in file: /www/cacti/lib/html_tree.php on line: 400
2016-09-02 10:43:23 - CMDPHP PHP ERROR WARNING Backtrace: (/graph_view.php: 229 api_tree_get_main)(/lib/api_tree.php: 556 draw_dhtml_tree_level_graphing)(/lib/html_tree.php: 400 CactiErrorHandler)(/lib/functions.php: 4137 cacti_debug_backtrace)
2016-09-02 10:43:23 - ERROR PHP WARNING: Illegal string offset 'id' in file: /www/cacti/lib/html_tree.php on line: 400
2016-09-02 10:43:23 - CMDPHP PHP ERROR WARNING Backtrace: (/graph_view.php: 229 api_tree_get_main)(/lib/api_tree.php: 556 draw_dhtml_tree_level_graphing)(/lib/html_tree.php: 400 CactiErrorHandler)(/lib/functions.php: 4137 cacti_debug_backtrace)
2016-09-02 10:43:23 - ERROR PHP WARNING: Illegal string offset 'id' in file: /www/cacti/lib/html_tree.php on line: 400
2016-09-02 10:43:23 - CMDPHP PHP ERROR WARNING Backtrace: (/graph_view.php: 229 api_tree_get_main)(/lib/api_tree.php: 556 draw_dhtml_tree_level_graphing)(/lib/html_tree.php: 400 CactiErrorHandler)(/lib/functions.php: 4137 cacti_debug_backtrace)
2016-09-02 10:43:23 - ERROR PHP WARNING: Illegal string offset 'id' in file: /www/cacti/lib/html_tree.php on line: 400
2016-09-02 10:43:23 - CMDPHP PHP ERROR WARNING Backtrace: (/graph_view.php: 229 api_tree_get_main)(/lib/api_tree.php: 556 draw_dhtml_tree_level_graphing)(/lib/html_tree.php: 400 CactiErrorHandler)(/lib/functions.php: 4137 cacti_debug_backtrace)
2016-09-02 10:43:23 - ERROR PHP WARNING: Illegal string offset 'id' in file: /www/cacti/lib/html_tree.php on line: 400
2016-09-02 10:43:23 - CMDPHP PHP ERROR WARNING Backtrace: (/graph_view.php: 229 api_tree_get_main)(/lib/api_tree.php: 556 draw_dhtml_tree_level_graphing)(/lib/html_tree.php: 400 CactiErrorHandler)(/lib/functions.php: 4137 cacti_debug_backtrace)
2016-09-02 10:43:23 - ERROR PHP WARNING: Illegal string offset 'id' in file: /www/cacti/lib/html_tree.php on line: 400
2016-09-02 10:43:23 - CMDPHP PHP ERROR WARNING Backtrace: (/graph_view.php: 229 api_tree_get_main)(/lib/api_tree.php: 556 draw_dhtml_tree_level_graphing)(/lib/html_tree.php: 400 CactiErrorHandler)(/lib/functions.php: 4137 cacti_debug_backtrace)
2016-09-02 10:43:23 - ERROR PHP WARNING: Illegal string offset 'id' in file: /www/cacti/lib/html_tree.php on line: 400
2016-09-02 10:43:23 - CMDPHP PHP ERROR WARNING Backtrace: (/graph_view.php: 229 api_tree_get_main)(/lib/api_tree.php: 556 draw_dhtml_tree_level_graphing)(/lib/html_tree.php: 400 CactiErrorHandler)(/lib/functions.php: 4137 cacti_debug_backtrace)
2016-09-02 10:43:23 - ERROR PHP WARNING: Illegal string offset 'id' in file: /www/cacti/lib/html_tree.php on line: 400
2016-09-02 10:43:23 - CMDPHP PHP ERROR WARNING Backtrace: (/graph_view.php: 229 api_tree_get_main)(/lib/api_tree.php: 556 draw_dhtml_tree_level_graphing)(/lib/html_tree.php: 400 CactiErrorHandler)(/lib/functions.php: 4137 cacti_debug_backtrace)
2016-09-02 10:43:23 - ERROR PHP WARNING: Illegal string offset 'id' in file: /www/cacti/lib/html_tree.php on line: 400
2016-09-02 10:43:23 - CMDPHP PHP ERROR WARNING Backtrace: (/graph_view.php: 229 api_tree_get_main)(/lib/api_tree.php: 556 draw_dhtml_tree_level_graphing)(/lib/html_tree.php: 400 CactiErrorHandler)(/lib/functions.php: 4137 cacti_debug_backtrace)
2016-09-02 10:43:23 - ERROR PHP WARNING: Illegal string offset 'id' in file: /www/cacti/lib/html_tree.php on line: 400
2016-09-02 10:43:23 - CMDPHP PHP ERROR WARNING Backtrace: (/graph_view.php: 229 api_tree_get_main)(/lib/api_tree.php: 556 draw_dhtml_tree_level_graphing)(/lib/html_tree.php: 400 CactiErrorHandler)(/lib/functions.php: 4137 cacti_debug_backtrace)
2016-09-02 10:43:23 - ERROR PHP WARNING: Illegal string offset 'id' in file: /www/cacti/lib/html_tree.php on line: 400
2016-09-02 10:43:23 - CMDPHP PHP ERROR WARNING Backtrace: (/graph_view.php: 229 api_tree_get_main)(/lib/api_tree.php: 556 draw_dhtml_tree_level_graphing)(/lib/html_tree.php: 400 CactiErrorHandler)(/lib/functions.php: 4137 cacti_debug_backtrace)
2016-09-02 10:43:23 - ERROR PHP WARNING: Illegal string offset 'id' in file: /www/cacti/lib/html_tree.php on line: 400
2016-09-02 10:43:23 - CMDPHP PHP ERROR WARNING Backtrace: (/graph_view.php: 229 api_tree_get_main)(/lib/api_tree.php: 556 draw_dhtml_tree_level_graphing)(/lib/html_tree.php: 400 CactiErrorHandler)(/lib/functions.php: 4137 cacti_debug_backtrace)
2016-09-02 10:43:23 - ERROR PHP WARNING: Illegal string offset 'id' in file: /www/cacti/lib/html_tree.php on line: 400
2016-09-02 10:43:23 - CMDPHP PHP ERROR WARNING Backtrace: (/graph_view.php: 229 api_tree_get_main)(/lib/api_tree.php: 556 draw_dhtml_tree_level_graphing)(/lib/html_tree.php: 400 CactiErrorHandler)(/lib/functions.php: 4137 cacti_debug_backtrace)
2016-09-02 10:43:23 - ERROR PHP WARNING: Illegal string offset 'id' in file: /www/cacti/lib/html_tree.php on line: 400
2016-09-02 10:43:23 - CMDPHP PHP ERROR WARNING Backtrace: (/graph_view.php: 229 api_tree_get_main)(/lib/api_tree.php: 556 draw_dhtml_tree_level_graphing)(/lib/html_tree.php: 400 CactiErrorHandler)(/lib/functions.php: 4137 cacti_debug_backtrace)
2016-09-02 10:43:23 - ERROR PHP WARNING: Illegal string offset 'id' in file: /www/cacti/lib/html_tree.php on line: 400
2016-09-02 10:43:23 - CMDPHP PHP ERROR WARNING Backtrace: (/graph_view.php: 229 api_tree_get_main)(/lib/api_tree.php: 556 draw_dhtml_tree_level_graphing)(/lib/html_tree.php: 400 CactiErrorHandler)(/lib/functions.php: 4137 cacti_debug_backtrace)
2016-09-02 10:43:23 - ERROR PHP WARNING: Illegal string offset 'id' in file: /www/cacti/lib/html_tree.php on line: 400
2016-09-02 10:43:23 - CMDPHP PHP ERROR WARNING Backtrace: (/graph_view.php: 229 api_tree_get_main)(/lib/api_tree.php: 556 draw_dhtml_tree_level_graphing)(/lib/html_tree.php: 392 CactiErrorHandler)(/lib/functions.php: 4137 cacti_debug_backtrace)
2016-09-02 10:43:23 - ERROR PHP WARNING: Illegal string offset 'id' in file: /www/cacti/lib/html_tree.php on line: 392
2016-09-02 10:43:23 - CMDPHP PHP ERROR WARNING Backtrace: (/graph_view.php: 229 api_tree_get_main)(/lib/api_tree.php: 556 draw_dhtml_tree_level_graphing)(/lib/html_tree.php: 392 CactiErrorHandler)(/lib/functions.php: 4137 cacti_debug_backtrace)
2016-09-02 10:43:23 - ERROR PHP WARNING: Illegal string offset 'id' in file: /www/cacti/lib/html_tree.php on line: 392
2016-09-02 10:43:23 - CMDPHP PHP ERROR WARNING Backtrace: (/graph_view.php: 229 api_tree_get_main)(/lib/api_tree.php: 556 draw_dhtml_tree_level_graphing)(/lib/html_tree.php: 392 CactiErrorHandler)(/lib/functions.php: 4137 cacti_debug_backtrace)
2016-09-02 10:43:23 - ERROR PHP WARNING: Illegal string offset 'id' in file: /www/cacti/lib/html_tree.php on line: 392
```

**Comment by cigamit** [comment]
thanks for logging this issue!

**Comment by cigamit** [comment]
resolved here https://github.com/Cacti/cacti/commit/860f3825cee3d9135d3feed76decbfa95c53f5c6

**Comment by dsclassen** [comment]
I'm on commit 2e7d0df and I'm still seeing these errors when I switch to the Graphs tab. It may be just a red herring, and it appears that my graphs are displaying properly and the functionality of the Graphs tab is fine. I just thought I'd let the developers know about it.

```
2016-09-21 08:38:04 - CMDPHP Filter Variable: graph_template_id, Must have a default and none is set
2016-09-21 08:38:04 - CMDPHP PHP ERROR WARNING Backtrace: (/graph_view.php: 229 api_tree_get_main)(/lib/api_tree.php: 556 draw_dhtml_tree_level_graphing)(/lib/html_tree.php: 392 CactiErrorHandler)(/lib/functions.php: 4160 cacti_debug_backtrace)
2016-09-21 08:38:04 - ERROR PHP WARNING: Illegal string offset 'id' in file: /www/cacti/lib/html_tree.php on line: 392
2016-09-21 08:38:04 - CMDPHP PHP ERROR WARNING Backtrace: (/graph_view.php: 229 api_tree_get_main)(/lib/api_tree.php: 556 draw_dhtml_tree_level_graphing)(/lib/html_tree.php: 392 CactiErrorHandler)(/lib/functions.php: 4160 cacti_debug_backtrace)
2016-09-21 08:38:04 - ERROR PHP WARNING: Illegal string offset 'id' in file: /www/cacti/lib/html_tree.php on line: 392
2016-09-21 08:38:04 - CMDPHP PHP ERROR WARNING Backtrace: (/graph_view.php: 229 api_tree_get_main)(/lib/api_tree.php: 556 draw_dhtml_tree_level_graphing)(/lib/html_tree.php: 392 CactiErrorHandler)(/lib/functions.php: 4160 cacti_debug_backtrace)
2016-09-21 08:38:04 - ERROR PHP WARNING: Illegal string offset 'id' in file: /www/cacti/lib/html_tree.php on line: 392
2016-09-21 08:38:04 - CMDPHP PHP ERROR WARNING Backtrace: (/graph_view.php: 229 api_tree_get_main)(/lib/api_tree.php: 556 draw_dhtml_tree_level_graphing)(/lib/html_tree.php: 398 CactiErrorHandler)(/lib/functions.php: 4160 cacti_debug_backtrace)
2016-09-21 08:38:04 - ERROR PHP WARNING: Illegal string offset 'id' in file: /www/cacti/lib/html_tree.php on line: 398
2016-09-21 08:38:04 - CMDPHP PHP ERROR WARNING Backtrace: (/graph_view.php: 229 api_tree_get_main)(/lib/api_tree.php: 556 draw_dhtml_tree_level_graphing)(/lib/html_tree.php: 398 CactiErrorHandler)(/lib/functions.php: 4160 cacti_debug_backtrace)
2016-09-21 08:38:04 - ERROR PHP WARNING: Illegal string offset 'id' in file: /www/cacti/lib/html_tree.php on line: 398
2016-09-21 08:38:04 - CMDPHP PHP ERROR WARNING Backtrace: (/graph_view.php: 229 api_tree_get_main)(/lib/api_tree.php: 556 draw_dhtml_tree_level_graphing)(/lib/html_tree.php: 398 CactiErrorHandler)(/lib/functions.php: 4160 cacti_debug_backtrace)
2016-09-21 08:38:04 - ERROR PHP WARNING: Illegal string offset 'id' in file: /www/cacti/lib/html_tree.php on line: 398
2016-09-21 08:38:04 - CMDPHP PHP ERROR WARNING Backtrace: (/graph_view.php: 229 api_tree_get_main)(/lib/api_tree.php: 556 draw_dhtml_tree_level_graphing)(/lib/html_tree.php: 398 CactiErrorHandler)(/lib/functions.php: 4160 cacti_debug_backtrace)
2016-09-21 08:38:04 - ERROR PHP WARNING: Illegal string offset 'id' in file: /www/cacti/lib/html_tree.php on line: 398
2016-09-21 08:38:04 - CMDPHP PHP ERROR WARNING Backtrace: (/graph_view.php: 229 api_tree_get_main)(/lib/api_tree.php: 556 draw_dhtml_tree_level_graphing)(/lib/html_tree.php: 398 CactiErrorHandler)(/lib/functions.php: 4160 cacti_debug_backtrace)
2016-09-21 08:38:04 - ERROR PHP WARNING: Illegal string offset 'id' in file: /www/cacti/lib/html_tree.php on line: 398
2016-09-21 08:38:04 - CMDPHP PHP ERROR WARNING Backtrace: (/graph_view.php: 229 api_tree_get_main)(/lib/api_tree.php: 556 draw_dhtml_tree_level_graphing)(/lib/html_tree.php: 398 CactiErrorHandler)(/lib/functions.php: 4160 cacti_debug_backtrace)
2016-09-21 08:38:04 - ERROR PHP WARNING: Illegal string offset 'id' in file: /www/cacti/lib/html_tree.php on line: 398
2016-09-21 08:38:04 - CMDPHP PHP ERROR WARNING Backtrace: (/graph_view.php: 229 api_tree_get_main)(/lib/api_tree.php: 556 draw_dhtml_tree_level_graphing)(/lib/html_tree.php: 398 CactiErrorHandler)(/lib/functions.php: 4160 cacti_debug_backtrace)
2016-09-21 08:38:04 - ERROR PHP WARNING: Illegal string offset 'id' in file: /www/cacti/lib/html_tree.php on line: 398
2016-09-21 08:38:04 - CMDPHP PHP ERROR WARNING Backtrace: (/graph_view.php: 229 api_tree_get_main)(/lib/api_tree.php: 556 draw_dhtml_tree_level_graphing)(/lib/html_tree.php: 398 CactiErrorHandler)(/lib/functions.php: 4160 cacti_debug_backtrace)
2016-09-21 08:38:04 - ERROR PHP WARNING: Illegal string offset 'id' in file: /www/cacti/lib/html_tree.php on line: 398
2016-09-21 08:38:04 - CMDPHP PHP ERROR WARNING Backtrace: (/graph_view.php: 229 api_tree_get_main)(/lib/api_tree.php: 556 draw_dhtml_tree_level_graphing)(/lib/html_tree.php: 398 CactiErrorHandler)(/lib/functions.php: 4160 cacti_debug_backtrace)
2016-09-21 08:38:04 - ERROR PHP WARNING: Illegal string offset 'id' in file: /www/cacti/lib/html_tree.php on line: 398
2016-09-21 08:38:04 - CMDPHP PHP ERROR WARNING Backtrace: (/graph_view.php: 229 api_tree_get_main)(/lib/api_tree.php: 556 draw_dhtml_tree_level_graphing)(/lib/html_tree.php: 398 CactiErrorHandler)(/lib/functions.php: 4160 cacti_debug_backtrace)
2016-09-21 08:38:04 - ERROR PHP WARNING: Illegal string offset 'id' in file: /www/cacti/lib/html_tree.php on line: 398
2016-09-21 08:38:04 - CMDPHP PHP ERROR WARNING Backtrace: (/graph_view.php: 229 api_tree_get_main)(/lib/api_tree.php: 556 draw_dhtml_tree_level_graphing)(/lib/html_tree.php: 398 CactiErrorHandler)(/lib/functions.php: 4160 cacti_debug_backtrace)
2016-09-21 08:38:04 - ERROR PHP WARNING: Illegal string offset 'id' in file: /www/cacti/lib/html_tree.php on line: 398
2016-09-21 08:38:04 - CMDPHP PHP ERROR WARNING Backtrace: (/graph_view.php: 229 api_tree_get_main)(/lib/api_tree.php: 556 draw_dhtml_tree_level_graphing)(/lib/html_tree.php: 398 CactiErrorHandler)(/lib/functions.php: 4160 cacti_debug_backtrace)
2016-09-21 08:38:04 - ERROR PHP WARNING: Illegal string offset 'id' in file: /www/cacti/lib/html_tree.php on line: 398
2016-09-21 08:38:04 - CMDPHP PHP ERROR WARNING Backtrace: (/graph_view.php: 229 api_tree_get_main)(/lib/api_tree.php: 556 draw_dhtml_tree_level_graphing)(/lib/html_tree.php: 398 CactiErrorHandler)(/lib/functions.php: 4160 cacti_debug_backtrace)
2016-09-21 08:38:04 - ERROR PHP WARNING: Illegal string offset 'id' in file: /www/cacti/lib/html_tree.php on line: 398
2016-09-21 08:38:04 - CMDPHP PHP ERROR WARNING Backtrace: (/graph_view.php: 229 api_tree_get_main)(/lib/api_tree.php: 556 draw_dhtml_tree_level_graphing)(/lib/html_tree.php: 398 CactiErrorHandler)(/lib/functions.php: 4160 cacti_debug_backtrace)
2016-09-21 08:38:04 - ERROR PHP WARNING: Illegal string offset 'id' in file: /www/cacti/lib/html_tree.php on line: 398
2016-09-21 08:38:04 - CMDPHP PHP ERROR WARNING Backtrace: (/graph_view.php: 229 api_tree_get_main)(/lib/api_tree.php: 556 draw_dhtml_tree_level_graphing)(/lib/html_tree.php: 398 CactiErrorHandler)(/lib/functions.php: 4160 cacti_debug_backtrace)
2016-09-21 08:38:04 - ERROR PHP WARNING: Illegal string offset 'id' in file: /www/cacti/lib/html_tree.php on line: 398
2016-09-21 08:38:04 - CMDPHP PHP ERROR WARNING Backtrace: (/graph_view.php: 229 api_tree_get_main)(/lib/api_tree.php: 556 draw_dhtml_tree_level_graphing)(/lib/html_tree.php: 398 CactiErrorHandler)(/lib/functions.php: 4160 cacti_debug_backtrace)
2016-09-21 08:38:04 - ERROR PHP WARNING: Illegal string offset 'id' in file: /www/cacti/lib/html_tree.php on line: 398
2016-09-21 08:38:04 - CMDPHP PHP ERROR WARNING Backtrace: (/graph_view.php: 229 api_tree_get_main)(/lib/api_tree.php: 556 draw_dhtml_tree_level_graphing)(/lib/html_tree.php: 398 CactiErrorHandler)(/lib/functions.php: 4160 cacti_debug_backtrace)
2016-09-21 08:38:04 - ERROR PHP WARNING: Illegal string offset 'id' in file: /www/cacti/lib/html_tree.php on line: 398
2016-09-21 08:38:04 - CMDPHP PHP ERROR WARNING Backtrace: (/graph_view.php: 229 api_tree_get_main)(/lib/api_tree.php: 556 draw_dhtml_tree_level_graphing)(/lib/html_tree.php: 398 CactiErrorHandler)(/lib/functions.php: 4160 cacti_debug_backtrace)
2016-09-21 08:38:04 - ERROR PHP WARNING: Illegal string offset 'id' in file: /www/cacti/lib/html_tree.php on line: 398
2016-09-21 08:38:04 - CMDPHP PHP ERROR WARNING Backtrace: (/graph_view.php: 229 api_tree_get_main)(/lib/api_tree.php: 556 draw_dhtml_tree_level_graphing)(/lib/html_tree.php: 398 CactiErrorHandler)(/lib/functions.php: 4160 cacti_debug_backtrace)
2016-09-21 08:38:04 - ERROR PHP WARNING: Illegal string offset 'id' in file: /www/cacti/lib/html_tree.php on line: 398
2016-09-21 08:38:04 - CMDPHP PHP ERROR WARNING Backtrace: (/graph_view.php: 229 api_tree_get_main)(/lib/api_tree.php: 556 draw_dhtml_tree_level_graphing)(/lib/html_tree.php: 398 CactiErrorHandler)(/lib/functions.php: 4160 cacti_debug_backtrace)
2016-09-21 08:38:04 - ERROR PHP WARNING: Illegal string offset 'id' in file: /www/cacti/lib/html_tree.php on line: 398
2016-09-21 08:38:04 - CMDPHP PHP ERROR WARNING Backtrace: (/graph_view.php: 229 api_tree_get_main)(/lib/api_tree.php: 556 draw_dhtml_tree_level_graphing)(/lib/html_tree.php: 398 CactiErrorHandler)(/lib/functions.php: 4160 cacti_debug_backtrace)
2016-09-21 08:38:04 - ERROR PHP WARNING: Illegal string offset 'id' in file: /www/cacti/lib/html_tree.php on line: 398
2016-09-21 08:38:04 - CMDPHP PHP ERROR WARNING Backtrace: (/graph_view.php: 229 api_tree_get_main)(/lib/api_tree.php: 556 draw_dhtml_tree_level_graphing)(/lib/html_tree.php: 390 CactiErrorHandler)(/lib/functions.php: 4160 cacti_debug_backtrace)
2016-09-21 08:38:04 - ERROR PHP WARNING: Illegal string offset 'id' in file: /www/cacti/lib/html_tree.php on line: 390
2016-09-21 08:38:04 - CMDPHP PHP ERROR WARNING Backtrace: (/graph_view.php: 229 api_tree_get_main)(/lib/api_tree.php: 556 draw_dhtml_tree_level_graphing)(/lib/html_tree.php: 390 CactiErrorHandler)(/lib/functions.php: 4160 cacti_debug_backtrace)
2016-09-21 08:38:04 - ERROR PHP WARNING: Illegal string offset 'id' in file: /www/cacti/lib/html_tree.php on line: 390
2016-09-21 08:38:04 - CMDPHP PHP ERROR WARNING Backtrace: (/graph_view.php: 229 api_tree_get_main)(/lib/api_tree.php: 556 draw_dhtml_tree_level_graphing)(/lib/html_tree.php: 390 CactiErrorHandler)(/lib/functions.php: 4160 cacti_debug_backtrace)
2016-09-21 08:38:04 - ERROR PHP WARNING: Illegal string offset 'id' in file: /www/cacti/lib/html_tree.php on line: 390
```

**Comment by cigamit** [comment]
yup, just resolved here: https://github.com/Cacti/cacti/commit/998adafc6c58754dbb11a17ada6bf4e3a134fa95
