### ISSUE TITLE
cacti 1.1.6 unable to enable snmp notification receiver mibs 

### ISSUE THREAD

**Issue by MyOwnMediaHub** [Cacti/cacti#672]
In console/utilities/system utilities/ snmp notification receivers;

if you add a snmp receiver then go to the notifications tab, select all mibs, change drop down to enable then press go, then press continue on the next page you will find that the notification mibs are still disabled and in the cacti log you will find the following;

2017-05-09 15:38:22 - CMDPHP PHP ERROR NOTICE Backtrace: (/managers.php: 58 manager_edit)(/managers.php: 335 manager_notifications)(/managers.php: 545 CactiErrorHandler)(/lib/functions.php: 4313 cacti_debug_backtrace)
2017-05-09 15:38:22 - ERROR PHP NOTICE: Undefined variable: item_rows in file: /var/www/html/cacti/managers.php on line: 545
2017-05-09 15:37:23 - CMDPHP PHP ERROR NOTICE Backtrace: (/managers.php: 58 manager_edit)(/managers.php: 335 manager_notifications)(/managers.php: 545 CactiErrorHandler)(/lib/functions.php: 4313 cacti_debug_backtrace)
2017-05-09 15:37:23 - ERROR PHP NOTICE: Undefined variable: item_rows in file: /var/www/html/cacti/managers.php on line: 545   

also note that a check on the table in MySQL 5.6 shows it to be empty
this has been the same issue on the following platforms using primary fresh installs as well as upgrades 
Ubuntu with MySQL 5.6  cacti 1.1.6
centos with MySQL 5.6 cacti 1.1.5
centos with MySQL 5.6 with cacti 1.1.2

**Comment by cigamit** [comment]
I corrected the warnings.  I'm not certain if that fixes everything though.

**Comment by MyOwnMediaHub** [comment]
Hi the warnings have gone which is a bonus but the notification mibs will still not enable, I have attached a screen shot.
![cacti snmp notification receivers](https://cloud.githubusercontent.com/assets/28554247/26040275/109339d0-3967-11e7-8f1d-748a2c387c50.png)
