### ISSUE TITLE
Translation Issues

### ISSUE THREAD

**Issue by jpobeda** [Cacti/cacti#756]
Hi there,

Have a look at the screenshots. Let me know if you need further details.
I guess these issues are cross every language.

![cacti_install_3](https://cloud.githubusercontent.com/assets/13456559/26572355/bf94bcf8-456d-11e7-9b87-c66cd893724a.png)
![cacti_gui_1](https://cloud.githubusercontent.com/assets/13456559/26572351/bf911b70-456d-11e7-9333-49be65d90500.png)
![cacti_gui_2](https://cloud.githubusercontent.com/assets/13456559/26572352/bf91455a-456d-11e7-9d6b-0c6948802db4.png)
![cacti_gui_3](https://cloud.githubusercontent.com/assets/13456559/26572350/bf83222c-456d-11e7-997c-2875a5aa1e29.png)
![cacti_gui_4](https://cloud.githubusercontent.com/assets/13456559/26572353/bf92563e-456d-11e7-976b-634173138f2b.png)
![cacti_gui_5](https://cloud.githubusercontent.com/assets/13456559/26572354/bf9333ec-456d-11e7-943c-cdc8957ebcf5.png)
![cacti_gui_6](https://cloud.githubusercontent.com/assets/13456559/26572356/bfad4034-456d-11e7-80d4-5b4bbe6ed45c.png)
![cacti_gui_7](https://cloud.githubusercontent.com/assets/13456559/26572362/bfd023a6-456d-11e7-9b5e-6e24894bb3c7.png)
![cacti_gui_8](https://cloud.githubusercontent.com/assets/13456559/26572358/bfba5990-456d-11e7-9970-56f7766dc884.png)
![cacti_gui_9](https://cloud.githubusercontent.com/assets/13456559/26572359/bfbce804-456d-11e7-8136-3dd9a6a722af.png)
![cacti_gui_10](https://cloud.githubusercontent.com/assets/13456559/26572361/bfc31396-456d-11e7-9f74-9aeceb5fc446.png)
![cacti_gui_11](https://cloud.githubusercontent.com/assets/13456559/26572360/bfc28110-456d-11e7-9c58-76c971c2281e.png)
![cacti_gui_12](https://cloud.githubusercontent.com/assets/13456559/26572363/bfe07260-456d-11e7-8cf7-eeecff1baf10.png)
![cacti_gui_13](https://cloud.githubusercontent.com/assets/13456559/26572364/bfe5a33e-456d-11e7-83e3-7d0dd6de38cc.png)
![cacti_gui_14](https://cloud.githubusercontent.com/assets/13456559/26572365/bfe7dece-456d-11e7-9844-a399723f503a.png)
![cacti_gui_help-menu](https://cloud.githubusercontent.com/assets/13456559/26572366/bfee8a12-456d-11e7-9ed6-ea0437eb9e65.png)
![cacti_install_1](https://cloud.githubusercontent.com/assets/13456559/26572367/bff5d114-456d-11e7-8b3b-724b860b457e.png)
![cacti_install_2](https://cloud.githubusercontent.com/assets/13456559/26572368/bff93732-456d-11e7-8b6f-697e63609835.png)

**Comment by cigamit** [comment]
Great post.  Thanks.

**Comment by cigamit** [comment]
Okay, most of these are resolved.  There are a few that are not however.  On the Paper-Plane theme, the dropdown that includes the help, and on the multi-select the 'Enter keywords' are still unresolved.  The multi-select is a upstream bug, but we may elect to resolve since we have forked this project anyway.  So, I'll leave this open for the moment.

**Comment by cigamit** [comment]
Resolved.

**Comment by jpobeda** [comment]
I've just downloaded 1.1.8 and so far most of the issues I've reported here are still present. Do you want me to open a new issue or re-open this with my findings? Or maybe the fixes didn't get in on this release.
