### ISSUE TITLE
Segfaults in apache error log

### ISSUE THREAD

**Issue by smiles1969** [Cacti/cacti#779]
After updating to 1.1.8 from 1.1.7, I'm getting segfaults in the apache error log:

[Thu Jun 01 16:54:14.981868 2017] [core:notice] [pid 889] AH00052: child pid 2196 exit signal Segmentation fault (11)

I'm able to log in and authenticate with Cacti, but then empty response and segfault in the log.

**Comment by cigamit** [comment]
That does not help.  Need more information.

**Comment by smiles1969** [comment]
root@ctcv-cacti2:/var/www/html/cacti# strace -s 256 -v -p 889
Process 889 attached
select(0, NULL, NULL, NULL, {0, 321045}) = 0 (Timeout)
wait4(-1, 0x7ffeb130182c, WNOHANG|WSTOPPED, NULL) = 0
select(0, NULL, NULL, NULL, {1, 0})     = 0 (Timeout)
wait4(-1, 0x7ffeb130182c, WNOHANG|WSTOPPED, NULL) = 0
select(0, NULL, NULL, NULL, {1, 0})     = 0 (Timeout)
wait4(-1, 0x7ffeb130182c, WNOHANG|WSTOPPED, NULL) = 0
select(0, NULL, NULL, NULL, {1, 0})     = 0 (Timeout)
wait4(-1, 0x7ffeb130182c, WNOHANG|WSTOPPED, NULL) = 0
select(0, NULL, NULL, NULL, {1, 0})     = 0 (Timeout)
clone(child_stack=0, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7f6da7e02a50) = 20953
wait4(-1, 0x7ffeb130182c, WNOHANG|WSTOPPED, NULL) = 0
select(0, NULL, NULL, NULL, {1, 0})     = 0 (Timeout)
wait4(-1, 0x7ffeb130182c, WNOHANG|WSTOPPED, NULL) = 0
select(0, NULL, NULL, NULL, {1, 0})     = 0 (Timeout)
wait4(-1, 0x7ffeb130182c, WNOHANG|WSTOPPED, NULL) = 0
select(0, NULL, NULL, NULL, {1, 0})     = ? ERESTARTNOHAND (To be restarted if no handler)
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_KILLED, si_pid=20455, si_uid=33, si_status=SIGSEGV, si_utime=35, si_stime=8} ---
select(0, NULL, NULL, NULL, {0, 822347}) = ? ERESTARTNOHAND (To be restarted if no handler)
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_KILLED, si_pid=20491, si_uid=33, si_status=SIGSEGV, si_utime=32, si_stime=8} ---
select(0, NULL, NULL, NULL, {0, 344559}) = 0 (Timeout)
clone(child_stack=0, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7f6da7e02a50) = 20961
wait4(-1, [{WIFSIGNALED(s) && WTERMSIG(s) == SIGSEGV}], WNOHANG|WSTOPPED, NULL) = 20455
write(2, "[Fri Jun 02 09:37:12.971470 2017] [core:notice] [pid 889] AH00052: child pid 20455 exit signal Segmentation fault (11)\n", 119) = 119
wait4(-1, [{WIFSIGNALED(s) && WTERMSIG(s) == SIGSEGV}], WNOHANG|WSTOPPED, NULL) = 20491
write(2, "[Fri Jun 02 09:37:12.972181 2017] [core:notice] [pid 889] AH00052: child pid 20491 exit signal Segmentation fault (11)\n", 119) = 119
wait4(-1, 0x7ffeb130182c, WNOHANG|WSTOPPED, NULL) = 0
select(0, NULL, NULL, NULL, {1, 0})     = ? ERESTARTNOHAND (To be restarted if no handler)
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_KILLED, si_pid=20496, si_uid=33, si_status=SIGSEGV, si_utime=37, si_stime=10} ---
select(0, NULL, NULL, NULL, {0, 728771}) = ? ERESTARTNOHAND (To be restarted if no handler)
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_KILLED, si_pid=20498, si_uid=33, si_status=SIGSEGV, si_utime=32, si_stime=4} ---
select(0, NULL, NULL, NULL, {0, 266608}) = 0 (Timeout)
clone(child_stack=0, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7f6da7e02a50) = 20962
wait4(-1, [{WIFSIGNALED(s) && WTERMSIG(s) == SIGSEGV}], WNOHANG|WSTOPPED, NULL) = 20496
write(2, "[Fri Jun 02 09:37:13.977338 2017] [core:notice] [pid 889] AH00052: child pid 20496 exit signal Segmentation fault (11)\n", 119) = 119
wait4(-1, [{WIFSIGNALED(s) && WTERMSIG(s) == SIGSEGV}], WNOHANG|WSTOPPED, NULL) = 20498
write(2, "[Fri Jun 02 09:37:13.977656 2017] [core:notice] [pid 889] AH00052: child pid 20498 exit signal Segmentation fault (11)\n", 119) = 119
wait4(-1, 0x7ffeb130182c, WNOHANG|WSTOPPED, NULL) = 0
select(0, NULL, NULL, NULL, {1, 0})     = ? ERESTARTNOHAND (To be restarted if no handler)
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_KILLED, si_pid=20504, si_uid=33, si_status=SIGSEGV, si_utime=32, si_stime=8} ---
select(0, NULL, NULL, NULL, {0, 764980}) = ? ERESTARTNOHAND (To be restarted if no handler)
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_KILLED, si_pid=20953, si_uid=33, si_status=SIGSEGV, si_utime=37, si_stime=5} ---
select(0, NULL, NULL, NULL, {0, 243861}) = 0 (Timeout)
clone(child_stack=0, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7f6da7e02a50) = 20963
wait4(-1, [{WIFSIGNALED(s) && WTERMSIG(s) == SIGSEGV}], WNOHANG|WSTOPPED, NULL) = 20504
write(2, "[Fri Jun 02 09:37:14.982460 2017] [core:notice] [pid 889] AH00052: child pid 20504 exit signal Segmentation fault (11)\n", 119) = 119
wait4(-1, [{WIFSIGNALED(s) && WTERMSIG(s) == SIGSEGV}], WNOHANG|WSTOPPED, NULL) = 20953
write(2, "[Fri Jun 02 09:37:14.982712 2017] [core:notice] [pid 889] AH00052: child pid 20953 exit signal Segmentation fault (11)\n", 119) = 119
wait4(-1, 0x7ffeb130182c, WNOHANG|WSTOPPED, NULL) = 0
select(0, NULL, NULL, NULL, {1, 0})     = ? ERESTARTNOHAND (To be restarted if no handler)
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_KILLED, si_pid=20961, si_uid=33, si_status=SIGSEGV, si_utime=30, si_stime=5} ---
select(0, NULL, NULL, NULL, {0, 763447}) = 0 (Timeout)
clone(child_stack=0, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7f6da7e02a50) = 20999
clone(child_stack=0, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7f6da7e02a50) = 21000
wait4(-1, [{WIFSIGNALED(s) && WTERMSIG(s) == SIGSEGV}], WNOHANG|WSTOPPED, NULL) = 20961
write(2, "[Fri Jun 02 09:37:15.990813 2017] [core:notice] [pid 889] AH00052: child pid 20961 exit signal Segmentation fault (11)\n", 119) = 119
wait4(-1, 0x7ffeb130182c, WNOHANG|WSTOPPED, NULL) = 0
select(0, NULL, NULL, NULL, {1, 0})     = 0 (Timeout)
clone(child_stack=0, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7f6da7e02a50) = 21018
clone(child_stack=0, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7f6da7e02a50) = 21019
clone(child_stack=0, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7f6da7e02a50) = 21020
clone(child_stack=0, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7f6da7e02a50) = 21021
wait4(-1, 0x7ffeb130182c, WNOHANG|WSTOPPED, NULL) = 0
select(0, NULL, NULL, NULL, {1, 0}^CProcess 889 detached

**Comment by smiles1969** [comment]
[Fri Jun 02 11:39:11.582498 2017] [:error] [pid 11106] [client 192.168.11.140:55102] PHP 251. read_user_setting() /var/www/html/cacti/lib/functions.php:4677, referer: http://192.168.11.15/cacti/index.php
[Fri Jun 02 11:39:11.582513 2017] [:error] [pid 11106] [client 192.168.11.140:55102] PHP 252. db_fetch_row_prepared() /var/www/html/cacti/lib/functions.php:228, referer: http://192.168.11.15/cacti/index.php
[Fri Jun 02 11:39:11.582531 2017] [:error] [pid 11106] [client 192.168.11.140:55102] PHP 253. cacti_log() /var/www/html/cacti/lib/database.php:301, referer: http://192.168.11.15/cacti/index.php
[Fri Jun 02 11:39:11.582539 2017] [:error] [pid 11106] [client 192.168.11.140:55102] PHP 254. date_time_format() /var/www/html/cacti/lib/functions.php:592, referer: http://192.168.11.15/cacti/index.php
[Fri Jun 02 11:39:11.582547 2017] [:error] [pid 11106] [client 192.168.11.140:55102] PHP 255. read_user_setting() /var/www/html/cacti/lib/functions.php:4677, referer: http://192.168.11.15/cacti/index.php
[Fri Jun 02 11:39:11.582561 2017] [:error] [pid 11106] [client 192.168.11.140:55102] PHP 256. db_fetch_row_prepared() /var/www/html/cacti/lib/functions.php:228, referer: http://192.168.11.15/cacti/index.php
[Fri Jun 02 11:39:11.582662 2017] [:error] [pid 11106] [client 192.168.11.140:55102] PHP Fatal error:  Maximum function nesting level of '256' reached, aborting! in Unknown on line 0, referer: http://192.168.11.15/cacti/index.php
[Fri Jun 02 11:39:11.582678 2017] [:error] [pid 11106] [client 192.168.11.140:55102] PHP Stack trace:, referer: http://192.168.11.15/cacti/index.php

**Comment by cigamit** [comment]
Looks like a recursive loop.  A couple questions, are you fully upgraded to 1.1.8?  Were you logging in when this happened?  What authentication method are you using?

**Comment by cigamit** [comment]
I just made some changes to the installer.  We are releasing tonight.  Should be solved.

**Comment by cigamit** [comment]
Marking this one resolved.

**Comment by smiles1969** [comment]
Still happening, even after upgrading to 1.1.9.
Just default authentication using cacti credentials.
This happens immediately after entering cacti username/password.
I've been trying to figure out where the loop is with xdebug, no luck so far.

**Comment by smiles1969** [comment]
PHP stack trace from apache error log:

[Mon Jun 05 09:52:55.628522 2017] [:error] [pid 31430] [client 192.168.11.140:53023] PHP 244. db_fetch_row_prepared() /var/www/html/cacti/lib/functions.php:228, referer: http://192.168.11.15/cacti/index.php
[Mon Jun 05 09:52:55.628527 2017] [:error] [pid 31430] [client 192.168.11.140:53023] PHP 245. cacti_log() /var/www/html/cacti/lib/database.php:301, referer: http://192.168.11.15/cacti/index.php
[Mon Jun 05 09:52:55.628531 2017] [:error] [pid 31430] [client 192.168.11.140:53023] PHP 246. date_time_format() /var/www/html/cacti/lib/functions.php:592, referer: http://192.168.11.15/cacti/index.php
[Mon Jun 05 09:52:55.628536 2017] [:error] [pid 31430] [client 192.168.11.140:53023] PHP 247. read_user_setting() /var/www/html/cacti/lib/functions.php:4688, referer: http://192.168.11.15/cacti/index.php
[Mon Jun 05 09:52:55.628541 2017] [:error] [pid 31430] [client 192.168.11.140:53023] PHP 248. db_fetch_row_prepared() /var/www/html/cacti/lib/functions.php:228, referer: http://192.168.11.15/cacti/index.php
[Mon Jun 05 09:52:55.628545 2017] [:error] [pid 31430] [client 192.168.11.140:53023] PHP 249. cacti_log() /var/www/html/cacti/lib/database.php:301, referer: http://192.168.11.15/cacti/index.php
[Mon Jun 05 09:52:55.628550 2017] [:error] [pid 31430] [client 192.168.11.140:53023] PHP 250. date_time_format() /var/www/html/cacti/lib/functions.php:592, referer: http://192.168.11.15/cacti/index.php
[Mon Jun 05 09:52:55.628554 2017] [:error] [pid 31430] [client 192.168.11.140:53023] PHP 251. read_user_setting() /var/www/html/cacti/lib/functions.php:4688, referer: http://192.168.11.15/cacti/index.php
[Mon Jun 05 09:52:55.628559 2017] [:error] [pid 31430] [client 192.168.11.140:53023] PHP 252. db_fetch_row_prepared() /var/www/html/cacti/lib/functions.php:228, referer: http://192.168.11.15/cacti/index.php
[Mon Jun 05 09:52:55.628563 2017] [:error] [pid 31430] [client 192.168.11.140:53023] PHP 253. cacti_log() /var/www/html/cacti/lib/database.php:301, referer: http://192.168.11.15/cacti/index.php
[Mon Jun 05 09:52:55.628567 2017] [:error] [pid 31430] [client 192.168.11.140:53023] PHP 254. date_time_format() /var/www/html/cacti/lib/functions.php:592, referer: http://192.168.11.15/cacti/index.php
[Mon Jun 05 09:52:55.628572 2017] [:error] [pid 31430] [client 192.168.11.140:53023] PHP 255. read_user_setting() /var/www/html/cacti/lib/functions.php:4688, referer: http://192.168.11.15/cacti/index.php
[Mon Jun 05 09:52:55.628576 2017] [:error] [pid 31430] [client 192.168.11.140:53023] PHP 256. db_fetch_row_prepared() /var/www/html/cacti/lib/functions.php:228, referer: http://192.168.11.15/cacti/index.php
[Mon Jun 05 09:52:55.628589 2017] [:error] [pid 31430] [client 192.168.11.140:53023] PHP Fatal error:  Maximum function nesting level of '256' reached, aborting! in Unknown on line 0, referer: http://192.168.11.15/cacti/index.php
[Mon Jun 05 09:52:55.628597 2017] [:error] [pid 31430] [client 192.168.11.140:53023] PHP Stack trace:, referer: http://192.168.11.15/cacti/index.php

**Comment by smiles1969** [comment]
I believe the recursion to be a result of this commit:

https://github.com/Cacti/cacti/commit/8a695b113c0f6fb8468d992630ae847e51117579

User is always 0 in every trace.

Here's the blame stack:

https://github.com/Cacti/cacti/blame/develop/lib/functions.php#L176

**Comment by cigamit** [comment]
As it should be in a normal setup.  Things like gexport will set the effective user to something other than 0.  And in cases where you are using the GUI, the user will be 0, but the $_SESSION['sess_user_id'] includes the real data.

I don't see any recursion there.  Is this happening when you view reports?  Again, the read_user_setting() looks clean to me.

**Comment by smiles1969** [comment]
This is happening immediately after I enter cacti credentials. I can not view any web page beyond attempting to login.

I should have stated that the effective user is always 0 on every trace. It doesn't appear to be getting the user value from the session.

Can you offer any suggestions on how I can provide more useful information or troubleshoot further? 

I would greatly appreciate it.

**Comment by smiles1969** [comment]
Enabled variable dump for xdebug stack trace:

[Thu Jun 08 10:22:09.238088 2017] [:error] [pid 26772] [client 192.168.11.140:61572] PHP   1. {main}() /var/www/html/cacti/index.php:0, referer: http://192.168.11.15/cacti/index.php
[Thu Jun 08 10:22:09.238093 2017] [:error] [pid 26772] [client 192.168.11.140:61572] PHP   2. include() /var/www/html/cacti/index.php:25, referer: http://192.168.11.15/cacti/index.php
[Thu Jun 08 10:22:09.238097 2017] [:error] [pid 26772] [client 192.168.11.140:61572] PHP   3. include() /var/www/html/cacti/include/auth.php:82, referer: http://192.168.11.15/cacti/index.php
[Thu Jun 08 10:22:09.238111 2017] [:error] [pid 26772] [client 192.168.11.140:61572] PHP   4. db_fetch_cell_prepared($sql = 'SELECT MAX(login_opts)\\n\\t\\t\\tFROM user_auth_group AS uag\\n\\t\\t\\tINNER JOIN user_auth_group_members AS uagm\\n\\t\\t\\tON uag.id=uagm.group_id\\n\\t\\t\\tWHERE user_id=?', $parms = array (0 => '1'), $col_name = *uninitialized*, $log = *uninitialized*, $db_conn = *uninitialized*) /var/www/html/cacti/auth_login.php:293, referer: http://192.168.11.15/cacti/index.php
[Thu Jun 08 10:22:09.238122 2017] [:error] [pid 26772] [client 192.168.11.140:61572] PHP   5. cacti_log($string = 'DEVEL: SQL Cell: "SELECT MAX(login_opts)   FROM user_auth_group AS uag   INNER JOIN user_auth_group_members AS uagm   ON uag.id=uagm.group_id   WHERE user_id=?"', $output = FALSE, $environ = 'DBCALL', $level = 6) /var/www/html/cacti/lib/database.php:240, referer: http://192.168.11.15/cacti/index.php
[Thu Jun 08 10:22:09.238127 2017] [:error] [pid 26772] [client 192.168.11.140:61572] PHP   6. date_time_format() /var/www/html/cacti/lib/functions.php:594, referer: http://192.168.11.15/cacti/index.php
[Thu Jun 08 10:22:09.238134 2017] [:error] [pid 26772] [client 192.168.11.140:61572] PHP   7. read_user_setting($config_name = 'default_date_format', $default = *uninitialized*, $force = *uninitialized*, $user = *uninitialized*) /var/www/html/cacti/lib/functions.php:4690, referer: http://192.168.11.15/cacti/index.php
[Thu Jun 08 10:22:09.238143 2017] [:error] [pid 26772] [client 192.168.11.140:61572] PHP   8. db_fetch_row_prepared($sql = 'SELECT value\\n\\t\\t\\tFROM settings_user\\n\\t\\t\\tWHERE name = ?\\n\\t\\t\\tAND user_id = ?', $parms = array (0 => 'default_date_format', 1 => '1'), $log = *uninitialized*, $db_conn = *uninitialized*) /var/www/html/cacti/lib/functions.php:230, referer: http://192.168.11.15/cacti/index.php
[Thu Jun 08 10:22:09.238152 2017] [:error] [pid 26772] [client 192.168.11.140:61572] PHP   9. cacti_log($string = 'DEVEL: SQL Row: "SELECT value   FROM settings_user   WHERE name = ?   AND user_id = ?"', $output = FALSE, $environ = 'DBCALL', $level = 6) /var/www/html/cacti/lib/database.php:301, referer: http://192.168.11.15/cacti/index.php
[Thu Jun 08 10:22:09.238157 2017] [:error] [pid 26772] [client 192.168.11.140:61572] PHP  10. date_time_format() /var/www/html/cacti/lib/functions.php:594, referer: http://192.168.11.15/cacti/index.php
[Thu Jun 08 10:22:09.238164 2017] [:error] [pid 26772] [client 192.168.11.140:61572] PHP  11. read_user_setting($config_name = 'default_date_format', $default = *uninitialized*, $force = *uninitialized*, $user = *uninitialized*) /var/www/html/cacti/lib/functions.php:4690, referer: http://192.168.11.15/cacti/index.php
[Thu Jun 08 10:22:09.238172 2017] [:error] [pid 26772] [client 192.168.11.140:61572] PHP  12. db_fetch_row_prepared($sql = 'SELECT value\\n\\t\\t\\tFROM settings_user\\n\\t\\t\\tWHERE name = ?\\n\\t\\t\\tAND user_id = ?', $parms = array (0 => 'default_date_format', 1 => '1'), $log = *uninitialized*, $db_conn = *uninitialized*) /var/www/html/cacti/lib/functions.php:230, referer: http://192.168.11.15/cacti/index.php
[Thu Jun 08 10:22:09.238182 2017] [:error] [pid 26772] [client 192.168.11.140:61572] PHP  13. cacti_log($string = 'DEVEL: SQL Row: "SELECT value   FROM settings_user   WHERE name = ?   AND user_id = ?"', $output = FALSE, $environ = 'DBCALL', $level = 6) /var/www/html/cacti/lib/database.php:301, referer: http://192.168.11.15/cacti/index.php
[Thu Jun 08 10:22:09.238187 2017] [:error] [pid 26772] [client 192.168.11.140:61572] PHP  14. date_time_format() /var/www/html/cacti/lib/functions.php:594, referer: http://192.168.11.15/cacti/index.php
[Thu Jun 08 10:22:09.238193 2017] [:error] [pid 26772] [client 192.168.11.140:61572] PHP  15. read_user_setting($config_name = 'default_date_format', $default = *uninitialized*, $force = *uninitialized*, $user = *uninitialized*) /var/www/html/cacti/lib/functions.php:4690, referer: http://192.168.11.15/cacti/index.php
[Thu Jun 08 10:22:09.238204 2017] [:error] [pid 26772] [client 192.168.11.140:61572] PHP  16. db_fetch_row_prepared($sql = 'SELECT value\\n\\t\\t\\tFROM settings_user\\n\\t\\t\\tWHERE name = ?\\n\\t\\t\\tAND user_id = ?', $parms = array (0 => 'default_date_format', 1 => '1'), $log = *uninitialized*, $db_conn = *uninitialized*) /var/www/html/cacti/lib/functions.php:230, referer: http://192.168.11.15/cacti/index.php
[Thu Jun 08 10:22:09.238214 2017] [:error] [pid 26772] [client 192.168.11.140:61572] PHP  17. cacti_log($string = 'DEVEL: SQL Row: "SELECT value   FROM settings_user   WHERE name = ?   AND user_id = ?"', $output = FALSE, $environ = 'DBCALL', $level = 6) /var/www/html/cacti/lib/database.php:301, referer: http://192.168.11.15/cacti/index.php
[Thu Jun 08 10:22:09.238219 2017] [:error] [pid 26772] [client 192.168.11.140:61572] PHP  18. date_time_format() /var/www/html/cacti/lib/functions.php:594, referer: http://192.168.11.15/cacti/index.php
[Thu Jun 08 10:22:09.238225 2017] [:error] [pid 26772] [client 192.168.11.140:61572] PHP  19. read_user_setting($config_name = 'default_date_format', $default = *uninitialized*, $force = *uninitialized*, $user = *uninitialized*) /var/www/html/cacti/lib/functions.php:4690, referer: http://192.168.11.15/cacti/index.php
[Thu Jun 08 10:22:09.238233 2017] [:error] [pid 26772] [client 192.168.11.140:61572] PHP  20. db_fetch_row_prepared($sql = 'SELECT value\\n\\t\\t\\tFROM settings_user\\n\\t\\t\\tWHERE name = ?\\n\\t\\t\\tAND user_id = ?', $parms = array (0 => 'default_date_format', 1 => '1'), $log = *uninitialized*, $db_conn = *uninitialized*) /var/www/html/cacti/lib/functions.php:230, referer: http://192.168.11.15/cacti/index.php
[Thu Jun 08 10:22:09.238243 2017] [:error] [pid 26772] [client 192.168.11.140:61572] PHP  21. cacti_log($string = 'DEVEL: SQL Row: "SELECT value   FROM settings_user   WHERE name = ?   AND user_id = ?"', $output = FALSE, $environ = 'DBCALL', $level = 6) /var/www/html/cacti/lib/database.php:301, referer: http://192.168.11.15/cacti/index.php
[Thu Jun 08 10:22:09.238248 2017] [:error] [pid 26772] [client 192.168.11.140:61572] PHP  22. date_time_format() /var/www/html/cacti/lib/functions.php:594, referer: http://192.168.11.15/cacti/index.php
[Thu Jun 08 10:22:09.238254 2017] [:error] [pid 26772] [client 192.168.11.140:61572] PHP  23. read_user_setting($config_name = 'default_date_format', $default = *uninitialized*, $force = *uninitialized*, $user = *uninitialized*) /var/www/html/cacti/lib/functions.php:4690, referer: http://192.168.11.15/cacti/index.php
[Thu Jun 08 10:22:09.238262 2017] [:error] [pid 26772] [client 192.168.11.140:61572] PHP  24. db_fetch_row_prepared($sql = 'SELECT value\\n\\t\\t\\tFROM settings_user\\n\\t\\t\\tWHERE name = ?\\n\\t\\t\\tAND user_id = ?', $parms = array (0 => 'default_date_format', 1 => '1'), $log = *uninitialized*, $db_conn = *uninitialized*) /var/www/html/cacti/lib/functions.php:230, referer: http://192.168.11.15/cacti/index.php

**Comment by smiles1969** [comment]
I have reverted back to older commits, and found the commit where this breaks is ae9acfd.

The recursion appears to be starting from the function cacti_log, with the settable date/time formatting.

I can run the latest commit if I change /lib/functions.php line 592 from:

$date = date(date_time_format());

back to it's original:

$date = date('Y-m-d H:i:s');

**Comment by smiles1969** [comment]
the values in my settings_user table for default_date_format and default_datechar were hosed, after correcting them, I'm able to run with no changes to current lastest commit.

Must have been a timing issue when I did git pull on how those records got the bogus values.

Perhaps some code to validate the stored values to prevent this scenario?

**Comment by reboot1983** [comment]
@smiles1969  I've added validation to prevent bogus values for default_datechar. I don't think it will prevent the recursion, but PR #815 should at least verify the correct default_datechar.

**Comment by reboot1983** [comment]
@smiles1969 Can you test something for me? Since I cannot reproduce this error, I want to ask you if you're able to test something for me. Can you change back the original code to:
`$date = date(date_time_format());`

And in functions.php; can you search for the function "date_time_format"; in this function you'll find a switch case for `$date_fmt`. In this switch case, the default case is: `return '';`

Can you change the default case: `return '';` into `return 'Y-m-d H:i:s';` to verify if this solves the problem?

Because: I think that while your Cacti is trying to write down a line in the cacti.log, it encounters an second error, which he also wants to write into the cacti.log, and while trying to write down the second line, it runs into a thirth error (here is where the recursion starts, because date() needs a valid parameter, and '' is not an valid parameter), and so on and so on...

**Comment by smiles1969** [comment]
I've tried that already.

I'm able to reproduce this reliably on this and other cacti instances running the latest commits.

If you enable DEVEL mode logging, it should happen for you as well. Try that and see if you can reproduce. Both my devel and production boxes had DEVEL level logging for some reason.

**Comment by cigamit** [comment]
This is resolved now.
