### ISSUE TITLE
Issue updating device hostname with SNMP data queries

### ISSUE THREAD

**Issue by acortiana** [Cacti/cacti#802]
I recently upgraded my 0.8.7g Cacti installation to 1.1.7 and now to 1.1.9. Spine poller.
Then I changed the "hostname" attribute of a few devices on the Cacti 1.1.9 installation.
These devices have "SNMP - Interface Statistics" data sources and other data sources.
I discovered that the realtime graph view functionality still tries to reach the devices for the "SNMP - Interface Statistics" data sources using the old hostname.
Other data sources in realtime graph view are correctly reached using the new hostname.
The spine poller also uses the new hostname for the standard polling.

I manually run the rebuild_poller_cache.php script and poller_reindex_hosts.php but the problem persists.
Accessing the database I discovered a strange behavior in the poller_item table.
On all hosts where I changed the "hostname" attribute, the "hostname" attribute is updated on every row except on the "SNMP - Interface Statistics" rows.
"SNMP - Interface Statistics" rows still have reference to the old "hostname".

The problem is only present on devices that where present on the old 0.8.7g installation.
If I create a new device (same configuration of an old one) and I change the "hostname" attribute, the modification is immediately propagated to the poller_item table on all rows.

Just for testing, I also restored the backup of the 0.8.7g Cacti installation and I tried to change the hostname of a device: the poller_item table is correctly updated on all rows.
So the problem appeared with the cacti upgrade.

I also found that this: https://moimeme.ca/linux/2014/12/cacti-issues/ fixes the issue.
But if I change the hostname of the device another time, you need to do it another time.

Any ideas?

**Comment by acortiana** [comment]
This: https://moimeme.ca/linux/2014/12/cacti-issues/
+ rebuild_poller_cache.php solves the problem.

But if I change the hostname of the device another time, you need to do it another time.

**Comment by cigamit** [comment]
Interesting, there were a few steps we de-contented from the reindex process to improve performance.  I think we should put them back in if this is the outcome.  It'll take a few days to investigate.  So, please be patient.

**Comment by cigamit** [comment]
This issue was actually a simpler fix than I thought.  We had a session array holding onto the old hostname.  So, when saving the device, and before repopulating the poller cache, we simply had to clear that session variable.  The issue is resolved.

**Comment by acortiana** [comment]
I tried the patch, installing the new lib/api_device.php file but the problem persists.
Steps that I followed:
1) identified an host with the problem, host_id=479. Only hosts created with previous version of cacti have that problem.
2) select host_id, hostname from poller_item where host_id=479;
+---------+---------------+
| host_id | hostname      |
+---------+---------------+
|     479 | new_hostname |
|     479 | new_hostname |
|     479 | old_hostname   |
|     479 | old_hostname    |
|     479 | old_hostname    |
|     479 | old_hostname    |
+---------+---------------+
3) downloaded and installed new lib/api_device.php
4) go to cacti web interface, edit device, click save
5) select host_id, hostname from poller_item where host_id=479;
+---------+---------------+
| host_id | hostname      |
+---------+---------------+
|     479 | new_hostname |
|     479 | new_hostname |
|     479 | old_hostname   |
|     479 | old_hostname    |
|     479 | old_hostname    |
|     479 | old_hostname    |
+---------+---------------+

**Comment by cigamit** [comment]
This looks like a separate issue.  Do this instead.

mysqldump poller_item > /tmp/poller_item_dump.sql
mysql cacti
delete from poller_item where host_id=479;

Then make the change.  Let me know the results of that test.  See if the 'old_hostname' items disappear.

**Comment by acortiana** [comment]
the old_hostname remains.

**Comment by acortiana** [comment]
As said in the previous posts, there is different behavior between old devices, created in the older version of cacti, and new ones. So I created a new host and I tried to understand where are the differences between the two hosts in the database. I found this difference.
If I try this query on "old devices":
```
SELECT data_input_data.value from data_input_data  
        JOIN data_input_fields ON data_input_data.data_input_field_id = data_input_fields.id  
        JOIN data_template_data ON data_input_data.data_template_data_id = data_template_data.id  
        JOIN data_local ON data_template_data.local_data_id = data_local.id  
        WHERE data_template_data.data_template_id=41 and  
              data_input_fields.data_name='management_ip' and  
              data_local.host_id='479';
```
I get this output:
+------------+
| value      |
+------------+
| old_address |
| old_address |
+------------+

The same query on new devices, I get no output.
If I modify the hostname of the "old device", the query still returns the old_address.
But if I remove these rows from data_input_data table, the problem is solved.
So, to solve the problem on all hosts, I used this query:
```
DELETE data_input_data.* from data_input_data 
        JOIN data_input_fields ON data_input_data.data_input_field_id = data_input_fields.id
        JOIN data_template_data ON data_input_data.data_template_data_id = data_template_data.id
        WHERE data_template_data.data_template_id=41 and data_input_fields.data_name='management_ip';
```

What do you think?

**Comment by acortiana** [comment]
@cigamit what do you think?
