### ISSUE TITLE
SQL error occurs when upgrading from 0.8.8h to 1.1.x

### ISSUE THREAD

**Issue by ftoyama** [Cacti/cacti#803]
When you upgrade from 0.8.8h to 1.1.x, it fails to create the table poller_resource_cache and poller_data_template_field_mappings.

This occurs in the upgrade program 1_0_0.php.
For utf8mb4 required by ver 1.1.x, an error occurs in SQL for ver 1.0.0.

The error when executing SQL manually is as follows：
"#1071 - Specified key was too long; max key length is 767 bytes"

**Comment by cigamit** [comment]
Should be resolved.

**Comment by ftoyama** [comment]
Hi,
I upgraded from 0.8.8h to 1.1.10.
An error still occurs in creating the `poller_data_template_field_mappings` table.

Probably, 1_0_0.php on line 1733 is not fixed.
`data_source_names` varchar(255) -> `data_source_names` varchar(191)

**Comment by cigamit** [comment]
Okay, made the changes for 1.1.11.
