### ISSUE TITLE
--input-fields variable not working with add_graphs.php cli

### ISSUE THREAD

**Issue by stormonts** [Cacti/cacti#841]
We have a data source that has a Custom Data input called "Instance".
![ds_template](https://user-images.githubusercontent.com/25824323/27971595-4ad6c650-6321-11e7-84cf-97e7b1ddb596.png)

The add_graphs.php script sees this:

cactiuser@util-st-01:/usr/local/cacti/cli> php add_graphs.php --list-input-fields --graph-template-id=137
Known Input Fields:(name, default, description)
143:instance Instance Name

However running the full add_graphs.php command and specifying the input field, leaves the field blank in the newly created data source.

cactiuser@util-st-01:/usr/local/cacti/cli> php add_graphs.php --graph-type=cg --graph-template-id=137 --host-id=92 --input-fields="143:instance=BEYONDINSIGHT" --force

![new_ds](https://user-images.githubusercontent.com/25824323/27971617-5eef100c-6321-11e7-8447-12dabe6e5ab0.png)

Wasn't sure if this was a bug or user error. I have tried it multiple times and the same thing happens.

**Comment by cigamit** [comment]
Should be resolved.  Please verify and close if resolved.

**Comment by stormonts** [comment]
It still isn't working for me.

cactiuser@util-st-01:/usr/local/cacti/cli> php add_graphs.php --graph-type=cg --graph-template-id=137 --host-id=92 --input-fields="143:instance=BEYONDINSIGHT" --force
PHP Notice:  Undefined offset: 1 in /usr/local/cacti-1.1.25/cli/add_graphs.php on line 494
PHP Stack trace:
PHP   1. {main}() /usr/local/cacti-1.1.25/cli/add_graphs.php:0
Graph Added - graph-id: (8070) - data-source-ids: (10663)

![image](https://user-images.githubusercontent.com/25824323/31513775-56895dae-af5d-11e7-81de-7784d021ce52.png)

**Comment by cigamit** [comment]
Use the development version, not the latest release.  That looks more like the latest release.

**Comment by stormonts** [comment]
Fixed in 1.1.26.  Thanks!
