### ISSUE TITLE
disable device(s) and graph view

### ISSUE THREAD

**Issue by dabeani** [Cacti/cacti#904]
if a device or devices will be disabled, it will be nice to make this devices invisible in the graph trees.
or is there some reason to not disable that devices in the graph trees?

**Comment by cigamit** [comment]
Great idea, thanks!

**Comment by cigamit** [comment]
Resolved.  Will be included as a User Setting in 1.1.18.

**Comment by smiles1969** [comment]
This new setting is causing aggregate graphs to not show in preview in "Reporting" tab. Also, the aggregate graphs are missing from emailed reports.

Unchecking the "Hide Disabled" option under the user settings tab restores normal functionality to both the preview and the emailed reports.

**Comment by smiles1969** [comment]
Clarification. Unchecking the "Hide Disabled" fixes preview and "Send Report" functionality, the event based emailed reports are still missing aggregate graphs.

**Comment by cigamit** [comment]
This should all be fixed now.
