### ISSUE TITLE
Graph image maps are buggy

### ISSUE THREAD

**Issue by eschoeller** [Cacti/cacti#932]
I can't capture this behavior in a screenshot. I have tried a few times. What I mean by "image map" is the javascript(?) overlay over the graphs which allows for the right-click menu and zoom cross-hair to work. Since upgrading from 1.1.16 to 1.1.19 the behavior of this "image map" has become completely erratic. I've seen this in both Firefox and Chrome, using linux. Sometimes I am able to right-click and get a web-browser right click menu, instead of the javascript menu (this does allow me to copy or save an image again! and drag and drop works too) sometimes the "image map" is off, so half of the graph has the normal functions and the other half of the graph does not. Sometimes the crosshair shows up over the graph legend, the graph zoom highlight region extends into the legend as well. 
Again, my apologies I can't really capture this in a screenshot.

**Comment by cigamit** [comment]
Use alt-print screen to do the image capture.  I'm still working on this disaster that was 1.1.18 and 1.1.19.  It's a bigger project than I expected, and time is fleeting (in other words I'm busy with other stuff too).  We definitely need a beta process moving forward.  I can't afford to give up my weekends continually.

**Comment by eschoeller** [comment]
I'm on KDE, not sure if that keybinding works or not but I'll play around with it. I hear you on the weekends, it's a real drag. I'll help out with betas.

**Comment by cigamit** [comment]
Thanks, these last two updates have not gone too well.

**Comment by cigamit** [comment]
This should be fixed now with 1.1.23.  Can you verify?

**Comment by eschoeller** [comment]
I'll upgrade in about an hour or so.

**Comment by eschoeller** [comment]
Sorry an hour turned into ... 2 days. I just upgraded. I still see this problem. I see people are doing animations now ... I'll see if I can figure out how to do that.

**Comment by eschoeller** [comment]
![peek 2017-09-17 15-53](https://user-images.githubusercontent.com/12864741/30525273-ac323e70-9bc0-11e7-91c2-bd5bf43bbdc9.gif)

**Comment by eschoeller** [comment]
![peek 2017-09-17 16-02](https://user-images.githubusercontent.com/12864741/30525332-c13c76ae-9bc1-11e7-9f72-5cc20fe7c80c.gif)
![image](https://user-images.githubusercontent.com/12864741/30525337-dc53d07c-9bc1-11e7-81fb-8bd688a36acf.png)

**Comment by cigamit** [comment]
Okay, now that browniebraun is back in town, I'll see if he can use this as an excuse to work on something.

**Comment by eschoeller** [comment]
Midori is also a problem ...

![peek 2017-09-17 16-11](https://user-images.githubusercontent.com/12864741/30525389-fdd31ebe-9bc2-11e7-9e0a-c3cc57f44a3c.gif)

![image](https://user-images.githubusercontent.com/12864741/30525393-0f972a6e-9bc3-11e7-8e3f-0362e657e289.png)

**Comment by eschoeller** [comment]
I've also noticed that the scroll wheel on my mouse doesn't appear to work reliably when the mouse is hovering over the graphs. I have to move it outside the image mapped areas to get the window to scroll reliably.

**Comment by cigamit** [comment]
Loving these animations everyone is doing.  Makes reproducing much easier.  Fixed!!!

**Comment by eschoeller** [comment]
hehe yeah, this "peek" application is a game changer. Super easy I'll be using it for all sorts of things now. I'm glad it's helping with the troubleshooting!

**Comment by eschoeller** [comment]
Confirmed fixed in 1.1.24 many thanks!

**Comment by eschoeller** [comment]
Scratch that. I still see it happening. I'm over on the graph preview tab now. 
![peek 2017-09-18 01-21](https://user-images.githubusercontent.com/12864741/30532166-01612bdc-9c10-11e7-8f84-d0a34beeb6e1.gif)

**Comment by eschoeller** [comment]
It seems like the zoom image map overaly is getting "stuck" on the last graph selected. If you switch between graphs the light gray overlay switches between graphs, but upon an event where the mouse leaves a graph and enters into whitespace, the overlay remains - and when you scroll that overlay is left behind. 
![peek 2017-09-18 01-33](https://user-images.githubusercontent.com/12864741/30532445-93daff64-9c11-11e7-88bf-efb0ea0bf332.gif)

**Comment by eschoeller** [comment]
I'm seeing it in tree view too.
