### ISSUE TITLE
CSV file shows incorrect for chinese language

### ISSUE THREAD

**Issue by vancefan** [Cacti/cacti#952]
After I export graph data to CSV file, I got the incorrect shows for chinese language. 

I use Cacti Version 1.1.20.

![image](https://user-images.githubusercontent.com/15649628/30005234-56509bce-9110-11e7-8520-8291963a6a41.png)

CSV file export from the follow graph:
![image](https://user-images.githubusercontent.com/15649628/30005267-38b0154e-9111-11e7-8714-bbae99904222.png)

**Comment by cigamit** [comment]
This is very odd.  I do not see us doing any i18n on CSV export, yet your header section of the CSV file (like Summary Details, Title, Vertical Label, Start Data, End Data, Step, and Rows) are all in Chinese.  Where did you download Cacti from?

**Comment by cigamit** [comment]
Should be resolved.  Please report using latest version of graph_xport.php in the develop branch.

**Comment by vancefan** [comment]
Thanks Cigamit.
I just download the latest version of graph_xport.php, still got the problem.  The difference is part of english words translated to Chinese.  Compare to the previous screenshot, the Chinese words was translated by me in the php file.

![image](https://user-images.githubusercontent.com/15649628/30028119-680eb566-91b6-11e7-8908-f60baabe72d1.png)

**Comment by cigamit** [comment]
Can you please do a select from the database for this data source?  Obtain the Graph Template ID for the specific graph and then run the following queries.  Provide the response screen shots using your database query tool of choice.  I would like to see if the values in the database are stored in Chinese.

`SELECT text_format FROM graph_templates_item WHERE graph_template_id=yourtemplate AND local_graph_id=0 AND graph_type_id=7;`
`SHOW CREATE TABLE graph_templates_item;`

Thanks!

**Comment by cigamit** [comment]
I just committed another attempt.

**Comment by vancefan** [comment]
Thanks for your quick update  :)
The lastest crack still not working.
Here is the screen shots:

![image](https://user-images.githubusercontent.com/15649628/30029934-d900af52-91bd-11e7-88d7-5e3d10ff470a.png)

![image](https://user-images.githubusercontent.com/15649628/30029969-f0aa3506-91bd-11e7-80a4-500cc97c4013.png)

**Comment by cigamit** [comment]
Please upload the latest csv output.

**Comment by cigamit** [comment]
Just performed another update.  This time, the escaping takes place only if the output is to the browser.

**Comment by vancefan** [comment]
Tried the latest vesion, still not working.
Attached the csv file.
[csv_file.zip](https://github.com/Cacti/cacti/files/1275009/csv_file.zip)

**Comment by cigamit** [comment]
Did you update both lib/rrd.php and graph_xport.php?

**Comment by vancefan** [comment]
Yes, both of them updated:

Following screen shots using Graph Utility View, still got the problem.

![image](https://user-images.githubusercontent.com/15649628/30032194-0256cde2-91c7-11e7-9424-66d7c34f1289.png)

**Comment by cigamit** [comment]
Well, we are getting there in any case.  It's pretty late there.  When how much time do you have?

**Comment by cigamit** [comment]
Can you do me a favor.  In your lib/html.php, there is a function called html_escape(), it's a simple one line function.  Can you please change the charset from 'UTF-8' to 'BIG5-HKSCS' and see if that makes a difference?  Another option would be to remove the `'UTF-8', true)`  off the end of that function, or change 'UTF-8' to ini_get('default_charset').  Let me know what works best.

**Comment by vancefan** [comment]
I tried all your suggestions, no works. I have to sleep now. Will reply your update tomorrow. Thanks for your help.

**Comment by vancefan** [comment]
Yes, it works now, thanks a lot 👍
